### ISSUE TITLE
Remove hard-coded host group names

### ISSUE THREAD

**Issue by eduardegorov** [ceph/ceph-ansible#1026]
`infrastructure-playbooks/purge-cluster.yml' playbook has definitions of host group names in the beginning of each play, e.g.:

``` yaml
    - name: purge ceph rgw cluster

  vars:
    rgw_group_name: ceph-rgws
```

However, group_vars file names are hardcoded and will not be included if custom host group names are used in inventory (see a fix for details - https://github.com/eduardegorov/ceph-ansible/commit/a8c7e62a9296d914b75bf549cbbc4ffffd1ad3bc ). Should I submit a pull-request for fixing it?

P.S. Sorry for newbie question - can spelling fixes be mixed with normal pull requests or individual PRs should be created for them?
