### ISSUE TITLE
Improving disk's device description

### ISSUE THREAD

**Issue by ErwanAliasr1** [ceph/ceph-ansible#1084]
Today, the actual sample file & usage is around pointing devices by /dev/sd* or similar.
Using a /dev/sd* naming isn't consistent across a cluster as 
- disks could be detected in a different order
- there is no guarantees of features & capabilities of a disk behind a /dev/sd* short name

Which leads to the following issue:
- How can I point the SSDs I have in my nodes to be a journal device ?
- How can I be sure I'm using the proper SCSI 15k 1TB disk as a data disk ? 

There is several options to be discussed on how to achieve that.

**Comment by ErwanAliasr1** [comment]
First idea, is using /dev/disk/by-id/* names like : 
/dev/disk/by-id/ata-SAMSUNG_MZ7LN512HCHP-000L1_S1ZKNXAGB23686

Pros:
- a path identify a vendor & product, so the pointed device is predictable (size / features / capabilities)
- this path is consistent over nodes & hardware setups

Cons:
- This path embed the serial number like 'S1ZKNXAGB23686' in my case. This imply being able to specify a path without the serial number maybe by using a star '*' but without taking the sub-partitions files like : ata-SAMSUNG_MZ7LN512HCHP-000L1_S1ZKNXAGB23686-part1
- Needs a particular entry for each hardware device type

**Comment by ErwanAliasr1** [comment]
Second idea would be adding a descriptive language to define what device we are looking for.

When we list devices to be used by ceph, we usually know what feature or capabilities we are looking at : like if we want to setup a cluster with 3x4TB disk per OSD with 1x 512 SSD for the journal

So the idea here would to point devices by features rather than name. This imply a kind of descriptive language like 

{'vendor':'SAMSUNG', size:'256G', 'rotational':'no'}

That's almost what we did in https://pypi.python.org/pypi/hardware

Pros:
- Devices are pointed by features, not by path

Cons:
- Required to setup a descriptive language & a tooling to elect the potential devices matching this criteria : using https://pypi.python.org/pypi/hardware ?

**Comment by leseb** [comment]
Example of a ceph_disk module:

```
- name: prepare osd disk
  ceph_disk:
    device: {{ item }}
    scenario: osd_colocation
    task: prepare
  with_items: "{{ devices }}"

- name: prepare osd disk
  ceph_disk:
    device: {{ item.0 }}
    journal_device: {{ item.1 }}
    scenario: dedicated_journal
    task: prepare
  with_together:
    - "{{ devices }}"
    - "{{ journal_device }}"

scenario:
  - journal_collocation
  - dedicated_device
  - dmcrypt
  - bluestore
  - directory

task:
  - prepare
  - activate
```
