### ISSUE TITLE
rolling_update hardcodes "ceph" cluster name for Upstart

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#1286]
Sebastien pointed out today that checking `/var/lib/ceph/mon/ceph-{{ ansible_hostname }}/upstart` hard-codes the cluster name as "ceph".

From `infrastructure-playbooks/rolling_update.yml`

```
    - name: check if upstart
      stat:
        path: /var/lib/ceph/mon/ceph-{{ ansible_hostname }}/upstart
      register: is_upstart
```
