### ISSUE TITLE
Deploy ceph cluster failed when I disable cephx

### ISSUE THREAD

**Issue by zealoussnow** [ceph/ceph-ansible#1300]
I don't want to enable cephx, so I set `cephx: false` in group_vars/all, and I get the flowing error message.

```yaml
TASK [ceph.ceph-common : fail if /var/lib/ceph/mon/ceph-kvm-ansible1/keyring doesn't exist] ***
fatal: [kvm-ansible1]: FAILED! => {"changed": false, "failed": true, "msg": "/var/lib/ceph/mon/ceph-kvm-ansible1/keyring not found"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/root/ceph-ansible/site.retry

PLAY RECAP *********************************************************************
kvm-ansible1               : ok=83   changed=7    unreachable=0    failed=1
```

**Comment by leseb** [comment]
@guits will take care of this.

**Comment by guits** [comment]
I can't reproduce your issue. Could you give me more details ?

Are you running ceph-ansible from master ?

 Could you provide the result of : 
`egrep -v '(^#|^$)' group_vars/all.yml`
`egrep -v '(^#|^$)' group_vars/osds.yml`

Which version of ansible are you using ?

**Comment by zealoussnow** [comment]
@guits 

Hello, I'm using ceph-ansible from master, the latest commit is

```
commit 5ddfc4f85cc189076f6a756dd19ffdfca3b3841e
Merge: 4ff5908 865b450
Author: Andrew Schoen <andrew.schoen@gmail.com>
Date:   Wed Feb 8 08:46:03 2017 -0600

    Merge pull request #1284 from ceph/BZ-1418980

    purge-cluster: do not use ceph-detect-init
```

egrep -v '(^#|^$)' group_vars/all.yml

```yml
---
dummy:
fetch_directory: fetch/
ceph_origin: 'upstream' # or 'distro' or 'local'
ceph_stable: true # use ceph stable branch
ceph_mirror: http://mirrors.163.com/ceph
ceph_stable_key: http://mirrors.163.com/ceph/keys/release.asc
generate_fsid: true
cephx: false
max_open_files: 131072
monitor_interface: eth0
journal_size: 2048 # OSD journal size in MB
public_network: 192.168.122.0/24
ceph_conf_overrides:
  global:
    osd_pool_default_size: 1
    osd_pool_default_min_size: 1
```

egrep -v '(^#|^$)' group_vars/osds.yml

```yml
---
dummy:
devices:
  - /dev/sdb
journal_collocation: true
```

ansible --version

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

The full log of playbook run:
[ceph-ansible.log](https://gist.github.com/zealoussnow/c60602754aa2b9fa0838751d5c64b914)
