### ISSUE TITLE
ubuntu permission in /run/ceph for ceph user

### ISSUE THREAD

**Issue by nabbar** [ceph/ceph-ansible#1583]
Permission denied when admin socket try to create the socket files in /run/ceph when the socket files does not exists.

Typical error when /run/ceph is empty and sudo is not installed : 
```
-1 asok ... AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-mon.5okl0xw8mc.asok': (13) Permission denied
```

With a little add in this file, it works : 
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/create_ceph_initial_dirs.yml#L10

```
    - /run/ceph
```

like this : 
```
---
- name: create ceph initial directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ceph
    group: ceph
    mode: 0755
  with_items:
    - /run/ceph
    - /etc/ceph
    - /var/lib/ceph/
    - /var/lib/ceph/mon
    - /var/lib/ceph/osd
    - /var/lib/ceph/mds
    - /var/lib/ceph/tmp
    - /var/lib/ceph/radosgw
    - /var/lib/ceph/bootstrap-rgw
    - /var/lib/ceph/bootstrap-mds
    - /var/lib/ceph/bootstrap-osd
```
