### ISSUE TITLE
Best way to add new nvme device to production raw_multi_journal deployment?

### ISSUE THREAD

**Issue by k0ste** [ceph/ceph-ansible#1614]
Hello.
I have cluster with raw_multi_journal. Now I need create new root with nvme only devices, for nvme only pool.
How to properly deploy new nvme osds (data and journal on same nvme drive)? AFAIK scenario's for osd role is mutually exclusive.

**Comment by k0ste** [comment]
@leseb, how do you think, I should do like this:

```yaml
---
### comment my production deployment configuration ###

# raw_multi_journal: 'true'
# devices:
#   - /dev/sda
#   - /dev/sdb
#   - /dev/sdc
#   - /dev/sdd
# raw_journal_devices:
#   - /dev/nvme0n1
#   - /dev/nvme0n1
#   - /dev/nvme0n1
#   - /dev/nvme0n1

### and define configuration for this case ###

journal_collocation: 'true'
devices:
  - /dev/nvme1n1
```

And deploy ceph-osd, or do it with hands (ceph-disk prepare, ceph-disk activate)?
