### ISSUE TITLE
ceph-mon role's enforcement of ceph:ceph ownership for mon directories is broken for upgrades

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1635]
In the `ceph-mon` role, `tasks/deploy_monitors.yml` contains:

```yaml
- name: create monitor directory
  file:
    path: /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
```

This breaks taking over an existing cluster and upgrading from hammer or any earlier release, where this directory would have been owned by `root:root`. If the user has set `setuser match path = /var/lib/ceph/$type/$cluster-$id`, then applying the `ceph-mon` role will result in the following situation:

- `/var/lib/ceph/$type/$cluster-$id` is owned by `ceph:ceph`.
- The subsequent mon restart results in `ceph-mon` dropping its root privileges and running as `ceph:ceph`.
- The files _contained within_ `/var/lib/ceph/$type/$cluster-$id` are still owned by `root:root`.
- `ceph-mon` is now unable to access the mon store, and aborts.

This should be easily fixed, [by adding `recurse: true` to the `file` invocation](http://docs.ansible.com/ansible/file_module.html#options).
