### ISSUE TITLE
Modify ceph_conf_overrides post install with docker

### ISSUE THREAD

**Issue by laggeduout** [ceph/ceph-ansible#1681]
I maybe using this option incorrectly so do correct me is my usage is just wrong.

I am deploying ceph 'L' using docker image tag-build-master-luminous-centos-7 with bluestore enabled and it is working well.

During the setup I put the below in group_vars/all.yml

```
ceph_conf_overrides:
  mon:
      mon_compact_on_start: true
      mon_allow_pool_delete: true
```

These settings get placed into the ceph.conf as we would expect:

```
[root@mon-01 ~]# cat /etc/ceph/ceph.conf | head -n3
[mon]
mon_allow_pool_delete = True
mon_compact_on_start = True
```

After the install I wanted to update the options to the below removing mon_allow_pool_delete: true
  
```
ceph_conf_overrides:
  mon:
      mon_compact_on_start: true
```

Then I re run site.yml and the change is not reflected in the ceph.conf, Also no handlers are being called, is this a problem or I am just misusing this?
