### ISSUE TITLE
stable-2.2: site.yml uninstalls ceph packages on Ubuntu Xenial after upgrade

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1732]
Original situation: Ubuntu Xenial, Jewel installed from distro (`xenial-updates`, running 10.2.9).

Ran `takeover-existing-cluster.yml` and then `site.yml`. All fine. At that time, used the following `group_vars/all.yml` in a test cluster:

```yaml
---
generate_fsid: false
fsid: 6e1b075a-7436-4e3e-bc6f-4b1c3bf13cf4
ceph_origin: distro
ceph_stable_release: jewel
monitor_interface: ens3
public_network: 192.168.122.0/24
radosgw_civetweb_port: 7480
ceph_conf_overrides:
  global:
    osd_pool_default_size: 2
    osd_pool_default_min_size: 1
    mon_pg_warn_max_per_osd: 4096
```

Then, changed to:

```yaml
generate_fsid: false
fsid: 6e1b075a-7436-4e3e-bc6f-4b1c3bf13cf4
ceph_origin: upstream
ceph_stable_release: luminous
monitor_interface: ens3
public_network: 192.168.122.0/24
radosgw_civetweb_port: 7480
ceph_conf_overrides:
  global:
    osd_pool_default_size: 2
    osd_pool_default_min_size: 1
    mon_pg_warn_max_per_osd: 4096
```

Ran `rolling-update.yml`, and then `site.yml` again. I end up with:

```
TASK [ceph-mon : start the monitor service] ***************************************************************************
fatal: [daisy]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service ceph-mon@dai
sy: host"}

fatal: [frank]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service ceph-mon@fra
nk: host"}

fatal: [eric]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service ceph-mon@eric
: host"}

        to retry, use: --limit @/home/training/ceph-ansible/site.retry

PLAY RECAP ************************************************************************************************************
daisy                      : ok=49   changed=5    unreachable=0    failed=1

deploy                     : ok=2    changed=0    unreachable=0    failed=0
eric                       : ok=47   changed=5    unreachable=0    failed=1

frank                      : ok=47   changed=5    unreachable=0    failed=1
```

And sure enough, if I shell into those boxes, **I see that the `ceph` package has been uninstalled**. What gives?
