### ISSUE TITLE
monitor_address_block not allowed

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#1837]
ceph-ansible started rejecting my use of **monitor_address_block** var.   Specifically you have to set either monitor_interface or monitor_address.   This is unfortunate because monitor_address_block is by far the easiest way to configure monitors.    The task that failed was [here](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/checks/check_mandatory_vars.yml#L78):
```
- name: make sure monitor_interface or monitor_address is defined
  fail:
    msg: "you must set monitor_interface or monitor_address"
  when:
    - monitor_interface == 'interface'
    - monitor_address == "0.0.0.0"
    - mon_group_name in group_names
```
It should have an additional when clause like **monitor_address_block | length == 0**.  However, in a different check  [here](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/check_mandatory_vars.yml#8), monitor_address_block is allowed.  Do we need both checks?

My other question is:  Shouldn't the value of **public_network** var be the default for **monitor_address_block** var?  That's what I typically set it to.  Then the user doesn't have to specify monitor addresses or interfaces at all in most cases, right?  

Same for radosgw_address_block var.
