### ISSUE TITLE
stable-2.2: purports to run on Ansible 2.1, but uses block name and listen in handlers

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1903]
http://docs.ceph.com/ceph-ansible/master/ says:

> stable-2.2 Support for ceph versions jewel and kraken. This branch supports ansible versions 2.1 and 2.2.2

... but in the `stable-2.2` branch, `roles/ceph-common/handlers/main.yml` contains:

```yaml
- block:
  - name: copy mon restart script
    template:
      src: restart_mon_daemon.sh.j2
      dest: /tmp/restart_mon_daemon.sh
      owner: root
      group: root
      mode: 0750
    listen: "restart ceph mons"

  - name: restart ceph mon daemon(s)
    command: /tmp/restart_mon_daemon.sh
    listen: "restart ceph mons"

  when:
# We do not want to run these checks on initial deployment (`socket.rc == 0`)
    - socket.rc == 0
    - ceph_current_fsid.rc == 0
    - mon_group_name in group_names

# This does not just restart OSDs but everything else too. Unfortunately
# at this time the ansible role does not have an OSD id list to use
# for restarting them specifically.
- block:
  - name: copy osd restart script
    template:
      src: restart_osd_daemon.sh.j2
      dest: /tmp/restart_osd_daemon.sh
      owner: root
      group: root
      mode: 0750
    listen: "restart ceph osds"

  - name: restart ceph osds daemon(s)
    command: /tmp/restart_osd_daemon.sh
    listen: "restart ceph osds"
    when: handler_health_osd_check

  when:
# We do not want to run these checks on initial deployment (`socket.rc == 0`)
    - socket.rc == 0
    - ceph_current_fsid.rc == 0
    - osd_group_name in group_names
# See https://github.com/ceph/ceph-ansible/issues/1457 for the condition below
    - inventory_hostname in play_hosts
```

- Support for `name` in blocks was added in Ansible 2.3, so this breaks on any prior Ansible version. See ansible/ansible#18985. 
- `listen` was added in Ansible 2.2, so that does not work on Ansible 2.1 either. 

However, `stable-2.2` deploys just fine with Ansible 2.3, so I'm not sure why the documentation seems to state you're not supposed to use it.
