### ISSUE TITLE
ceph.conf failing to generate due to missing monitor_secret

### ISSUE THREAD

**Issue by marksutherland** [ceph/ceph-ansible#2166]
I'm attempting to run the playbook with vagrant, and I'm finding that it can't seem to generate the `monitor_secret` which is stopping the `ceph.conf` file from being generated:

```
TASK [ceph-config : generate ceph configuration file: ceph.conf] ***************
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use 
ansible.module_utils._text.to_bytes instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use 
ansible.module_utils._text.to_text instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use 
ansible.module_utils._text.to_bytes instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use 
ansible.module_utils._text.to_text instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_bytes is deprecated.  Use 
ansible.module_utils._text.to_bytes instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ansible.utils.unicode.to_unicode is deprecated.  Use 
ansible.module_utils._text.to_text instead. This feature will be removed in 
version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
fatal: [mon0]: FAILED! => {"failed": true, "msg": "{{ monitor_keyring.stdout }}: 'dict object' has no attribute 'stdout'"}
fatal: [mon1]: FAILED! => {"failed": true, "msg": "{{ monitor_keyring.stdout }}: 'dict object' has no attribute 'stdout'"}
fatal: [mon2]: FAILED! => {"failed": true, "msg": "{{ monitor_keyring.stdout }}: 'dict object' has no attribute 'stdout'"}
```

It looks like `monitor_keyring` should be set by `ceph-common/tasks/facts_mon_fsid.yml` but this isn't run because `ceph_current_fsid.rc` is non-zero, because it failed when it couldn't find a `ceph.conf` file:

```
ok: [mon1] => {
    "ceph_current_fsid": {
        "changed": false, 
        "cmd": [
            "ceph", 
            "--connect-timeout", 
            "3", 
            "--cluster", 
            "ceph", 
            "fsid"
        ], 
        "delta": "0:00:03.761918", 
        "end": "2017-11-13 05:28:20.286618", 
        "failed": false, 
        "failed_when_result": false, 
        "msg": "non-zero return code", 
        "rc": 1, 
        "start": "2017-11-13 05:28:16.524700", 
        "stderr": "2017-11-13 05:28:17.385666 7f8fb4725700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc
/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory\nCluster connection interrupted or timed out", 
        "stderr_lines": [
            "2017-11-13 05:28:17.385666 7f8fb4725700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/
keyring,/etc/ceph/keyring.bin,: (2) No such file or directory", 
            "Cluster connection interrupted or timed out"
        ], 
        "stdout": "", 
        "stdout_lines": []
    }
}
```

This seems a bit circuitous and it's not obvious how to bootstrap past this.

I'm guessing there's some variable I haven't set, or have set incorrectly. Here is the contents of `all.yml`, `mons.yml` and `vagrant_variables.yml` for reference, much of which was taken from the sample files:

all.yml:
```
---
ceph_release_num:
  dumpling: 0.67
  emperor: 0.72
  firefly: 0.80
  giant: 0.87
  hammer: 0.94
  infernalis: 9
  jewel: 10
  kraken: 11
  luminous: 12
  mimic: 13
fetch_directory: fetch/
cluster: ceph
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
nfs_group_name: nfss
restapi_group_name: restapis
rbdmirror_group_name: rbdmirrors
client_group_name: clients
iscsi_gw_group_name: iscsi-gws
mgr_group_name: mgrs
debian_package_dependencies:
  - python-pycurl
  - hdparm
centos_package_dependencies:
  - python-pycurl
  - hdparm
  - epel-release
  - python-setuptools
  - libselinux-python
redhat_package_dependencies:
  - python-pycurl
  - hdparm
  - python-setuptools
ntp_service_enabled: true
bootstrap_dirs_owner: "64045"
bootstrap_dirs_group: "64045"
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: luminous
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
ceph_stable_redhat_distro: el7
monitor_interface: eth2
ip_version: ipv4
public_network: 172.27.220.0/24
cluster_network: "{{ public_network }}"
```

mons.yml:
```
---
monitor_secret: "{{ monitor_keyring.stdout }}"
admin_secret: 'admin_secret'
cephfs_pools:
  - { name: "{{ cephfs_data }}", pgs: "" }
  - { name: "{{ cephfs_metadata }}", pgs: "" }
openstack_config: false
osd_pool_default_pg_num: 0
openstack_glance_pool:
  name: images
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_cinder_pool:
  name: volumes
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_nova_pool:
  name: vms
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_cinder_backup_pool:
  name: backups
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_gnocchi_pool:
  name: metrics
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_pools:
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_nova_pool }}"
  - "{{ openstack_cinder_backup_pool }}"
  - "{{ openstack_gnocchi_pool }}"
```

vagrant_variables.yml:
```
---
docker: false
mon_vms: 3
osd_vms: 3
mds_vms: 0
rgw_vms: 0
nfs_vms: 0
rbd_mirror_vms: 0
client_vms: 0
iscsi_gw_vms: 0
mgr_vms: 0
restapi: true
public_subnet: 192.168.42
cluster_subnet: 192.168.43
memory: 512
eth: 'eth2'
disks: [ '/dev/sda', '/dev/sdb' ]
vagrant_box: centos/7
vagrant_sync_dir: /home/vagrant/sync
os_tuning_params:
  - { name: kernel.pid_max, value: 4194303 }
  - { name: fs.file-max, value: 26234859 }
debug: false
```

Note I'm using 'eth2' as I've added an extra interface to the Vagrantfile that will provide the VMs with access to the internet. I can't see how this would cause the issue I'm seeing however.

Any idea what I'm missing?
