### ISSUE TITLE
Mix ssd and sata disks on hosts (CRUSH Map)

### ISSUE THREAD

**Issue by tssvl** [ceph/ceph-ansible#2435]
Hello.
I have cluster with bunch of slow sata disks for backup.
Each server also has couple of ssd disks.
The idea is to build s3 compatible storage on slow disks and keep "rgw bucket index" on ssd pool.
So I need two crushmap roots SSD and SATA.

I am trying following:

```
ceph version: 12.2.4 luminous (stable)
ceph-ansible version: latest master
```

**/etc/host:**

```
192.168.0.10 my-ceph-s3-backup-1
192.168.0.10 my-ceph-s3-backup-1-ssd
```

**inventory.yml:**

```
osds:
  hosts:
    my-ceph-s3-backup-1:
      osd_crush_location: "{ 'root': 'HDD', 'rack': 'mon-rackkkk', 'pod': 'monpod', 'host': 'my-ceph-s3-backup-1' }"
      devices: ['/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh', '/dev/sdi', '/dev/sdj', '/dev/sdk', '/dev/sdl']
      dedicated_devices: ['/dev/sda', '/dev/sda', '/dev/sda', '/dev/sda', '/dev/sda', '/dev/sda', '/dev/sda', '/dev/sda', '/dev/sda']

    my-ceph-s3-backup-1-ssd:
      osd_crush_location: "{ 'root': 'SSD', 'rack': 'mon-rackkkk', 'pod': 'monpod', 'host': 'my-ceph-s3-backup-1-ssd' }"
      devices: ['/dev/sdb']
      osd_scenario: collocated
```

**group_vars/all.yml:**

```
      osd_objectstore: filestore
      osd_scenario: non-collocated

      crush_rule_config: true

      crush_rule_hdd:
        name: HDD
        root: HDD
        type: host
        default: false

      crush_rule_ssd:
        name: SSD
        root: SSD
        type: host
        default: false

      crush_rules:
        - "{{ crush_rule_hdd }}"
        - "{{ crush_rule_ssd }}"

      create_crush_tree: true
```

**expected result:**

host my-ceph-s3-backup-1-ssd have SSD as root.

**actual result:**

```
 ceph osd tree
ID CLASS WEIGHT   TYPE NAME                                   STATUS REWEIGHT PRI-AFF
-7       49.97276 root HDD
-4       49.97276     pod monpod
-3       49.97276         rack mon-rackkkk
-6       49.97276             host my-ceph-s3-backup-1
 1   hdd  5.45609                 osd.1                           up  1.00000 1.00000
 2   hdd  5.45609                 osd.2                           up  1.00000 1.00000
 3   hdd  5.45609                 osd.3                           up  1.00000 1.00000
 4   hdd  5.45609                 osd.4                           up  1.00000 1.00000
 5   hdd  5.45609                 osd.5                           up  1.00000 1.00000
 6   hdd  5.45609                 osd.6                           up  1.00000 1.00000
 7   hdd  5.45609                 osd.7                           up  1.00000 1.00000
 8   hdd  5.45609                 osd.8                           up  1.00000 1.00000
 9   hdd  5.45609                 osd.9                           up  1.00000 1.00000
 0   ssd  0.86800                 osd.0                           up  1.00000 1.00000
-2              0             host my-ceph-s3-backup-1-ssd
-5              0 root SSD
-1              0 root default
```

Is there any workaround of this problem?
