### ISSUE TITLE
fact gathering optimization for scalability

### ISSUE THREAD

**Issue by bengland2** [ceph/ceph-ansible#2553]
The [gather and delegate facts](https://github.com/ceph/ceph-ansible/blob/master/site-docker.yml.sample#L29) task is not scalable, and requires in general O(N^2) fact-gathering operations per host, but it is not clear to me why that should be.  I have run tests with this patch that just gathers facts on a host ONCE, instead of N times, and ceph-ansible succeeds just the same.  The effect on memory consumption and time to execute this task is dramatic.  Particularly for HCI configurations, this could make a big difference in scalability of ceph-ansible.  

```
--- /usr/share/ceph-ansible/site-docker.yml.sample.v31_orig	2018-04-30 19:53:30.539611319 +0000
+++ /usr/share/ceph-ansible/site-docker.yml.sample	2018-04-30 22:05:00.561611319 +0000
@@ -24,26 +24,16 @@
     - name: gather facts
       setup:
       when:
-        - not delegate_facts_host | bool or inventory_hostname in groups.get('clients', [])
+        - not delegate_facts_host | bool
 
     - name: gather and delegate facts
       setup:
-      delegate_to: "{{ item }}"
-      delegate_facts: True
-      with_items: "{{ groups['all'] | difference(groups.get('clients', [])) }}"
       when:
         - delegate_facts_host | bool
 ```
Here's a graph of ansible RSS and virtual memory consumption before the patch, with --forks 25, 3 [osds] hosts, 3 [mons] hosts, and 80 [clients] hosts, running ansible 2.4.3 and ceph-ansible-3.1.0-0.1.beta8 starting at 18:35:
![cephans31-fork25](https://user-images.githubusercontent.com/1717107/39523853-06efa83a-4de5-11e8-84fa-1ffa3ba73144.png)

And here's the same exact run with the patch, starting at 19:56:

![cephans31-factpatch-fork25](https://user-images.githubusercontent.com/1717107/39523882-1fd12d10-4de5-11e8-89d3-75ca55083ef9.png)

elapsed time for this one fact gathering task drops from 5 minutes to about 1 minute, and RSS drops from 8 GB to about 2 GB.

**Comment by bengland2** [comment]
The above patch should not work in general, as @guits explained to me, because ansible modules are interpreting vars about host B on the remote system A, so facts have to be gathered about B on the remote system A to allow these variables to be used (his example below).

However, it may be possible to cut down on the possible (A, B) combinations that have to be fact-gathered to lower the work done in this task from O(N^2) to O(N), where N is the number of hosts in the ansible inventory file.

- RADOS clients and OSDs find out about other OSDs, storage pools, etc. by talking to the monitors, not through ceph-ansible.  So *in theory* it should be sufficient for each non-monitor host to gather facts about itself and about the 3 monitor hosts (so that ceph.conf can be constructed).
- we don't need all facts about the monitor hosts, probably just a subset including network information. 
- monitors have to know about all other hosts so that they can construct crush maps, build MDS filesystems, etc.  But there are only 3 of these, so it's not so bad.

This might not be that hard to verify -- i.e. search for references to ansible "groups" var.  A preliminary search seemed to confirm this.

So the resulting patch might look something like this - only limited testing so far:

```
    # fact gathering delegation allows modules on remote hosts
    # to access information about other hosts
    
    # this step allows monitors to know cluster configuration
    
    - name: monitors gather facts about everyone
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] }}"
      when:
        - inventory_hostname in groups.get('mons', [])

    # this step allows any host to construct a ceph.conf, for example
    
    - name: everyone gathers facts about monitors
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['mons'] }}"
      when:
        - inventory_hostname not in groups.get('mons', [])
```
I am testing this on a 3-node cluster with a single monitor and all other roles defined on the other 2 nodes, using site.yml, and I verified that no fact gathering was done between pairs of non-monitor hosts, therefore it is now O(N) computational complexity. 

background: Guillaume Abrioux provided this example illustrating why ceph-ansible requires remote hosts to have facts about other hosts on hand:

```
# site.yml
---
- hosts:
    - osds
  gather_facts: true

  roles:
    - role: defaults
    - role: osd
    
# roles/osd/tasks/main.yml
- name: test
  debug:
    msg: "{{ hostvars['mon0']['ansible_all_ipv4_addresses'] }}"
```
results in output like this:
```
TASK [osd : test] **************************************************************************************************************************************************************************************************************************************************************
fatal: [osd0]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_all_ipv4_addresses'\n\nThe error appears to have been in '/Users/guits/GIT/playbook-test/roles/osd/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: test\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'ansible_all_ipv4_addresses'"}
fatal: [osd1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_all_ipv4_addresses'\n\nThe error appears to have been in '/Users/guits/GIT/playbook-test/roles/osd/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: test\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'ansible_all_ipv4_addresses'"}
```
