### ISSUE TITLE
ceph-default role should not restart all mons in a cluster

### ISSUE THREAD

**Issue by vishalkanaujia** [ceph/ceph-ansible#2630]
The current task to restart mons in a cluster is as follows:

```
./roles/ceph-defaults/handlers/main.yml
- name: restart ceph mon daemon(s) - non container
  command: /usr/bin/env bash /tmp/restart_mon_daemon.sh
  listen: "restart ceph mons"
  when:
    # We do not want to run these checks on initial deployment (`socket.rc == 0`)
    - mon_group_name in group_names
    - not containerized_deployment
    - hostvars[item]['_mon_handler_called'] | default(False)
    - mon_socket_stat.rc == 0
  with_items: "{{ groups[mon_group_name] }}"
  delegate_to: "{{ item }}"
  run_once: True

```
However, it could cause an outage (all mons appear down) in a live production cluster where all mons took some time to come up.

Solution
======
We shouldperform this task serially for each mon at a time. I'll send a PR for this fix.

```
- name: restart ceph mon daemon(s) - non container
  command: /usr/bin/env bash /tmp/restart_mon_daemon.sh
  listen: "restart ceph mons"
  when:
    # We do not want to run these checks on initial deployment (`socket.rc == 0`)
    - mon_group_name in group_names
    - not containerized_deployment
    - hostvars[item]['_mon_handler_called'] | default(False)
    - mon_socket_stat.rc == 0
  with_items: "{{ groups[mon_group_name] }}"
  delegate_to: "{{ item }}"
  run_once: True
  serial: 1
```
