### ISSUE TITLE
Syntax error in rgw multisite task

### ISSUE THREAD

**Issue by vishalkanaujia** [ceph/ceph-ansible#2704]
The playbook roles/ceph-rgw/tasks/multisite/master.yml has a syntax error in the when clause:

```
   command: radosgw-admin zonegroup create --rgw-zonegroup={{ rgw_zonegroup }} --endpoints=http://{{ ansible_fqdn }}:{{ radosgw_civetweb_port }} --master --default
   run_once: true
   when:
        - 'No such file or directory' in zonegroupcheck.stderr
        - rgw_zonemaster
   notify:
       - update period
```
The check `'No such file or directory'` in zonegroupcheck.stderr should be as `"'No such file or directory' in zonegroupcheck.stderr"`
