### ISSUE TITLE
ceph-mon  create filesystem pools  failure

### ISSUE THREAD

**Issue by cy-lee** [ceph/ceph-ansible#274]
Hi @leseb , I encountered same problem as @dfarrar117  reported in issue #254

Here is my environment and console output.

#### Vagrant version
1.7.2

#### Guest OS
ubuntu/trusty64

#### Ceph version
ceph version 0.94.1 (e4bfad3a3c51054df7e537a724c8d0bf9be972ff)

#### vagrant_variables.yml 

```yaml
---

# DEFINE THE NUMBER OF VMS TO RUN
mon_vms: 3
osd_vms: 3
mds_vms: 1
rgw_vms: 1
client_vms: 0
# Enable Keystone authentication
radosgw_keystone: true
# SUBNET TO USE FOR THE VMS
subnet: 192.168.42

# MEMORY
memory: 1024

# VAGRANT BOX
# Fedora: http://download.fedoraproject.org/pub/fedora/linux/releases/test/22_Alpha/Cloud/x86_64/Images/Fedora-Cloud-Atomic-Vagrant-22_Alpha-20150305.x86_64.vsphere.ova
# Ubuntu: ubuntu/trusty
# CentOS: chef/centos-7.0
# For more boxes have a look at:
#   - https://atlas.hashicorp.com/boxes/search?utf8=✓&sort=&provider=virtualbox&q=
#   - https://download.gluster.org/pub/gluster/purpleidea/vagrant/
vagrant_box: ubuntu/trusty64

```

#### Console output

https://gist.github.com/cy-lee/3cc4e074a166a94a1d89
