### ISSUE TITLE
Error creating ceph.conf

### ISSUE THREAD

**Issue by verdurin** [ceph/ceph-ansible#2876]
I'm seeing this error when I try to create a `luminous` cluster:
```
fatal: [ceph0]: FAILED! => {
    "msg": "'dict object' has no attribute u'ipv4'"
}
```

This is presumably because that interface has no IP address yet. 

If I change the `monitor_interface` to refer to an interface that already has an IP, I see this error:
```
fatal: [ceph0]: FAILED! => {
    "msg": "No first item, sequence was empty."
}
```

Here are the values I've added to `group_vars/all.yml`:
```
osd_scenario: lvm
osd_objectstore: bluestore
lvm_volumes:
  - data: /dev/sda
    db: db-sda-lv
    db_vg: pilot-ceph0
    wal: wal-sda-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdb
    db: db-sdb-lv
    db_vg: pilot-ceph0
    wal: wal-sdb-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdc
    db: db-sdc-lv
    db_vg: pilot-ceph0
    wal: wal-sdc-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdd
    db: db-sdd-lv
    db_vg: pilot-ceph0
    wal: wal-sdd-lv
    wal_vg: pilot-ceph0
  - data: /dev/sde
    db: db-sde-lv
    db_vg: pilot-ceph0
    wal: wal-sde-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdf
    db: db-sdf-lv
    db_vg: pilot-ceph0
    wal: wal-sdf-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdg
    db: db-sdg-lv
    db_vg: pilot-ceph0
    wal: wal-sdg-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdh
    db: db-sdh-lv
    db_vg: pilot-ceph0
    wal: wal-sdh-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdi
    db: db-sdi-lv
    db_vg: pilot-ceph0
    db: db-sdi-lv
    db_vg: pilot-ceph0
    wal: wal-sdi-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdj
    db: db-sdj-lv
    db_vg: pilot-ceph0
    wal: wal-sdj-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdk
    db: db-sdk-lv
    db_vg: pilot-ceph0
    wal: wal-sdk-lv
    wal_vg: pilot-ceph0
  - data: /dev/sdl
    db: db-sdl-lv
    db_vg: pilot-ceph0
    wal: wal-sdl-lv
    wal_vg: pilot-ceph0

ceph_origin: "repository"

ceph_repository:  "community"

ceph_stable_release: "luminous"

radosgw_address_block: "172.16.16.0/24"

monitor_interface: "eno4"

public_network: "172.16.48.0/24"

cluster_network: "172.16.64.0/24"

ip_version: "ipv4"
```

I've seen the same error or very similar errors with `stable-3.0`, `stable-3.1` and `master`.
