### ISSUE TITLE
corporate security does not like 0755 mode on directories

### ISSUE THREAD

**Issue by artur-fijalkowski** [ceph/ceph-ansible#2920]
**By default multiple directories (/etc/ceph, /var/lib/ceph) get 0755 mode**
Corporate security departments do not like to see 0755 mode on any directories without valid reasoning.
This always need evaluation when creating security papers.

**As first step creating directories should have configurable mode**
```yaml
# from ceph-ansible/roles/ceph-defaults/tasks/create_ceph_initial_dirs.yml
---
- name: set_fact ceph_directories
  set_fact:
    ceph_directories:
      - /etc/ceph
      - /var/lib/ceph/
      - /var/lib/ceph/mon
      - /var/lib/ceph/osd
      - /var/lib/ceph/mds
      - /var/lib/ceph/tmp
      - /var/lib/ceph/radosgw
      - /var/lib/ceph/bootstrap-rgw
      - /var/lib/ceph/bootstrap-mds
      - /var/lib/ceph/bootstrap-osd
      - /var/lib/ceph/bootstrap-rbd
      - /var/run/ceph

- name: create ceph initial directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ceph_uid }}"
    group: "{{ ceph_uid }}"
    mode: 0755
  with_items: "{{ ceph_directories }}"
```

Can be converted to following:

```yaml
# from ceph-ansible/roles/ceph-defaults/tasks/create_ceph_initial_dirs.yml
---
- name: set_fact ceph_directories
  set_fact:
    ceph_directories:
      - /etc/ceph
      - /var/lib/ceph/
      - /var/lib/ceph/mon
      - /var/lib/ceph/osd
      - /var/lib/ceph/mds
      - /var/lib/ceph/tmp
      - /var/lib/ceph/radosgw
      - /var/lib/ceph/bootstrap-rgw
      - /var/lib/ceph/bootstrap-mds
      - /var/lib/ceph/bootstrap-osd
      - /var/lib/ceph/bootstrap-rbd
      - /var/run/ceph

- name: create ceph initial directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ceph_uid }}"
    group: "{{ ceph_uid }}"
    mode: "{{ ceph_directories_mode | default('0755') }}"
  with_items: "{{ ceph_directories }}"
```

**After parametrizing mode for directories corporate user can choose access rights**
After this change anyone for whom it matters can easily overwrite access mode via `group_vars/all.yml`

**This change adds functionality without braking anything**
Simple to do ;)
