### ISSUE TITLE
Unsafe /tmp/ file use in ceph-ansible

### ISSUE THREAD

**Issue by mcv21** [ceph/ceph-ansible#2937]
**Bug Report**

Hi,

I've been migrating our local setup to v3.0.39, and discovered that ceph-ansible is now using predictable files/filenames in `/tmp` instead of e.g. the Ansible `tempfile` module in several places This is not best security practice (cf https://cwe.mitre.org/data/definitions/377.html and more generally https://cwe.mitre.org/data/definitions/376.html )

eg 1: roles/ceph-config/tasks/main.yml
```YAML
  - name: template ceph_conf_overrides
    copy:
      content: "{{ ceph_conf_overrides }}"
      dest: "/tmp/ceph_conf_overrides_temp_{{ ansible_hostname }}"
```

eg 2: roles/ceph-docker-common/tasks/fetch_image.yml
```YAML
- name: export local ceph dev image
  local_action:
    module: command
      docker save -o "/tmp/{{ ceph_docker_username }}-{{ ceph_docker_imagename }}-{{ ceph_docker_image_tag }}.tar" "{{ ceph_docker_username }}/{{ ceph_docker_imagename }}:{{ ceph_docker_image_tag }}"
  when:
    - (ceph_docker_dev_image is defined and ceph_docker_dev_image)
  run_once: true
                                                                               -
- name: copy ceph dev image file
  copy:
    src: "/tmp/{{ ceph_docker_username }}-{{ ceph_docker_imagename }}-{{ ceph_docker_image_tag}}.tar"
    dest: "/tmp/{{ ceph_docker_username }}-{{ ceph_docker_imagename }}-{{ ceph_docker_image_tag }}.tar"
  when:
    - (ceph_docker_dev_image is defined and ceph_docker_dev_image)
```

eg 3: roles/ceph-defaults/handlers/main.yml
```YAML
- name: copy mon restart script
  template:
    src: restart_mon_daemon.sh.j2
    dest: /tmp/restart_mon_daemon.sh
    owner: root
    group: root
    mode: 0750
```
[and many examples in that file]

`git grep /tmp` is probably a good way to find most/all of these. The right thing to do, I think, is instead use `tempfile` and register the `path` it returns.

**Environment**:
* Ubuntu 16.04
* kernel  4.4.0-93-generic
* Ansible 2.4.4.0
* ceph-ansible version v3.0.39
* ceph version 10.2.9 (Jewel)

**Comment by leseb** [comment]
That'd nice indeed, unfortunately, I don't think we have the bandwidth at the moment. However, if you want to take a stab at it, you're more than welcome :).

**Comment by mcv21** [comment]
Hi,
Any chance of a review (or, better a pull :) ) on the PRs I put in to fix this issue, please? 
Thanks.

**Comment by leseb** [comment]
Sorry for the delay, we are going to look into this ASAP, but in the meantime can you please check the CI and see why it was failing? Thanks!

**Comment by mcv21** [comment]
Just having a look at this; logs say:
```
RUNNING HANDLER [ceph-defaults : make tempdir for scripts] *********************
skipping: [osd0] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
```

which suggests something is defining `tmpdirpath`, since that task is:
```YAML
- name: make tempdir for scripts
  tempfile:
    state: directory
    prefix: ceph_ansible
  listen:
    - "restart ceph mons"
    - "restart ceph osds"
    - "restart ceph mdss"
    - "restart ceph rgws"
    - "restart ceph nfss"
    - "restart ceph rbdmirrors"
    - "restart ceph mgrs"
  register: tmpdirpath
  when: tmpdirpath is not defined
```

...and that's why the task is eventually failing, because we later try and copy a file to `dest: "{{tmpdirpath.path}}/restart_osd_daemon.sh"` and it doesn't exist because the task that makes it is being skipped.

Is it plausible that some bit of the testing rig is setting `tmpdirpath`? I can't find anything in the repo proper that does so...

**Comment by mcv21** [comment]
[pushing a test commit to check this theory]

**Comment by mcv21** [comment]
Something strange is happening in the CI - see https://2.jenkins.ceph.com/job/ceph-ansible-prs-luminous-ooo_collocation/257/consoleFull and search for `xxx` which I put in my debug handler - the first few times everything works as expected, then (when doing ceph-mgr) it doesn't call the first couple of handlers:

```
RUNNING HANDLER [ceph-defaults : make tempdir for scripts] *********************
Wednesday 26 September 2018  15:26:37 +0000 (0:00:00.048)       0:15:44.512 *** 
skipping: [mon0] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}

RUNNING HANDLER [ceph-defaults : xxx show tmpdirpath] **************************
Wednesday 26 September 2018  15:26:37 +0000 (0:00:00.054)       0:15:44.566 *** 
ok: [mon0] => {
    "tmpdirpath": {
        "changed": false, 
        "skip_reason": "Conditional result was False", 
        "skipped": true
    }
}
```

I think this must be a bug, since that task doesn't _have_ a conditional:
```YAML
- name: xxx show tmpdirpath
  debug:
    var: tmpdirpath
  listen:
    - "restart ceph mons"
    - "restart ceph osds"
    - "restart ceph mdss"
    - "restart ceph rgws"
    - "restart ceph nfss"
    - "restart ceph rbdmirrors"
    - "restart ceph mgrs"
    - "restart ceph tcmu-runner"
    - "restart ceph rbd-target-gw"
    - "restart ceph rbd-target-api"

```

I don't _think_ this is my fault, but perhaps I'm missing something obvious...
