### ISSUE TITLE
INFO:ceph-create-keys:ceph-mon is not in quorum: u'probing'

### ISSUE THREAD

**Issue by sunnoy** [ceph/ceph-ansible#2981]
### ceph ansible

```bash
ceph-ansible-stable-3.1
```
### ansible

```bash
ansible 2.5.3
```

### os

```bash
CentOS Linux release 7.5.1804 (Core)
```

### the files to ues
host file  **updated**
```bash
[mons]
192.168.12.69
192.168.12.70
192.168.12.71
[mgrs]
192.168.12.69
[osds]
192.168.12.69 devices="[ '/dev/vdb' ]"
192.168.12.70 devices="[ '/dev/vdb' ]"
192.168.12.71 devices="[ '/dev/vdb' ]"
```

group_vars/all.yml   **updated**

```yml
ceph_origin: repository
ceph_repository: community
ceph_mirror: http://mirrors.aliyun.com/ceph
ceph_stable_key: http://mirrors.aliyun.com/ceph/keys/release.asc
ceph_stable_release: luminous
ceph_stable_repo: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}"
fsid: 6ed9e8b2-1f5c-4358-be73-5c3f20278ae4
generate_fsid: false
cephx: true
monitor_interface: eth2
public_network: 192.168.12.0/24
cluster_network: 192.168.12.0/24
osd_objectstore: bluestore
```

group_vars/mon.yml

```yml
monitor_secret: AQAjn8tUwBpnCRAAU8X0S5f+U8gfBvnbUkDPyg==
admin_secret: AQAjn8tUwBpnCRAAU8X0Syf+U8gfBvnbUkDPyg==
```

group_vars/osd.yml

```yml
osd_scenario: collocated
```
