### ISSUE TITLE
ceph-defaults role is not deleting unused sockets when more then one socket per daemon type exists

### ISSUE THREAD

**Issue by artur-fijalkowski** [ceph/ceph-ansible#3065]
**Bug Report**

What happened:

Following task [source](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/tasks/check_socket_non_container.yml#L30):

```
# https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-defaults/tasks/check_socket_non_container.yml#L30

- name: check for a ceph osd socket
  shell: |
    stat --printf=%n {{ rbd_client_admin_socket_path }}/{{ cluster }}-osd*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket_stat
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
```

Is not properly handling multiple sockets matching same pattern. This is caused by the fact that stat with formatting used in shell module returns all filenames concatenated in single string (without any separator).

What you expected to happen:

Proper approach should be something like below:

```
- name: check for a ceph osd socket
  shell: |
    stat --printf="%n\n" {{ rbd_client_admin_socket_path }}/{{ cluster }}-osd*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket_stat
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
```

The next 2 tasks should then be looped against `osd_socket_stat.stdout_lines` instead of direct usage of `osd_socket_stat.stdout`. Also I do not understand why `stat` command with shell module is used instead of using find with command module, which will improve security (no shell escaping possible!). Example task would look like:

```
- name: check for a ceph osd socket
  command: |
    find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-osd*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket_stat
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
```

**This of course applies to ALL daemon types, not only OSDs.**
