### ISSUE TITLE
OSD auto discovery and md devices

### ISSUE THREAD

**Issue by tssvl** [ceph/ceph-ansible#3123]
Hello.
My ceph deployment fails. The reason is that I have software raid 1 for OS partitions and I have also osd auto discovery enabled.

`
["Error: Partition(s) on /dev/md127 are being used."]
`

 Is there any way to ignore md devices and use "osd_auto_discovery: true" option?

`
Thursday 13 September 2018  17:48:47 +0300 (0:00:00.061)       0:02:11.673 **** 
ok: [ceph-backup-1] => (item=/dev/sde)
ok: [ceph-backup-2] => (item=/dev/sde)
ok: [ceph-backup-3] => (item=/dev/sdd)
ok: [ceph-backup-1] => (item=/dev/sdf)
ok: [ceph-backup-3] => (item=/dev/sde)
ok: [ceph-backup-2] => (item=/dev/sdf)
ok: [ceph-backup-1] => (item=/dev/sdg)
ok: [ceph-backup-2] => (item=/dev/sdg)
ok: [ceph-backup-3] => (item=/dev/sdf)
ok: [ceph-backup-1] => (item=/dev/sdb)
ok: [ceph-backup-1] => (item=/dev/sdc)
ok: [ceph-backup-3] => (item=/dev/sdg)
ok: [ceph-backup-2] => (item=/dev/sdb)
ok: [ceph-backup-1] => (item=/dev/sdh)
ok: [ceph-backup-2] => (item=/dev/sdc)
ok: [ceph-backup-3] => (item=/dev/sdb)
ok: [ceph-backup-1] => (item=/dev/md126)
ok: [ceph-backup-2] => (item=/dev/sdh)
ok: [ceph-backup-3] => (item=/dev/sdc)
ok: [ceph-backup-3] => (item=/dev/md126)
ok: [ceph-backup-2] => (item=/dev/md126)
ok: [ceph-backup-1] => (item=/dev/md125)
ok: [ceph-backup-3] => (item=/dev/md125)
ok: [ceph-backup-1] => (item=/dev/md127)
ok: [ceph-backup-2] => (item=/dev/md125)
ok: [ceph-backup-3] => (item=/dev/md127)
ok: [ceph-backup-2] => (item=/dev/md127)
` 

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Ansible version (e.g. `ansible-playbook --version`): 2.4.0.0
* ceph-ansible version (e.g. `git head or tag or stable branch`): 3.1 stable

**Comment by tssvl** [comment]
What do you think can we just add ` - "'md' not in item.key"` to solve this problem?
In this task:
```
- name: set_fact devices generate device list when osd_auto_discovery
  set_fact:
    devices: "{{ devices | default([]) + [ item.key | regex_replace('^', '/dev/') ] }}"
  with_dict: "{{ ansible_devices }}"
  when:
    - osd_auto_discovery
    - ansible_devices is defined
    - item.value.removable == "0"
    - item.value.sectors != "0"
    - item.value.partitions|count == 0
    - item.value.holders|count == 0
    - "'dm-' not in item.key"
```
My lsblk output for better understanding of problem. (OS disk).

```
NAME      MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda         8:0    0 136,8G  0 disk  
├─sda1      8:1    0     8G  0 part  
│ └─md126   9:126  0     8G  0 raid1 [SWAP]
├─sda2      8:2    0     2G  0 part  
│ └─md127   9:127  0     2G  0 raid1 /boot
└─sda3      8:3    0 126,7G  0 part  
  └─md125   9:125  0 126,7G  0 raid1 /
```
