### ISSUE TITLE
Missing ceph.conf error with "devices" list based LVM OSD setup

### ISSUE THREAD

**Issue by bencherian** [ceph/ceph-ansible#3363]
**Bug Report**

What happened:
Error during task : "ceph-config run 'ceph-volume lvm batch --report' to see how many osds are to be created"
Error is: "RuntimeError: No valid ceph configuration file was loaded"
What you expected to happen:
For the playbook to figure out that "/dev/sd<x>" represent disks which should be allocated as OSDs and for /dev/md126 to be an SSD which should be used for block.db LVs.

How to reproduce it (minimal and precise):
Inventory:
```ini
[mons]
cis01
[osds]
cis01 osd_crush_location="{'root': 'default', 'rack': '3', 'host': 'cis01'}"
[clients]
cis01
[mgrs]
cis01
```
all.yml
```yml
---
dummy:
ntp_service_enabled: False # This is preconfigured
ceph_origin: distro # Using preconfigured local mirror of Ceph repo
public_network: 172.x.x.x/nn # exact IP redacted
cluster_network: 172.y.x.x/nn # exact IP redacted
ceph_conf_overrides: {"global": {"mon_allow_pool_delete": True}}
```
clients.yml:
```yml
dummy:
user_config: true
pools: []
keys:
  - {name: client.usera, caps: { mon: "allow rw", osd: "allow rw" }, mode: "0640"}
  - {name: client.userb, caps: { mon: "allow r", osd: "allow rw" }, mode: "0640"}
```
mons.yml
```yml
---
dummy:
create_crush_tree: true
```
osds.yml
```yml
---
dummy:
devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/sdh
  - /dev/sdi
  - /dev/sdj
  - /dev/md126
osd_scenario: lvm
crush_device_class: hdd
```

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
* Kernel (e.g. `uname -a`): Linux cis01 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): N/A
* Ansible version (e.g. `ansible-playbook --version`):

* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.2
* anbsible version:
ansible-playbook 2.6.8
  config file = /home/<<username>>/ceph-ansible/ansible.cfg
  configured module search path = [u'/home/<<username>>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

* Ceph version (e.g. `ceph -v`): ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)
