### ISSUE TITLE
ceph_key says "Failed to find some of the initial entities"

### ISSUE THREAD

**Issue by dmick** [ceph/ceph-ansible#3461]
If ceph_keys.py fails in "lookup_ceph_initial_entities", its error message is "Failed to find some of the initial entities". That's not useful to the user. Show which ones (and what an "initial entity" is).

**Comment by barbudone** [comment]
this issue is still present.

**Comment by guits** [comment]
@barbudone this is definitely missing information, share more details about your setup.

**Comment by m3nu** [comment]
I'm getting this as well. Was testing it on Google Cloud/CentOS 7. My config is minimal:

all.yml:
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: luminous
ceph_repository_type: cdn
monitor_interface: eth0
```

osds.yml
```
osd_scenario: collocated
osd_objectstore: bluestore
osd_auto_discovery: true
```

/etc/ceph/ceph.conf
```
# Please do not change this file directly since it is managed by Ansible and will be overwritten

[global]


mon initial members = mon1
osd pool default crush rule = -1

fsid = 18ffe2ac-0c5b-419f-bf1b-457f1eabd783

mon host = 10.142.0.7
public network = 0.0.0.0/0
cluster network = 0.0.0.0/0
```

sudo ceph -n mon. -k /var/lib/ceph/mon/ceph-mon1/keyring --cluster ceph status
```
  cluster:
    id:     18ffe2ac-0c5b-419f-bf1b-457f1eabd783
    health: HEALTH_OK

  services:
    mon: 1 daemons, quorum mon1
    mgr: no daemons active
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0B
    usage:   0B used, 0B / 0B avail
    pgs:
```

sudo ceph -n mon. -k /var/lib/ceph/mon/ceph-mon1/keyring --cluster ceph auth list
`no installed auth entries!`
