### ISSUE TITLE
nfs-ganesha unsigned repository

### ISSUE THREAD

**Issue by Bruceforce** [ceph/ceph-ansible#3520]
**Bug Report**

What happened:
Playbook stops, because nfs-ganesha repository is unsigend

What you expected to happen:
nfs-ganesha repository should be signed or the default value for `nfs_ganesha_stable_deb_repo`: should be
```
nfs_ganesha_stable_deb_repo: "[trusted=yes] {{ ceph_mirror }}/nfs-ganesha/deb-{{ nfs_ganesha_stable_branch }}/{{ ceph_stable_release }}"
```
How to reproduce it (minimal and precise):

- Just run the playbook with default site.yaml file and with nfs-ganesha enabled

Share your group_vars files, inventory
group_vars/all
```
ceph_origin: repository
ceph_repository: community
ceph_stable_release: mimic
public_network: 192.168.90.0/24
cluster_network: 192.168.90.0/24
monitor_interface: eth1
lvm_volumes:
  - data: /dev/sdb
  - data: /dev/sdc
osd_scenario: lvm
nfs_ganesha_stable_branch: V2.7-stable
nfs_file_gw: true
nfs_obj_gw: false
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 1804 (Vagrant box generic/ubuntu1804)
* Kernel (e.g. `uname -a`): Linux master 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.6.11
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-3.2 (commit 4e94d11aa738a0f5de3e84dc70d534fbe9c34c2f)
* Ceph version (e.g. `ceph -v`): ceph version 13.2.4-88-g30fcb44 (30fcb440bcf4f65ce0ca5ef7d9c4f3a6cc9342bb) mimic (stable)
