### ISSUE TITLE
there are no container docs

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#3531]
There are no guides on how to deploy containerized Ceph, grepping through the current docs shows just a couple of docker variables being referenced.

**Comment by gregoryo2014** [comment]
https://www.youtube.com/watch?v=DQYZU1VsqXc is a walkthrough using docker, and I think that's what I used to get me started. This worked for me:

groups_vars/all.yml:
```
monitor_interface: my_interface
docker: true
containerized_deployment: true
```
group_vars/osd.yml:
```
osd_scenario: lvm
lvm_volumes:
  - data: /dev/sdc
    db: /dev/sda1
...
```
```
cp site-docker.yml.sample docker.yml
ansible-playbook docker.yml
```

It's not doco I know, but I hope it is of some help.
