### ISSUE TITLE
Check mode fails when pulling docker images

### ISSUE THREAD

**Issue by devster31** [ceph/ceph-ansible#3608]
**Bug Report**

What happened: running `site-docker.yml` in check mode fails

What you expected to happen: running `site-docker.yml` succeeds with a lot of skipped items

How to reproduce it: `ansible-playbook -D -i ../inventories/local.yml site-docker.yml -C --skip-tags with_pkg`

Output (with `unixy` stdout_callback):
```
pulling docker.io/ceph/daemon:latest image...
  sagittarius failed | msg: The conditional check 'docker_image.rc == 0' failed. The error was: error while evaluating conditional (docker_image.rc == 0): 'dict object' has no attribute 'rc'
  Ran out of hosts!
```
when trying to pull the image.
A couple of options I see are either adding `check_mode: no` in the task as below:
```yaml
- name: "pulling {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }} image"
  command: "{{ timeout_command }} {{ container_binary }} pull {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  changed_when: false
  register: docker_image
  until: docker_image.rc == 0
  retries: "{{ docker_pull_retry }}"
  delay: 10
  check_mode: no
  when:
    - (ceph_docker_dev_image is undefined or not ceph_docker_dev_image)
```
and/or introducing a check to verify the image already exists:
```
$ docker images -q ceph/daemon:latest
$ docker inspect docker.io/ceph/daemon:latest
```

Share your group_vars files, inventory
**local.yml**
```yaml
local:
  hosts:
    sagittarius:
      ansible_host: <IP>
      ansible_python_interpreter: /usr/bin/python3
  children:
    ceph:
      children:
        mons:
          hosts:
            sagittarius
        osds:
          hosts:
            sagittarius
        ...
    machines:
        servers:
          hosts:
            sagittarius
```
**group_vars/all.yml** - only the relevant bit
```yaml
docker: true
containerized_deployment: true
```

**Environment**:
* OS: MacOS 10.12 is the workstation, Ubuntu 18.04.2 LTS is the target machine
* Kernel (e.g. `uname -a`): `Linux sagittarius 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`): `Docker version 18.09.2, build 6247962` from official repo
* Ansible version (e.g. `ansible-playbook --version`):
```
ansible-playbook 2.7.6
  config file = /Users/devster/code/infrastructure/ansible/ceph-ansible/ansible.cfg
  configured module search path = ['/Users/devster/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/devster/code/infrastructure/ansible/env/lib/python3.7/site-packages/ansible
  executable location = /Users/devster/code/infrastructure/ansible/env/bin/ansible-playbook
  python version = 3.7.2 (default, Feb 12 2019, 08:16:11) [Clang 9.0.0 (clang-900.0.39.2)]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`): https://github.com/ceph/ceph-ansible/commit/d4e31b90a67a76d21d98cd956fc2809b980b8126
* Ceph version (e.g. `ceph -v`): N/A
