### ISSUE TITLE
ceph-volume module does not handle its own exit in check mode

### ISSUE THREAD

**Issue by devster31** [ceph/ceph-ansible#3610]
**Bug Report**

#### What happened ####
when running a `site-docker` playbook in check mode the following error pops up
```
run 'ceph-volume lvm batch --report' to see how many osds are to be created...
  sagittarius failed | msg: New-style module did not handle its own exit
```
#### What you expected to happen ####
completion of the playbook in check mode

How to reproduce it (minimal and precise):
`ansible-playbook -D -i ../inventories/local.yml site-docker.yml -C`
this seems related to `library/ceph_volume.py` and more precisely to
https://github.com/ceph/ceph-ansible/blob/d4e31b90a67a76d21d98cd956fc2809b980b8126/library/ceph_volume.py#L527-L528
which doesn't use `module.exit_json()`.
```
    if module.check_mode:
        result['rc'] = 0
        module.exit_json(**result)
```
using the snippet above, succeeds. It might, however, be worth adding `check_mode: no` to this task: https://github.com/ceph/ceph-ansible/blob/719a25b571dbd8ff99cbfb273afb8997965fb0e6/roles/ceph-config/tasks/main.yml#L22-L39

**../inventory/local.yml**

```yaml
local:
  hosts:
    sagittarius:
      ansible_host: <IP>
      ansible_python_interpreter: /usr/bin/python3
  children:
    ceph:
      children:
        mons:
          hosts:
            sagittarius
        osds:
          hosts:
            sagittarius
        ...
    machines:
      children:
        servers:
          hosts:
            sagittarius
```

**group_vars/all.yml** - only the relevant bit

```yaml
docker: true
containerized_deployment: true
```

**Environment**:

* OS: MacOS 10.12 is the workstation, Ubuntu 18.04.2 LTS is the target machine
* Kernel (e.g. `uname -a`): `Linux sagittarius 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`): `Docker version 18.09.2, build 6247962` from official repo
* Ansible version (e.g. `ansible-playbook --version`):

```
ansible-playbook 2.7.6
  config file = /Users/devster/code/infrastructure/ansible/ceph-ansible/ansible.cfg
  configured module search path = ['/Users/devster/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/devster/code/infrastructure/ansible/env/lib/python3.7/site-packages/ansible
  executable location = /Users/devster/code/infrastructure/ansible/env/bin/ansible-playbook
  python version = 3.7.2 (default, Feb 12 2019, 08:16:11) [Clang 9.0.0 (clang-900.0.39.2)]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`): [d4e31b9](https://github.com/ceph/ceph-ansible/commit/d4e31b90a67a76d21d98cd956fc2809b980b8126)
* Ceph version (e.g. `ceph -v`): N/A
