### ISSUE TITLE
containerized deployment: possibly missing lvmetad on host to allow mounting of devices in containers

### ISSUE THREAD

**Issue by devster31** [ceph/ceph-ansible#3728]
**Bug Report**

What happened: upon rebooting the server the `systemd` services that spin up ceph containers started but was unable to mount `/dev/ceph-<uuid>` as this was missing in the host.

What you expected to happen: reboot spins up ceph containers

How to reproduce it (minimal and precise): unfortunately I don't have spare machines to test with, but I believe the absence of `lvmetad` on the host machine is the root cause.

Share your group_vars files, inventory
```yaml
--- all.yml
osd_objectstore: bluestore
radosgw_civetweb_port: 7480
ceph_conf_overrides:
  mon:
    'mon allow pool delete': 'true'
ceph_docker_image_tag: latest-nautilus
containerized_deployment: true
containerized_deployment_with_kv: false # does not seem to work
mon_containerized_default_ceph_conf_with_kv: false # does not seem to work
--- mgr.yml
ceph_mgr_modules:
  - status
  - balancer
  - dashboard
  - prometheus
  - restful
  - iostat
ceph_mgr_overrides:
  - "set mgr mgr/dashboard/server_addr '::'"
  - "set mgr mgr/dashboard/server_port 8088"
  - "set mgr mgr/dashboard/ssl false"
--- mons.yml
ceph_mon_docker_memory_limit: "{{ (ansible_memtotal_mb / 4) | round | int }}m"
--- osds.yml
devices:
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_R5G2DRGV
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_R6GWWBXY
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLG6K3BY
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLHMNLBY
osd_scenario: lvm
```
**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu LTS 18.04.2
* Kernel (e.g. `uname -a`): Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`):
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
* Ansible version (e.g. `ansible-playbook --version`):
```
ansible-playbook 2.7.9
  config file = /Users/devster/code/infrastructure/ansible/ansible.cfg
  configured module search path = ['/Users/devster/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/devster/code/infrastructure/ansible/env/lib/python3.7/site-packages/ansible
  executable location = /Users/devster/code/infrastructure/ansible/env/bin/ansible-playbook
  python version = 3.7.2 (default, Feb 12 2019, 08:16:11) [Clang 9.0.0 (clang-900.0.39.2)]
```
* ceph-ansible version (e.g. `git head or tag or stable branch`): `stable-3.2` but I forgot to change the variable for the docker image tag and it was upgraded to nautilus by accident about a week ago.
* Ceph version (e.g. `ceph -v`): `ceph version 14.1.1 (ae1b3cf8e2e29118c0682f0895e3f48a79895cbc) nautilus (rc)`
