### ISSUE TITLE
add_osd.yaml missing keys problem

### ISSUE THREAD

**Issue by mrpity** [ceph/ceph-ansible#3736]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when using infrastructure-playbooks/add_osd.yaml playbook.

**Describe the solution you'd like**
I think we should add such block in add_osd.yaml:
```
- hosts:
  - mons

  tasks:
    - import_role:
        name: ceph-fetch-keys
```
It should help to avoid problem with missing keys in *fetch* directory
For now I am using such approach like workaround.
