### ISSUE TITLE
add Ansible 2.8 testing

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-ansible#3765]
Ansible 2.7 has some usability issues with RHEL 8. As far as I know, the RH Ansible Engine 2.7 product will not be available for RHEL 8 at all.

This means that we will need to support Ansible 2.8 in ceph-ansible if we want to support RHEL 8. Currently ceph-ansible fails on this version:

```yaml
- name: fail on unsupported ansible version
  fail:
    msg: "Ansible version must be 2.7!"
  when:
    - ansible_version.major|int != 2
    - ansible_version.minor|int != 7
```

There are no [release candidates](https://pypi.org/project/ansible/#history) yet, but [the roadmap schedule](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html) indicates the Ansible team will make release candidates available in the next couple of weeks.

Would you please test with Ansible 2.8 ?
