### ISSUE TITLE
nfs-ganesha-stable missing for ceph nautilus in ubuntu bionic

### ISSUE THREAD

**Issue by Bruceforce** [ceph/ceph-ansible#3789]
**Bug Report**
I tried the new stable-4.0 in a clean environment with nfs-ganesha but it failed because http://download.ceph.com/nfs-ganesha/deb-V2.7-stable/nautilus does not exist. I checke that https://shaman.ceph.com/repos/nfs-ganesha-stable/V2.7-stable/ is already there for nautilus and https://github.com/ceph/ceph-build/blob/master/nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml also was updated, so I assume this has to be pushed somehow to http://download.ceph.com/nfs-ganesha/deb-V2.7-stable/nautilus?

What happened:
Playbook fails because it cannot find http://download.ceph.com/nfs-ganesha/deb-V2.7-stable/nautilus

What you expected to happen:
http://download.ceph.com/nfs-ganesha/deb-V2.7-stable/nautilus should exist

How to reproduce it (minimal and precise):

- execute `site.yml` with nfs-ganesha enabled

Share your group_vars files, inventory
```
  ceph_origin: repository
  ceph_repository: community
  ceph_stable_release: nautilus
  public_network: 192.168.90.0/24
  cluster_network: 192.168.90.0/24
  radosgw_address: 192.168.90.2
  monitor_address_block: 192.168.90.0/24
  lvm_volumes:
  - data: /dev/sdc
  - data: /dev/sdd
  osd_scenario: lvm
  ceph_nfs_rgw_squash: No_Root_Squash
  ceph_nfs_ceph_squash: No_Root_Squash
  nfs_file_gw: true
  nfs_obj_gw: true
  nfs_ganesha_stable_branch: V2.7-stable
```

**Environment**:
* OS (e.g. from /etc/os-release): 18.04.2 LTS (Bionic Beaver)
* Kernel (e.g. `uname -a`): Linux node-10 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.7.9
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)

I bet this is still the wrong place to open this issue, but I'm never sure if to open it in ceph-build, the ceph-issue tracker or in any other place. I'm sorry for this.
