### ISSUE TITLE
[stable-4.0] generating ceph.conf fails

### ISSUE THREAD

**Issue by devster31** [ceph/ceph-ansible#3799]
**Bug Report**

#### What happened
```
TASK [ceph-config : generate ceph.conf configuration file] ******************************************************************************************************
fatal: [sagittarius]: FAILED! =>
  msg: the inline if-expression on line 1 evaluated to false and no else section was defined.
```
How to reproduce it (minimal and precise):
`stable-4.0` branch, upgrading from `stable-3.2` with the below variables
```yaml
---
# forcing them as it kept changing from debian and container
bootstrap_dirs_owner: "167"
bootstrap_dirs_group: "167"
fsid: <fsid>
generate_fsid: false
monitor_interface: eth0
cephfs_pools:
# about to change to autoscaler
 - { name: "{{ cephfs_data }}", pgs: "64", size: "2", min_size: "{{ osd_pool_default_min_size }}" }
 - { name: "{{ cephfs_metadata }}", pgs: "64", size: "4", min_size: "{{ osd_pool_default_min_size }}" }
public_network: "10.0.0.0/24"
osd_objectstore: bluestore
radosgw_frontend_type: beast
radosgw_civetweb_port: 7480
radosgw_frontend_port: 8088
radosgw_interface: eth0
common_single_host_mode: true
ceph_conf_overrides: {}
os_tuning_params:
  - { name: fs.file-max, value: 26234859 }
ceph_docker_image_tag: latest-nautilus
containerized_deployment: true
---
ceph_mgr_modules:
  - status
  - balancer
  - dashboard
  - prometheus
  - restful
  - iostat
---
ceph_mon_docker_memory_limit: "{{ (ansible_memtotal_mb / 4) | round | int }}m"
---
dummy:
nfs_file_gw: true
nfs_obj_gw: false
ceph_nfs_disable_caching: true
---
devices:
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_R5G2DRGV
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_R6GWWBXY
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLG6K3BY
  - /dev/disk/by-id/ata-HGST_HUH728080ALE600_VLHMNLBY
osd_auto_discovery: false
osd_scenario: lvm
```
**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):
