### ISSUE TITLE
lvm_volumes validation failed with inventory var

### ISSUE THREAD

**Issue by dcasier** [ceph/ceph-ansible#4007]
**Bug Report**

Failed, if lvm_volume is defined in a global variable :

```
Validation failed for variable: lvm_volumes
Reason: expected a list but got AnsibleUnicode
```

Example :
```
all:
  children:
    osds:
      hosts:
        cephosdnode1:
          lvm_volumes: '{{ global_lvm }}'
        cephosdnode2:
          lvm_volumes: '{{ global_lvm }}'
    vars:
      global_lvm:
          - data: block1-lv
            data_vg: block1
            db: nvme1-db1
            db_vg: nvme1
            wal: nvme1-wal1
            wal_vg: nvme1
          - data: block2-lv
            data_vg: block2
            db: nvme1-db2
            db_vg: nvme1
            wal: nvme1-wal2
            wal_vg: nvme1
```

The behavior is the same if the file is ini or yaml format

I think the issue related to ansible, but if you have any ideas

**Environment**:
* ceph-ansible-3.2.0-1.el7cp.noarch
* ansible-2.6.12-1.el7ae.noarch
