### ISSUE TITLE
Create crush rule version mimic 

### ISSUE THREAD

**Issue by ushacow** [ceph/ceph-ansible#4012]
Hi!

Is it possible to create crush rule with using storage class?

Where should I put storage class parameter in this var?
```
crush_rule_hdd:
  name: HDD
  root: test
  type: rack
  default: true
```
