### ISSUE TITLE
ceph_dashboard role incorrectly setting grafana utl

### ISSUE THREAD

**Issue by pcuzner** [ceph/ceph-ansible#4085]
After installation the mgr/dashboard grafana-api-url was set to a mon host not the name of the grafana-server host.
dashboards.yml contains
---
grafana_server_group_name: grafana-server

and the inventory contains
```yaml
all:
  children:
    grafana-server:
      hosts:
        nautilus-metrics: null
```
Grafana and prometheus deploy correctly but the grafana url applied to mgr/dashboard is invalid

Is this syntax valid?
```yaml
- name: set grafana url to grafana instance
  set_fact:
    dashboard_url: "{{ groups[grafana_server_group_name][0] }}"
  when: "{{  groups.grafana_server_group_name is defined and groups[grafana_server_group_name] | length > 0 }}"
```

Does groups.grafana_server_group_name actually resolve as intended?

ref: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-dashboard/tasks/configure_dashboard.yml#L96
