### ISSUE TITLE
TASK [ceph-facts : set grafana_server_addr fact - ipv4] failed when more than one public_network exists

### ISSUE THREAD

**Issue by beomseok-park** [ceph/ceph-ansible#4170]
**Bug Report**

What happened:
```
TASK [ceph-facts : set grafana_server_addr fact - ipv4] 
Friday 28 June 2019  14:55:24 +0900 (0:00:00.797)       0:01:32.894
fatal: [mon01]: FAILED! =>
  msg: 'ipaddr: unknown filter type: 192.168.1.0/24,192.168.2.0/24'
```

How to reproduce it (minimal and precise):
**all.yml**
```
public_network: 192.168.1.0/24,192.168.2.0/24
dashboard_enabled: true
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.6
* Ansible version (e.g. `ansible-playbook --version`): 2.8.1
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.1 nautilus

**Comment by dsavineau** [comment]
we currently don't support multiple public networks in ceph-ansible

**Comment by radut** [comment]
I also noticed if I run twice the playbooks, the second time it will pick up the docker interface ip address. 
my config is : 
```
public_network: 192.168.16.0/24
```

problem was fixed for me by changing this 
```
- name: set grafana_server_addr fact - ipv4
  set_fact:
#    grafana_server_addr: "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'] | ipaddr(public_network) | first }}"
    grafana_server_addr: "{{  hostvars[groups[grafana_server_group_name][0]]['ansible_default_ipv4']['address'] }}"
```
