### ISSUE TITLE
TASK 'wait for grafana to start' fails

### ISSUE THREAD

**Issue by SalsaBr** [ceph/ceph-ansible#4288]
ceph-grafana is not starting and ceph-ansible fails.

Tried to run ceph-ansible in a Ubuntu and a CentOS machine, and both had the same results.

```console
TASK [ceph-grafana : wait for grafana to start] *******************************************************************************************************************************************************************
task path: /home/salsa/repo/ceph-ansible/roles/ceph-grafana/tasks/configure_grafana.yml:94
Tuesday 30 July 2019  13:55:30 -0300 (0:00:01.008)       0:06:58.355 **********
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/utilities/logic/wait_for.py
Pipelining is enabled.
<ceph-mon-01> ESTABLISH SSH CONNECTION FOR USER: None
<ceph-mon-01> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/root/.ansible/cp/%h-%r-%p ceph-mon-01 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-omyipiutbdwqxilzorxszkcxjuorwerf ; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<ceph-mon-01> (1, '\n{"msg": "Timeout when waiting for 127.0.0.1:3000", "failed": true, "exception": "WARNING: The below traceback may *not* be related to the actual failure.\\n  File \\"/tmp/ansible_wait_for_payload_9tLaPX/__main__.py\\", line 599, in main\\n    s = _create_connection(host, port, min(connect_timeout, alt_connect_timeout))\\n  File \\"/tmp/ansible_wait_for_payload_9tLaPX/__main__.py\\", line 456, in _create_connection\\n    connect_socket = socket.create_connection((host, port), connect_timeout)\\n  File \\"/usr/lib64/python2.7/socket.py\\", line 571, in create_connection\\n    raise err\\n", "elapsed": 300, "invocation": {"module_args": {"active_connection_states": ["ESTABLISHED", "FIN_WAIT1", "FIN_WAIT2", "SYN_RECV", "SYN_SENT", "TIME_WAIT"], "state": "started", "port": 3000, "delay": 0, "msg": null, "host": "127.0.0.1", "sleep": 1, "timeout": 300, "exclude_hosts": null, "search_regex": null, "path": null, "connect_timeout": 5}}}\n', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 5832\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
<ceph-mon-01> Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017^M
debug1: Reading configuration data /etc/ssh/ssh_config^M
debug1: /etc/ssh/ssh_config line 19: Applying options for *^M
debug1: auto-mux: Trying existing master^M
debug2: fd 3 setting O_NONBLOCK^M
debug2: mux_client_hello_exchange: master version 4^M
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote^M
debug3: mux_client_request_session: entering^M
debug3: mux_client_request_alive: entering^M
debug3: mux_client_request_alive: done pid = 5832^M
debug3: mux_client_request_session: session request sent^M
debug1: mux_client_request_session: master session id: 2^M
debug3: mux_client_read_packet: read header failed: Broken pipe^M
debug2: Received exit status from master 1
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_wait_for_payload_9tLaPX/__main__.py", line 599, in main
    s = _create_connection(host, port, min(connect_timeout, alt_connect_timeout))
  File "/tmp/ansible_wait_for_payload_9tLaPX/__main__.py", line 456, in _create_connection
    connect_socket = socket.create_connection((host, port), connect_timeout)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
fatal: [ceph-mon-01]: FAILED! => changed=false
  elapsed: 300
  invocation:
    module_args:
      active_connection_states:
      - ESTABLISHED
      - FIN_WAIT1
      - FIN_WAIT2
      - SYN_RECV
      - SYN_SENT
      - TIME_WAIT
      connect_timeout: 5
      delay: 0
      exclude_hosts: null
      host: 127.0.0.1
      msg: null
      path: null
      port: 3000
      search_regex: null
      sleep: 1
      state: started
      timeout: 300
  msg: Timeout when waiting for 127.0.0.1:3000

RUNNING HANDLER [ceph-prometheus : service handler] ***************************************************************************************************************************************************************
task path: /home/salsa/repo/ceph-ansible/roles/ceph-prometheus/handlers/main.yml:2
Tuesday 30 July 2019  14:00:31 -0300 (0:05:01.207)       0:11:59.563 **********

PLAY RECAP ********************************************************************************************************************************************************************************************************
ceph-mon-01                : ok=297  changed=9    unreachable=0    failed=1    skipped=397  rescued=0    ignored=0
ceph-mon-02                : ok=130  changed=3    unreachable=0    failed=0    skipped=236  rescued=0    ignored=0
ceph-mon-03                : ok=131  changed=3    unreachable=0    failed=0    skipped=235  rescued=0    ignored=0
ceph-osd-01                : ok=251  changed=8    unreachable=0    failed=0    skipped=293  rescued=0    ignored=0
ceph-osd-02                : ok=156  changed=4    unreachable=0    failed=0    skipped=228  rescued=0    ignored=0
ceph-osd-03                : ok=156  changed=4    unreachable=0    failed=0    skipped=228  rescued=0    ignored=0
```

```yaml
group_vars/all.yml:
dummy:
ceph_release_num:
  nautilus: 14
fetch_directory: fetch/
cluster: alpha_ceph
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
nfs_group_name: nfss
rbdmirror_group_name: rbdmirrors
client_group_name: clients
iscsi_gw_group_name: iscsigws
mgr_group_name: mgrs
configure_firewall: True
ceph_conf_local: true
redhat_package_dependencies: []
ntp_service_enabled: true
ntp_daemon_type: timesyncd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
ceph_stable_redhat_distro: el7
nfs_ganesha_flavor: "ceph_master"
generate_fsid: true
ceph_conf_key_directory: /etc/ceph
ceph_keyring_permissions: '0600'
monitor_interface: ens32
public_network: 10.17.6.64/26
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
devices:
  - '/dev/sdb/'
  - '/dev/sdc/'
radosgw_interface: ens32
docker: false
openstack_config: false
dashboard_enabled: true
dashboard_protocol: http
dashboard_admin_user: admin
dashboard_admin_password: admin
node_exporter_container_image: prom/node-exporter:latest
grafana_admin_user: admin
grafana_admin_password: admin
grafana_container_image: "grafana/grafana:latest"
grafana_container_cpu_period: 100000
grafana_container_cpu_cores: 2
grafana_container_memory: 4
grafana_plugins:
  - vonage-status-panel
  - grafana-piechart-panel
prometheus_container_image: prom/prometheus:latest
prometheus_container_cpu_period: 100000
prometheus_container_cpu_cores: 2
prometheus_container_memory: 4
prometheus_data_dir: /var/lib/prometheus
prometheus_conf_dir: /etc/prometheus
```

**Environment**:
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
Linux Alpha 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
No docker
ansible-playbook 2.8.2
Using HEAD -> master
CEPH nautilus
