### ISSUE TITLE
add-osd playbook fails on TASK [ceph-osd : copy ceph key(s) if needed]

### ISSUE THREAD

**Issue by Scooty5** [ceph/ceph-ansible#4387]
Hello,

On containerized deployment, add-osd playbook fails with error:

```
TASK [ceph-osd : copy ceph key(s) if needed] *********************************************************************************************************************************************************************
Saturday 24 August 2019  17:31:43 +0000 (0:00:00.429)       0:01:34.956 *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [10.0.0.47] (item={u'name': u'/var/lib/ceph/bootstrap-osd/ceph.keyring', u'copy_key': True}) => changed=false
  ansible_loop_var: item
  item:
    copy_key: true
    name: /var/lib/ceph/bootstrap-osd/ceph.keyring
  msg: |-
    Could not find or access 'fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring'
    Searched in:
            /root/ceph-ansible/roles/ceph-osd/files/fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring
            /root/ceph-ansible/roles/ceph-osd/fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring
            /root/ceph-ansible/roles/ceph-osd/tasks/files/fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring
            /root/ceph-ansible/roles/ceph-osd/tasks/fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring
            /root/ceph-ansible/infrastructure-playbooks/files/fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring
            /root/ceph-ansible/infrastructure-playbooks/fetch//9dbfe6f4-e938-4b2a-8ac2-15c12f64502b//var/lib/ceph/bootstrap-osd/ceph.keyring on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option
skipping: [10.0.0.47] => (item={u'name': u'/etc/ceph/ceph.client.admin.keyring', u'copy_key': False})
```

I'm not sure why ansible tries to copy this keyring, it already exists on OSD node.
When i delete this single task from role, new OSD disk is deployed successfully.

all.yml:
```
---
ceph_conf_local: true
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
monitor_interface: ens3
public_network: "10.0.0.0/24"
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
osd_objectstore: bluestore
radosgw_interface: ens4
ceph_conf_overrides:
  global:
    osd_pool_default_size: 2
containerized_deployment: true
openstack_config: true
dashboard_enabled: True
```

inventory(as it's described in add-osd.yml, i've deleted all other osd nodes):
```
all:
  children:
    mons:
      hosts:
        10.0.0.49:
    rgws:
      hosts:
        10.0.0.49:
    grafana-server:
      hosts:
        10.0.0.49:
    osds:
      hosts:
        10.0.0.47:
          lvm_volumes:
            - data: data-1
              data_vg: hdd-1
              wal: wal-1
              wal_vg: ssd-1
              db: db-1
              db_vg: ssd-1
              crush_device_class: hdd
            - data: data-2
              data_vg: hdd-2
              wal: wal-2
              wal_vg: ssd-1
              db: db-2
              db_vg: ssd-1
              crush_device_class: hdd
            - data: data-3
              data_vg: hdd-3
              wal: wal-3
              wal_vg: ssd-1
              db: db-3
              db_vg: ssd-1
              crush_device_class: hdd

  vars:
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /root/dev.key
```

**Environment**:
* OS: Ubuntu 18.04
* Kernel: 4.15
* Docker version if applicable : 18.09.7
* Ansible version: 2.8.4
* ceph-ansible version: stable-4.0
* Ceph version: 14.2.2
