### ISSUE TITLE
shrink-osd.yml playbook try to connect to osd host via hostname instead of IP.

### ISSUE THREAD

**Issue by Scooty5** [ceph/ceph-ansible#4388]
Hello,

shrink-osd.yml playbook has tasks which should find OSD host, where osd process is running:

```
    - name: find the host(s) where the osd(s) is/are running on
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} osd find {{ item }}"
      with_items: "{{ osd_to_kill.split(',') }}"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: find_osd_hosts

    - name: set_fact osd_hosts
      set_fact:
        osd_hosts: "{{ osd_hosts | default([]) + [ [ (item.stdout | from_json).crush_location.host, (item.stdout | from_json).osd_fsid ] ] }}"
      with_items: "{{ find_osd_hosts.results }}"
```

It receives crush_location.host (it's OSD hostname) and then try to connect to it, but it leads to two important problems:

1. this hostname can be unresolvable, then playbook returns an error: `Data could not be sent to remote host "ceph-1". Make sure this host can be reached over ssh: ssh: Could not resolve hostname ceph-1: Temporary failure in name resolutio`
2. many people(and me) store IP addresses in inventory files and also variables for group [all] like `ansible_user: ubuntu`. Even if ceph OSD hostname is resolvable and can be reached from ansible host, ansible won't take variables like `ansible_user` from inventory file. This may lead to errors like `Please login as the user "ubuntu" rather than the user "root".`

**Proposal: Playbook should connect to OSD hosts over IP addresses stored in inventory file**

**Environment**:
* OS: Ubuntu 18.04
* Kernel: 4.15
* Docker version if applicable : 18.09.7
* Ansible version: 2.8.4
* ceph-ansible version: stable-4.0
* Ceph version: 14.2.2
