### ISSUE TITLE
"copy ceph key(s) if needed" fails when local ansible username != remote username

### ISSUE THREAD

**Issue by kevincoakley** [ceph/ceph-ansible#4518]
Environment:

Running Ansible (2.8.5) on a management host as user kcoakley, accessing Ceph cluster as centos user (see hosts file excerpt below):

```
[mons]
sdsc-dev-mon-0 ansible_host=192.168.0.6 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo
sdsc-dev-mon-1 ansible_host=192.168.0.26 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo
sdsc-dev-mon-2 ansible_host=192.168.0.24 ansible_port=22 ansible_user=centos ansible_become=yes ansible_become_method=sudo
```

commit e1d06f498cbd239dbe415ffa26824eaf9116161f changed how ceph keys are copied and added the delegate_to setting to the copy function.

Without the delegate_to setting the ssh command is:

```
<192.168.0.6> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o Port=22 -
o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="centos
"' -o ConnectTimeout=60 -o ControlPath=/home/kcoakley/.ansible/cp/%h-%r-%p 192.168.0.6 '/bin/sh -c '"'"'rm -f -r /home/centos/.ansible/tmp/ansible-tmp-15700
61746.22-219962892797935/ > /dev/null 2>&1 && sleep 0'"'"''
```

With the delegate_to setting the ssh command is:

```
<ceph-mon-0> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=600s -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=60 -o ControlPath=/home/kcoakley/.ansible/cp/%h-%r-%p ceph-mon-0 '/bin/sh -c '"'"'echo ~centos && sleep 0'"'"''
```

Since the ssh command with delegate_to set doesn't include `-o 'User="centos"'` the ssh command tries to ssh to the Ceph cluster as kcoakley instead of centos and fails since the kcoakley user doesn't exist on the Ceph cluster. 

I created the following playbook as a test. It fails when I run it as is. If I remove `delegate_to: "{{ item.item.hostname }}"` it succeeds but doesn't do what you meant for it to do.

```
---
- name: copy delegate_to test
  hosts: mons
  become: true

  vars:
   mon_group_name: mons
   container_exec_cmd: ""
   cluster: ceph
   containerized_deployment: false
   ceph_keyring_permissions: 0644
   _mgr_keys:
      - name: client.admin
        hostname: ceph-mon-0
        path: /etc/ceph/ceph.client.admin.keyring
      - name: mgr.ceph-mon-0
        hostname: ceph-mon-0
        path: /var/lib/ceph/mgr/ceph-ceph-mon-0/keyring

  post_tasks:
    - name: get keys from monitors
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} auth get {{ item.name }}"
      register: _mgr_keys
      with_items: "{{ _mgr_keys }}"
      delegate_to: "{{ groups.get(mon_group_name)[0] }}"
      run_once: true

    - name: copy ceph key(s) if needed
      copy:
        dest: "{{ item.item.path }}"
        content: "{{ item.stdout + '\n' }}"
        owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
        group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
        mode: "{{ ceph_keyring_permissions }}"
      with_items: "{{ _mgr_keys.results }}"
      delegate_to: "{{ item.item.hostname }}"
      run_once: true
```

ceph-ansible now fails the first time the ceph keys are attempted to be copied.

**Comment by kevincoakley** [comment]
Some additional information, the error I am receiving is only when delegate_to is used with "{{ item.item.hostname }}" in roles/ceph-mgr/tasks/common.yml. 

Is there a reason why `delegate_to: "{{ item.item.hostname }}"` instead of something like `delegate_to: "{{ groups.get(mon_group_name)[0] }}"`?

I can work around the issue by updating "copy ceph key(s) if needed" to:

```
    - name: copy ceph key(s) if needed
      copy:
        dest: "{{ item.item.path }}"
        content: "{{ item.stdout + '\n' }}"
        owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
        group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
        mode: "{{ ceph_keyring_permissions }}"
      with_items: "{{ _mgr_keys.results }}"
      delegate_to: "{{ item.item.hostname }}"
      remote_user: "{{ ansible_user }}"
      run_once: true
      when:
        - cephx | bool
        - item.item.copy_key | bool
```

Would you accept a pull request to add `remote_user: "{{ ansible_user }}"`?
