### ISSUE TITLE
login to authenticated registry failing

### ISSUE THREAD

**Issue by pcuzner** [ceph/ceph-ansible#4636]
When using downstream authenticated registry vars, the images pulls still fail. When I looked at the playbook, the login process is in ceph-container-common, but for the dashboard this role is not included?

ceph-ansible-4.0.2-1.el8cp.noarch
group_vars/all.yml
```
---
alertmanager_container_image: registry.redhat.io/openshift4/ose-prometheus-alertmanager:4.1
ceph_conf_overrides:
  global:
    osd_crush_chooseleaf_type: 0
    osd_pool_default_size: 1
ceph_docker_image: rhceph-beta/rhceph-4-rhel8
ceph_docker_registry: registry.redhat.io
ceph_docker_registry_auth: true
ceph_docker_registry_password: <my password>
ceph_docker_registry_username: <my user>
ceph_origin: repository
ceph_repository: rhcs
ceph_repository_type: iso
ceph_rhcs_iso_path: /usr/share/ansible-runner-service/iso/RHCEPH-4.0-RHEL-8-20191007.6-x86_64-dvd.iso
ceph_rhcs_version: 4
cluster_network: 10.90.90.0/24
containerized_deployment: false
dashboard_enabled: true
grafana_container_image: registry.redhat.io/rhceph/rhceph-3-dashboard-rhel7:3
ip_version: ipv4
monitor_address_block: 10.90.90.0/24
node_exporter_container_image: registry.redhat.io/openshift4/ose-prometheus-node-exporter:v4.1
prometheus_container_image: registry.redhat.io/openshift4/ose-prometheus:4.1
public_network: 10.90.90.0/24
radosgw_address_block: 10.90.90.0/24
```
