### ISSUE TITLE
rolling-upgrade: set_fact mds_active_name: expected string or buffer

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-ansible#4673]
**Bug Report**

What happened:

rolling upgraded from mimic -> nautilus failed (**I have NO mds server configured!**):

```
TASK [set_fact mds_active_name] **************************************************************************************************************************************************************************************************************
task path: /root/ansible-playbooks/ceph-ansible-dev/rolling_update.yml:572
Friday 25 October 2019  21:42:28 +0200 (0:00:00.062)       0:12:23.672 ******** 
fatal: [ceph-mon01-dev.intern.customer-virt.eu]: FAILED! => 
  msg: 'Unexpected templating type error occurred on ({{ (_mds_active_name.stdout | from_json).filesystems[0][''mdsmap''][''info''] }}): expected string or buffer'
```

Share your group_vars files, inventory

hosts:
```
[ceph-mgmt-nodes-dev]
ceph-mon01-dev.intern
ceph-mon02-dev.intern
ceph-mon03-dev.intern

[mons:children]
ceph-mgmt-nodes-dev

[mgrs:children]
ceph-mgmt-nodes-dev

[rgws:children]
ceph-mgmt-nodes-dev

[iscsigws]
ceph-osd01-dev.intern
ceph-osd02-dev.intern
ceph-osd03-dev.intern

[osds:]
ceph-osd01-dev.intern
ceph-osd02-dev.intern 
ceph-osd03-dev.intern
```

all.yml
```
---
dummy:
configure_firewall: false 
ntp_daemon_type: ntpd
upgrade_ceph_packages: False 
ceph_origin: repository
ceph_repository: community 
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: nautilus 
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
monitor_interface: ens192 
osd_objectstore: bluestore
radosgw_interface: ens192 
ceph_conf_overrides: 
  osd:
    osd_client_watch_timeout: 15
    osd_heartbeat_grace: 20
    osd_heartbeat_interval: 5
ceph_tcmalloc_max_total_thread_cache: 134217728 
```

mgrs.yml
```
---
dummy:
ceph_mgr_modules: 
  - status
  - dashboard
  - diskprediction_cloud
  - diskprediction_local
  - prometheus
  - iostat
  - ceph-mgr
  - ceph-mgr-dashboard
  - ceph-mgr-diskprediction-local
```

mons.yml
```
---
dummy:
create_crush_tree: true 
```

**Environment:

*OS (e.g. from /etc/os-release): CentOS 7.7
*Kernel (e.g. uname -a): 3.10.0-1062.1.2.el7.x86_64
*Ansible version (e.g. ansible-playbook --version): 2.8.5
*ceph-ansible version (e.g. git head or tag or stable branch): 4.0.4

Non Containerized Installation
