### ISSUE TITLE
fail to use add-osd.yml to add osd back after swap journal hard drive

### ISSUE THREAD

**Issue by xinrist** [ceph/ceph-ansible#4730]
**Bug Report**

What happened:
1) on one ceph node - 12 osd share 2 journal hard drives. (6 osds share one same journal hard drive.)
2) Removed 6 osds on same ceph node due to a journal hard drive failure
3) swap journal hard drive. re-partition and run 
ansible-playbook -i hosts.yml  add-osd.yml
4) no errors, but 
4.1) osd docker failed to start:
```
Every 2.0s: docker logs ceph-osd-nspregrceph6-sdm                                        Tue Nov 12 14:02:51 2019

2019-11-12 14:02:50  /entrypoint.sh: static: does not generate config
/usr/lib/python2.7/site-packages/ceph_disk/main.py:5689: UserWarning:
*******************************************************************************
This tool is now deprecated in favor of ceph-volume.
It is recommended to use ceph-volume for OSD deployments. For details see:
    http://docs.ceph.com/docs/master/ceph-volume/#migrating
*******************************************************************************
  warnings.warn(DEPRECATION_WARNING)
main_activate: path = /dev/sdm1
get_dm_uuid: get_dm_uuid /dev/sdm1 uuid path is /sys/dev/block/8:193/dm/uuid
command: Running command: /usr/sbin/blkid -o udev -p /dev/sdm1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/sdm1
```

4.2) osds are not associate with journals and hard drives anymore:

```
/dev/sda :
/dev/sda1 other, xfs, mounted on /usr/share/zoneinfo/UTC
/dev/sdb :
/dev/sdb1 ceph journal, for /dev/sdd1
/dev/sdb2 ceph journal, for /dev/sdf1
/dev/sdb3 ceph journal, for /dev/sdh1
/dev/sdb4 ceph journal, for /dev/sdj1
/dev/sdb5 ceph journal, for /dev/sdl1
/dev/sdb6 ceph journal, for /dev/sdn1
/dev/sdc :
/dev/sdc1 ceph journal, for /dev/sde1
/dev/sdc2 ceph journal, for /dev/sdg1
/dev/sdc3 ceph journal, for /dev/sdi1
/dev/sdc4 ceph journal, for /dev/sdk1
/dev/sdc5 ceph journal, for /dev/sdm1
/dev/sdc6 ceph journal, for /dev/sdo1
/dev/sdd :
/dev/sdd1 ceph data, prepared, cluster ceph, osd.63, journal /dev/sdb1
/dev/sde :
/dev/sde1 ceph data, prepared, cluster ceph, journal /dev/sdc1
/dev/sdf :
/dev/sdf1 ceph data, prepared, cluster ceph, osd.72, journal /dev/sdb2
/dev/sdg :
/dev/sdg1 ceph data, prepared, cluster ceph, journal /dev/sdc2
/dev/sdh :
/dev/sdh1 ceph data, active, cluster ceph, osd.87, journal /dev/sdb3
/dev/sdi :
/dev/sdi1 ceph data, prepared, cluster ceph, journal /dev/sdc3
/dev/sdj :
/dev/sdj1 ceph data, prepared, cluster ceph, osd.90, journal /dev/sdb4
/dev/sdk :
/dev/sdk1 ceph data, prepared, cluster ceph, journal /dev/sdc4
/dev/sdl :
/dev/sdl1 ceph data, prepared, cluster ceph, osd.77, journal /dev/sdb5
/dev/sdm :
/dev/sdm1 ceph data, prepared, cluster ceph, journal /dev/sdc5
/dev/sdn :
/dev/sdn1 ceph data, prepared, cluster ceph, osd.105, journal /dev/sdb6
/dev/sdo :
/dev/sdo1 ceph data, prepared, cluster ceph, journal /dev/sdc6

```

Share your group_vars files, inventory
```
all:
  vars: { osd_pool_pg_num: 256, monitor_network_vlan: 230, cluster_network_vlan: 240,
          ceph_pub_subnet: '172.23.0.0/21', ceph_cluster_subnet: '172.24.0.0/21', cloud_name: ***,
          cluster_fsid:**** ansible_user: **** }

  hosts:
    # keep existing monitor nodes
    ceph0: {ansible_host: 135.228.129.0, monitor_address: 172.23.7.0, cluster_address: 172.24.7.0}
    ceph4: {ansible_host: 135.228.129.4, monitor_address: 172.23.7.4, cluster_address: 172.24.7.4}
    ceph3: {ansible_host: 135.228.129.3, monitor_address: 172.23.7.3, cluster_address: 172.24.7.3}
    ceph2: {ansible_host: 135.228.129.2, monitor_address: 172.23.7.2, cluster_address: 172.24.7.2}
    ceph1: {ansible_host: 135.228.129.1, monitor_address: 172.23.7.1, cluster_address: 172.24.7.1}
    ceph6: {ansible_host: 135.228.129.6, monitor_address: 172.23.7.6, cluster_address: 172.24.7.6}

  children:
    osds:
      hosts:
        ceph6:
          devices:
            - /dev/sdd
            - /dev/sde
            - /dev/sdf
            - /dev/sdg
            - /dev/sdh
            - /dev/sdi
            - /dev/sdj
            - /dev/sdk
            - /dev/sdl
            - /dev/sdm
            - /dev/sdn
            - /dev/sdo
          dedicated_devices:
            - /dev/sdb1
            - /dev/sdc1
            - /dev/sdb2
            - /dev/sdc2
            - /dev/sdb3
            - /dev/sdc3
            - /dev/sdb4
            - /dev/sdc4
            - /dev/sdb5
            - /dev/sdc5
            - /dev/sdb6
            - /dev/sdc6
    mons:
      hosts: { ceph0, ceph1, ceph2, ceph3, ceph4 }
```

**Environment**:
* OS (e.g. from /etc/os-release): 
ceph MIMIC
* Kernel (e.g. `uname -a`): 
Linux 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-75.git8633870.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      8633870/1.13.1
 Built:           Fri Sep 28 19:45:08 2018
 OS/Arch:         linux/amd64
 Experimental:    false

* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.6.12
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv/lib/python2.7/site-packages/ansible
  executable location = /opt/venv/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
https://github.com/ceph/ceph-ansible/releases/tag/v3.2.14

* Ceph version (e.g. `ceph -v`):
ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)
