### ISSUE TITLE
ceph-mds: osd pool creation fails for 'erasure' type

### ISSUE THREAD

**Issue by skjoedt** [ceph/ceph-ansible#4768]
**Bug Report**

When creating cephfs data pools with erasure code instead of replication, the wrong command is constructed by the [create_mds_filesystems.yml](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mds/tasks/create_mds_filesystems.yml) task. 

Expected command: 

```
ceph --cluster ceph osd pool create cephfs_data 8 8 erasure default
```
Constructed command:
```
ceph --cluster ceph osd pool create cephfs_data 8 8 erasure 3 default
```

**Stderr message:**
```
TASK [ceph-mds : create filesystem pools] ***********************************************************************************************
Saturday 23 November 2019  18:12:41 +0100 (0:00:00.103)       0:05:45.250 *****
failed: [osd0 -> 192.168.121.171] (item={'name': 'cephfs_data', 'pg_num': '8', 'pgp_num': '8', 'rule_name': 'erasure', 'type': 'erasure',
 'erasure_profile': 'default', 'expected_num_objects': '', 'application': 'cephfs', 'size': '3', 'min_size': '0'}) => changed=false 
  ansible_loop_var: item
  cmd:
  - ceph
  - --cluster
  - ceph
  - osd
  - pool
  - create
  - cephfs_data
  - '8'
  - '8'
  - erasure
  - '3'
  - default
  delta: '0:00:00.504146'
  end: '2019-11-23 17:12:42.481327'
  item:
    application: cephfs
    erasure_profile: default
    expected_num_objects: ''
    min_size: '0'
    name: cephfs_data
    pg_num: '8'
    pgp_num: '8'
    rule_name: erasure
    size: '3'
    type: erasure
  msg: non-zero return code
  rc: 2
  start: '2019-11-23 17:12:41.977181'
  stderr: 'Error ENOENT: specified rule default doesn''t exist'
```
The problem can be reproduced with the cephfs block below (group_vars/all.yml):

```yaml
##########
# CEPHFS #
##########
cephfs: cephfs # name of the ceph filesystem
cephfs_data_pool:
  name: "{{ cephfs_data if cephfs_data is defined else 'cephfs_data' }}"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "erasure"
  type: 'erasure'
  erasure_profile: "default"
  expected_num_objects: ""
  application: "cephfs"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
cephfs_metadata_pool:
  name: "{{ cephfs_metadata if cephfs_metadata is defined else 'cephfs_metadata' }}"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "erasure"
  type: 'erasure'
  erasure_profile: "default"
  expected_num_objects: ""
  application: "cephfs"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
cephfs_pools:
  - "{{ cephfs_data_pool }}"
  - "{{ cephfs_metadata_pool }}"
```

The misbehaving [line](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mds/tasks/create_mds_filesystems.yml#L31) seems to be 

```yaml
{{ 1 if item.type|default(1) == 'replicated' else 3 if item.type|default(1) == 'erasure' else item.type|default(1) }}
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 1804
* Kernel (e.g. `uname -a`): 4.15.0-64-generic
* Docker version if applicable (e.g. `docker version`): N/A
* Ansible version (e.g. `ansible-playbook --version`): ansible 2.8.4
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.4

**Comment by skjoedt** [comment]
It seems that `cephfs_pool.type` can take either a number `3` or the name `erasure` to trigger erasure profile. However, it is not clear if the number itself should be injected into the `ceph osd pool create` command.

According to the [documentation](https://docs.ceph.com/docs/nautilus/rados/operations/pools/#create-a-pool), nothing is expected between `erasure` and `erasure_profile`

**Comment by skjoedt** [comment]
I was able to workaround it by setting `type: "default"` in the group_vars. 

Also, for other's interest I had to change the metadata to replicate according to documentation:

> Erasure coded pools do not support omap, so to use them with RBD and CephFS you must instruct them to store their data in an ec pool, **and their metadata in a replicated pool.**

Now my all.yml looks like

```yaml
cephfs: cephfs # name of the ceph filesystem
cephfs_data_pool:
  name: "{{ cephfs_data if cephfs_data is defined else 'cephfs_data' }}"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "erasure"
  type: "default"
  erasure_profile: ""
  expected_num_objects: ""
  application: "cephfs"
  size: "{{ ceph_osd_pool_default_size }}"
  min_size: "{{ ceph_osd_pool_default_min_size }}"
cephfs_metadata_pool:
  name: "{{ cephfs_metadata if cephfs_metadata is defined else 'cephfs_metadata' }}"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "cephfs"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
cephfs_pools:
  - "{{ cephfs_data_pool }}"
  - "{{ cephfs_metadata_pool }}"
```
