### ISSUE TITLE
ceph-mds: cephfs filesystems does not support erasure coded pools

### ISSUE THREAD

**Issue by skjoedt** [ceph/ceph-ansible#4769]
For filesystems to use erasure coded pools, the data pool needs to be [modified slightly](https://docs.ceph.com/docs/nautilus/rados/operations/erasure-code/#erasure-coding-with-overwrites).

```
ceph osd pool set ec_pool allow_ec_overwrites true
```
**Describe the solution you'd like**
This could be implemented in the `deploy filesystem pools` block of [create_mds_filesystems.yml](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mds/tasks/create_mds_filesystems.yml) as:

```yaml
- name: customize pool for partial writes
  command: "{{ container_exec_cmd | default('') }} ceph --cluster {{ cluster }} osd pool set {{ item.name }} allow_ec_overwrites true"
  with_items: "{{ cephfs_pools | unique }}"
  changed_when: false
  when: item.type | default("1") == '3' or item.type | default("1") == 'erasure'
```

**Describe alternatives you've considered**
A explicit flag could be introduced into `cephfs_pools.allow_ec_overwrites` that can be used to toggle this behavior. I don't know why it shouldn't always follow `cephfs_pools.type == erasure` though. 

**Additional context**
This might need to be tested with a fix to #4768 as it is unclear whether the `cephfs_pools.type` is used correct.
