### ISSUE TITLE
InfluxDB mgr-module missing dependancies

### ISSUE THREAD

**Issue by Hobadee** [ceph/ceph-ansible#4859]
# Bug Report
*Note:* I have updated my hosts.yml and group_vars below since originally submitting this issue.  I did this after I found issues with my original configuration which was causing other issues.

## What happened:
After running ceph-ansible, the system is unable to start the influxdb mgr module due to a missing python library.

## What you expected to happen:
ceph-ansible should produce a fully-functional system with all options available to users.

## How to reproduce it (minimal and precise):
Clean install of system using ceph-ansible

## Resolution:
1. On Manager nodes (`mgrs`) install `pip`
     * CentOS 7 Package: `python2-pip`
1. Using `pip` on the `mgrs` nodes, install the `influxdb` package
1. (Optional) Enable the module using a non-active manager node by using `ceph mgr module enable influx`

Some users may not want these additional packages installed, so it may be desirable to make a configuration variable to enable these packages.  I shall leave that discussion up to the developers.

# Vars
## Hosts
**hosts.yml**
``` yml
all:
  hosts:
    stor0[1:4].<<redacted>>:
      ansible_user: ansible
  children:
    mgrs:
      hosts:
        stor0[1:3].<<redacted>>:
    mons:
      hosts:
        stor0[1:3].<<redacted>>:
    osds:
      hosts:
        stor0[1:4].<<redacted>>:
          devices:
            - /dev/sdb
            - /dev/sdc
            - /dev/sdd
            - /dev/sde
            - /dev/sdf
            - /dev/sdg
    iscsigws:
      hosts:
        stor0[1:2].<<redacted>>:
    grafana-server:
      hosts:
        stor01.<<redacted>>:
```

## Group Vars
**group_vars/all.yml**
``` yml
---
dummy:
fetch_directory: fetch/
configure_firewall: True
ceph_mon_firewall_zone: public
ceph_mgr_firewall_zone: public
ceph_osd_firewall_zone: public
ceph_iscsi_firewall_zone: public
ceph_dashboard_firewall_zone: public
centos_package_dependencies:
  - epel-release
  - libselinux-python
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
cephx: true
monitor_address_block: 10.7.11.0/24
ip_version: ipv4
public_network: 10.7.11.0/24
cluster_network: 10.7.12.0/24
ceph_tcmalloc_max_total_thread_cache: 0
dashboard_admin_password: "<<redacted>>"
dashboard_rgw_api_no_ssl_verify: true
```

**group_vars/mgrs.yml**
``` yml
---
dummy:
ceph_mgr_modules: 
  - dashboard
  - prometheus
  - influx
ceph_mgr_packages:
  - ceph-mgr
  - ceph-mgr-dashboard
  - ceph-mgr-diskprediction-local
  - python2-pip
```

**group_vars/iscsigws.yml**
``` yml
---
dummy:
api_user: "admin"
api_password: "<<redacted>>"
```

**group_vars/mons.yml**
``` yml
dummy:
```

**group_vars/osds.yml**
``` yml
dummy:
```

# Environment:
* OS (e.g. from /etc/os-release): 
    ```
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"
    ```
* Kernel (e.g. `uname -a`):
    `Linux <redacted> 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Ansible version (e.g. `ansible-playbook --version`):
    ```
    ansible-playbook 2.8.2
      config file = /Users/erick/src/ansible/ceph-ansible/ansible.cfg
      configured module search path = [u'/Users/erick/src/ansible/ceph-ansible/library']
      ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
      executable location = /usr/local/bin/ansible-playbook
      python version = 2.7.17 (default, Oct 24 2019, 12:57:47) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]
* ceph-ansible version (e.g. `git head or tag or stable branch`):
    `v4.0.5`
* Ceph version (e.g. `ceph -v`):
    `ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)`
