### ISSUE TITLE
task tries to use dnf in CentOS7

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#4918]
**Bug Report**

What happened: The redhat_dev_repository.yml which gets included for CentOS distros has the following task:

```yaml
- name: enable ceph-el8 copr
  command: dnf copr enable -y ktdreyer/ceph-el8
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:ktdreyer:ceph-el8.repo
    warn: false
  register: result
  until: result is succeeded
```

This is intended only for CentOS8, and it causes any deployment on CentOS7 to fail.

What you expected to happen:

How to reproduce it (minimal and precise): Run ceph-ansible master against CentOS7

Share your group_vars files, inventory

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):
