### ISSUE TITLE
Upgrade error - validate ceph_origin

### ISSUE THREAD

**Issue by rlljorge** [ceph/ceph-ansible#4968]
Hello there,

I am try upgrade my cluster from mimic to nautilus without success.

Before upgrade I executed site.yaml without errors in mimic release, the cluster is ok and updated.

```console
[root@mon01 ~]# ceph -v
ceph version 13.2.8 (5579a94fafbc1f9cc913a0f5d362953a5d9c3ae0) mimic (stable)
[root@mon01 ~]# ceph -s
  cluster:
    id:     d6fd8a81-377c-47a7-b110-db9800be79cd
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum mon01,mon02,mon03
    mgr: mon01(active), standbys: mon02, mon03
    osd: 12 osds: 12 up, 12 in
    rgw: 2 daemons active

  data:
    pools:   15 pools, 544 pgs
    objects: 3.05 M objects, 7.4 TiB
    usage:   22 TiB used, 65 TiB / 87 TiB avail
    pgs:     543 active+clean
             1   active+clean+scrubbing+deep

  io:
    client:   9.4 MiB/s rd, 4.2 MiB/s wr, 117 op/s rd, 154 op/s wr
```

SO Info:

cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
Kernel:3.10.0-862.14.4.el7.x86_64
Ansible 2.8.8

[root@ceph-deploy-799889c476-lk27p ceph-ansible]# cat /etc/ansible/hosts
```yaml
[mons]
mon01 monitor_address=10.250.6.1
mon02 monitor_address=10.250.6.2
mon03 monitor_address=10.250.6.3

[osds]
osd01 osd_scenario="lvm" lvm_volumes="[{'data': 'data-lv1', 'data_vg': 'data-vg1', 'wal': 'wal-lv1', 'wal_vg': 'wal-vg1'},{'data': 'data-lv2', 'data_vg': 'data-vg2', 'wal': 'wal-lv2', 'wal_vg': 'wal-vg2'},{'data': 'data-lv3', 'data_vg': 'data-vg3', 'wal': 'wal-lv3', 'wal_vg': 'wal-vg3'}]"
osd02 osd_scenario="lvm" lvm_volumes="[{'data': 'data-lv1', 'data_vg': 'data-vg1', 'wal': 'wal-lv1', 'wal_vg': 'wal-vg1'},{'data': 'data-lv2', 'data_vg': 'data-vg2', 'wal': 'wal-lv2', 'wal_vg': 'wal-vg2'},{'data': 'data-lv3', 'data_vg': 'data-vg3', 'wal': 'wal-lv3', 'wal_vg': 'wal-vg3'}]"
osd03 osd_scenario="lvm" lvm_volumes="[{'data': 'data-lv1', 'data_vg': 'data-vg1', 'wal': 'wal-lv1', 'wal_vg': 'wal-vg1'},{'data': 'data-lv2', 'data_vg': 'data-vg2', 'wal': 'wal-lv2', 'wal_vg': 'wal-vg2'},{'data': 'data-lv3', 'data_vg': 'data-vg3', 'wal': 'wal-lv3', 'wal_vg': 'wal-vg3'}]"
osd04 osd_scenario="lvm" lvm_volumes="[{'data': 'data-lv1', 'data_vg': 'data-vg1', 'wal': 'wal-lv1', 'wal_vg': 'wal-vg1'},{'data': 'data-lv2', 'data_vg': 'data-vg2', 'wal': 'wal-lv2', 'wal_vg': 'wal-vg2'},{'data': 'data-lv3', 'data_vg': 'data-vg3', 'wal': 'wal-lv3', 'wal_vg': 'wal-vg3'}]"


[mgrs]
mon01
mon02
mon03

[rgws]
rgw01
rgw02
```
My group_vars/all.yml
```yaml
---
ceph_release_num:
  luminous: 12
  mimic: 13
mon_group_name: mons
osd_group_name: osds
mgr_group_name: mgrs
configure_firewall: False #True
ntp_daemon_type: chronyd
upgrade_ceph_packages: True #False
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
monitor_interface: "bond0.51"
monitor_address_block: 10.250.6.0/25
journal_size: 20480
public_network: 10.250.6.0/25
cluster_network: 10.1.9.0/27
radosgw_interface: eth2
ceph_conf_overrides:
  mon:
      mon_allow_pool_delete: true
  "client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}":
      rgw enable usage log: true
      rgw usage log tick interval: 30
      rgw usage log flush threshold: 1024
      rgw usage max shards: 32
      rgw usage max user shards: 1
openstack_config: true
dashboard_enabled: False
```

I attached full ansible output

```console
TASK [ceph-validate : validate ceph_origin] ***********************************
task path: /opt/ceph-ansible/roles/ceph-validate/tasks/main.yml:5
Tuesday 21 January 2020  11:33:39 -0300 (0:00:01.432)       0:03:35.451 ******* 
fatal: [mon01]: FAILED! => changed=false 
  msg: ceph_origin must be either 'repository', 'distro' or 'local'
```
[ceph.txt](https://github.com/ceph/ceph-ansible/files/4091669/ceph.txt)
