### ISSUE TITLE
Secret key is not properly handled during multisite RGW deployments

### ISSUE THREAD

**Issue by p37ruh4** [ceph/ceph-ansible#5150]
**Bug Report**

What happened:
`system_secret_key` ansible variable is `system_secret_key` (string) instead of actual variable value.

How to reproduce it (minimal and precise):
Added debug task for variable and see that variable is not properly initialised:
```
  ansible_loop_var: item
  item:
  - hostname
  - endpoint: http://hostname:8080
    instance_name: rgw0
    radosgw_address: 172.16.XX.YY
    radosgw_frontend_port: 8080
    rgw_realm: ceph
    rgw_zone: site
    rgw_zone_user: zone_user
    rgw_zone_user_display_name: Zone User
    rgw_zonegroup: example
    system_access_key: 6kWkikvapSnHyE22P7nO
    system_secret_key: system_secret_key
```
Issue is in this line:
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-facts/tasks/set_radosgw_address.yml#L55

Share your group_vars files, inventory
```
$ cat group_vars/all.yml | grep _key
system_access_key: "{{ lookup('env','CEPH_SYSTEM_ACCESS_KEY') }}"
system_secret_key: "{{ lookup('env','CEPH_SYSTEM_SECRET_KEY') }}"
```

**Environment**:
OpenBSD on ansible controller
ansible-playbook 2.9.5
ceph-ansible stable version
