### ISSUE TITLE
[stable-4.0] generating ceph.conf fails at MGR install

### ISSUE THREAD

**Issue by ArKam** [ceph/ceph-ansible#5279]
**Bug Report**

What happened:
While deploying `stable-4.0` containerized minimal environment (1 ctrl / 3 osds nodes with only mon/mgr and osds) at the MGR Installation step, the installation stopped with the following error.

```
TASK [ceph-config : generate ceph.conf configuration file] *********************
Thursday 16 April 2020  17:02:34 +0200 (0:00:00.487)       0:03:57.202 ********
fatal: [ctrl-emea-01]: FAILED! => 
  msg: '''dict object'' has no attribute ''stdout'''
```

It's like if it wasn't able to use the `{{ cluster_uuid.stdout }}` variable previously built for the monitor.

How to reproduce it (minimal and precise):
`stable-4.0` branch deploying with bellow variables:

```yaml
mon_group_name: mons
osd_group_name: osds
mgr_group_name: mgrs

fsid: "{{ cluster_uuid.stdout }}"
generate_fsid: true
ceph_conf_key_directory: /etc/ceph
ceph_uid: 167
ceph_keyring_permissions: '0600'
cephx: true

monitor_interface: eno5.42
ip_version: ipv4

journal_size: 5120 # OSD journal size in MB
public_network: 10.1.42.0/24
cluster_network: 10.1.41.0/24
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: bluestore

osd_auto_discovery_exclude: "dm-*|loop*|md*|rbd*|sda|sdb|sdc"

##########
# DOCKER #
##########
containerized_deployment: true
container_package_name: docker-ce
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: 4.0.9
ceph_docker_registry: registry.internal.domain.tld
ceph_docker_registry_auth: true
ceph_docker_registry_username: username
ceph_docker_registry_password: password
ceph_docker_enable_centos_extra_repo: false

#############
# DASHBOARD #
#############
dashboard_enabled: False
dashboard_protocol: https
dashboard_port: 8443
dashboard_admin_user: username
dashboard_admin_user_ro: false
dashboard_admin_password: password
dashboard_crt: ''
dashboard_key: ''
```

**Environment**:
* **OS:** CentOS 7.7
* **Kernel:** Linux ctrl-emea-01 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Docker:** Docker version 19.03.8, build afacb8b
* **Ansible:** 2.9.6
* **ceph-ansible:** stable-4.0
* **Ceph:** v4.0.9-stable-4.0-nautilus-centos-7-x86_64
