### ISSUE TITLE
mgr daemons created by ceph-ansible are not visible to ceph

### ISSUE THREAD

**Issue by micmoyles** [ceph/ceph-ansible#5321]
[ansible-github.log](https://github.com/ceph/ceph-ansible/files/4529673/ansible-github.log)

**Bug Report**

I have 3 mgr daemons running but ceph is not aware of them.
```
[root@bvcephtest05 ~]# ceph status
  cluster:
    id:     81ae6812-607f-4205-9484-2d063a9c4431
    health: HEALTH_WARN
            clock skew detected on mon.bvcephtest04, mon.bvcephtest05

  services:
    mon: 3 daemons, quorum bvcephtest03,bvcephtest04,bvcephtest05 (age 5m)
    mgr: no daemons active
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:


[root@bvcephtest05 ~]# systemctl status ceph-mgr
ceph-mgr@bvcephtest05.service  ceph-mgr.target
[root@bvcephtest05 ~]# systemctl status ceph-mgr@bvcephtest05.service
● ceph-mgr@bvcephtest05.service - Ceph cluster manager daemon
   Loaded: loaded (/usr/lib/systemd/system/ceph-mgr@.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-04-24 11:34:35 BST; 5min ago
 Main PID: 50595 (ceph-mgr)
    Tasks: 21 (limit: 23597)
   Memory: 117.7M
   CGroup: /system.slice/system-ceph\x2dmgr.slice/ceph-mgr@bvcephtest05.service
           └─50595 /usr/bin/ceph-mgr -f --cluster ceph --id bvcephtest05 --setuser ceph --setgroup ceph

```
Apr 24 11:34:35 bvcephtest05 systemd[1]: Started Ceph cluster manager daemon..`

What you expected to happen:

The mgr daemons to be detected :) 

How to reproduce it (minimal and precise):

This is how I have defined my inventory. My hosts are all Centos8 VMs.
```
cat  inventory
[mons]
bvcephtest03
bvcephtest04
bvcephtest05
[mgrs]
bvcephtest03
bvcephtest04
bvcephtest05

[osds]
bvcephtest01
bvcephtest03
bvcephtest04
bvcephtest05

[rgws]
bvcephtest01

[grafana-server]
bvcephtest01
```

I have tried this a number of times and get the same result. I've used new VMs and run the purge-cluster playbook to start the entire process from scratch. 

The run fails at the same task every time
`TASK [ceph-mgr : wait for all mgr to be up]`
Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
* Kernel (e.g. `uname -a`):
`Linux bvcephtest05 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version if applicable (e.g. `docker version`):
NA
* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.9.6
* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-5.0
* Ceph version (e.g. `ceph -v`):
ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)

*Group vars*
grep -vE '^#' group_vars/all.yml | uniq
```yaml
---
centos_package_dependencies:
  - epel-release
  - python3-libselinux
ntp_service_enabled: true
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
ceph_stable_redhat_distro: el8
monitor_address_block: 10.64.6.0/24
public_network: 10.64.6.0/24
cluster_network: "{{ public_network | regex_replace(' ', '') }}"
radosgw_address: 10.64.6.11
dashboard_enabled: True
dashboard_protocol: http
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_user_ro: false
dashboard_admin_password: p@ssw0rd
grafana_admin_user: admin
grafana_admin_password: admin
```
grep -vE '^#' group_vars/osds.yml | uniq
```yaml
---
devices:
  - /dev/sdb
```

**Comment by dsavineau** [comment]
Share your group_vars files, inventory and full ceph-ansibe log

**Comment by micmoyles** [comment]
> Share your group_vars files, inventory and full ceph-ansibe log

They are all included now. I haven't attached the full contents of group vars as they are most commented out, if the whole files are better please let me know.

**Comment by dsavineau** [comment]
> > Share your group_vars files, inventory and full ceph-ansibe log
> 
> They are all included now. I haven't attached the full contents of group vars as they are most commented out, if the whole files are better please let me know.

egrep -v '^(#|$|dummy)' group_vars/*.yml ;)

**Comment by micmoyles** [comment]
> > > Share your group_vars files, inventory and full ceph-ansibe log
> > 
> > 
> > They are all included now. I haven't attached the full contents of group vars as they are most commented out, if the whole files are better please let me know.
> 
> `egrep -v '^(#|$|dummy)' group_vars/*.yml` ;)

```
  egrep -v '^(#|$|dummy)' group_vars/*.yml
group_vars/all.yml:---
group_vars/all.yml:centos_package_dependencies:
group_vars/all.yml:  - epel-release
group_vars/all.yml:  - python3-libselinux
group_vars/all.yml:ntp_service_enabled: true
group_vars/all.yml:ceph_origin: repository
group_vars/all.yml:ceph_repository: community
group_vars/all.yml:ceph_stable_release: octopus
group_vars/all.yml:ceph_stable_redhat_distro: el8
group_vars/all.yml:monitor_address_block: 10.64.6.0/24
group_vars/all.yml:public_network: 10.64.6.0/24
group_vars/all.yml:cluster_network: "{{ public_network | regex_replace(' ', '') }}"
group_vars/all.yml:radosgw_address: 10.64.6.11
group_vars/all.yml:dashboard_enabled: True
group_vars/all.yml:dashboard_protocol: http
group_vars/all.yml:dashboard_port: 8443
group_vars/all.yml:dashboard_admin_user: admin
group_vars/all.yml:dashboard_admin_user_ro: false
group_vars/all.yml:dashboard_admin_password: p@ssw0rd
group_vars/all.yml:grafana_admin_user: admin
group_vars/all.yml:grafana_admin_password: admin
group_vars/mons.yml:---
group_vars/osds.yml:---
group_vars/osds.yml:devices:
group_vars/osds.yml:  - /dev/sdb
group_vars/rgws.yml:---
```

**Comment by dsavineau** [comment]
Would it be possible to get the ceph-mgr journald log from one of the mgr node ?

From the ceph-ansible execution perspective everything seems fine.

You mentioned that you're using the stable-5.0 branch. Could you tell me the exact sha1 commit ?

**Comment by micmoyles** [comment]
Sure 

```
 journalctl -u  ceph-mgr@bvcephtest05.service
-- Logs begin at Fri 2020-04-24 12:26:42 BST, end at Fri 2020-04-24 16:20:30 BST. --
Apr 24 12:26:50 bvcephtest05 systemd[1]: Started Ceph cluster manager daemon.
```

```
cat ceph-mgr.bvcephtest05.log
2020-04-24T11:34:35.567+0100 7f2538c85040  0 set uid:gid to 167:167 (ceph:ceph)
2020-04-24T11:34:35.567+0100 7f2538c85040  0 ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable), process ceph-mgr, pid 50595
2020-04-24T11:34:35.567+0100 7f2538c85040  0 pidfile_write: ignore empty --pid-file
2020-04-24T11:34:35.590+0100 7f2538c85040  1 mgr[py] Loading python module 'alerts'
2020-04-24T11:34:35.672+0100 7f2538c85040  1 mgr[py] Loading python module 'balancer'
2020-04-24T11:34:35.728+0100 7f2538c85040  1 mgr[py] Loading python module 'crash'
2020-04-24T11:34:35.785+0100 7f2538c85040  1 mgr[py] Loading python module 'dashboard'
2020-04-24T11:34:36.385+0100 7f2538c85040  1 mgr[py] Loading python module 'devicehealth'
2020-04-24T11:34:36.434+0100 7f2538c85040  1 mgr[py] Loading python module 'diskprediction_local'
2020-04-24T12:18:57.575+0100 7f3afe86e040  0 set uid:gid to 167:167 (ceph:ceph)
2020-04-24T12:18:57.575+0100 7f3afe86e040  0 ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable), process ceph-mgr, pid 53708
2020-04-24T12:18:57.575+0100 7f3afe86e040  0 pidfile_write: ignore empty --pid-file
2020-04-24T12:18:57.607+0100 7f3afe86e040  1 mgr[py] Loading python module 'alerts'
2020-04-24T12:18:57.719+0100 7f3afe86e040  1 mgr[py] Loading python module 'balancer'
2020-04-24T12:18:57.803+0100 7f3afe86e040  1 mgr[py] Loading python module 'crash'
2020-04-24T12:18:57.888+0100 7f3afe86e040  1 mgr[py] Loading python module 'dashboard'
2020-04-24T12:18:58.602+0100 7f3afe86e040  1 mgr[py] Loading python module 'devicehealth'
2020-04-24T12:18:58.676+0100 7f3afe86e040  1 mgr[py] Loading python module 'diskprediction_local'
2020-04-24T12:26:58.180+0100 7fcac6a5a040  0 set uid:gid to 167:167 (ceph:ceph)
2020-04-24T12:26:58.180+0100 7fcac6a5a040  0 ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable), process ceph-mgr, pid 1753
2020-04-24T12:26:58.180+0100 7fcac6a5a040  0 pidfile_write: ignore empty --pid-file
2020-04-24T12:26:58.235+0100 7fcac6a5a040  1 mgr[py] Loading python module 'alerts'
2020-04-24T12:26:58.495+0100 7fcac6a5a040  1 mgr[py] Loading python module 'balancer'
2020-04-24T12:26:58.609+0100 7fcac6a5a040  1 mgr[py] Loading python module 'crash'
2020-04-24T12:26:58.781+0100 7fcac6a5a040  1 mgr[py] Loading python module 'dashboard'
2020-04-24T12:26:59.759+0100 7fcac6a5a040  1 mgr[py] Loading python module 'devicehealth'
2020-04-24T12:26:59.809+0100 7fcac6a5a040  1 mgr[py] Loading python module 'diskprediction_local'
```

HEAD of my repo
commit 47d7819bbecf90cea11ab16c619b0ec8220f6c6e (HEAD -> stable-5.0, origin/stable-5.0)

From the ceph-ansible perspective everything runs without error until the step where is tries to verify the mgrs are active. In a previous task to start the mgr daemons everything runs smoothly. 

When I dump the state of the mgr I notice that the active_addrs is empty and that the range is unrecognised.

```
[root@bvcephtest05 ceph-bvcephtest05]# ceph --cluster ceph mgr dump
{
    "epoch": 1,
    "active_gid": 0,
    "active_name": "",
    "active_addrs": {
        "addrvec": []
    },
    "active_addr": "(unrecognized address family 0)/0",
    "active_change": "0.000000",
    "active_mgr_features": 0,
    "available": false,
    "standbys": [],
    "modules": [
        "iostat",
        "restful"
    ],
    "available_modules": [],
    "services": {},
    "always_on_modules": {
        "nautilus": [
            "balancer",
            "crash",
            "devicehealth",
            "orchestrator_cli",
            "progress",
            "rbd_support",
            "status",
            "volumes"
        ],
        "octopus": [
            "balancer",
            "crash",
            "devicehealth",
            "orchestrator",
            "osd_support",
            "pg_autoscaler",
            "progress",
            "rbd_support",
            "status",
            "telemetry",
            "volumes"
        ],
        "last_failure_osd_epoch": 0,
        "active_clients": []
    }
}
```

**Comment by micmoyles** [comment]
Thanks for linking the other issue. 
Here is some more info from my side
*ceph status*
```
[root@bvcephtest05 ceph]# ceph -s
  cluster:
    id:     81ae6812-607f-4205-9484-2d063a9c4431
    health: HEALTH_WARN
            clock skew detected on mon.bvcephtest04, mon.bvcephtest05

  services:
    mon: 3 daemons, quorum bvcephtest03,bvcephtest04,bvcephtest05 (age 4h)
    mgr: no daemons active
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:
```
*mgr daemon config*
```
 ceph daemon  mgr.bvcephtest05 config  show | grep 10.64
    "cluster_network": "10.64.6.0/24",
    "mon_host": "[v2:10.64.6.8:3300,v1:10.64.6.8:6789],[v2:10.64.6.9:3300,v1:10.64.6.9:6789],[v2:10.64.6.10:3300,v1:10.64.6.10:6789]",
    "public_addr": "v2:10.64.6.10:0/0",
    "public_network": "10.64.6.0/24",
```

Is there anything else that would be helpful?
