### ISSUE TITLE
stderr: Calculated size of logical volume is 0 extents. Needs to be larger.

### ISSUE THREAD

**Issue by skunkr** [ceph/ceph-ansible#5323]
Hello Guys,
I have this error output when trying to deploy Nautilus from release-4 branch.

```console
"    Running command: /sbin/lvcreate --yes -l 100%FREE -n osd-block-b50caec4-5cbd-4390-a3ce-2d9e88a60963 ceph-795de951-f1b1-4b93-a53f-c9830ae55f40
     stderr: Calculated size of logical volume is 0 extents. Needs to be larger.
    --> Was unable to complete a new OSD, will rollback changes
"
```

I think the problem is somewhere on my side,  but i'm just scratching my head trying to sort it out.
Could you please hekp me with this, or a hint direction about what could be the issue ?

Roughly, in my all.yml all I  have is:
```yaml
dummy:

dashboard_admin_password: password
grafana_admin_password: password

mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
nfs_group_name: nfss
rbdmirror_group_name: rbdmirrors
client_group_name: clients
iscsi_gw_group_name: iscsigws
mgr_group_name: mgrs
rgwloadbalancer_group_name: rgwloadbalancers
grafana_server_group_name: grafana-server


ceph_origin: repository
ceph_repository: community
ceph_repository_type: cdn
ceph_stable_release: nautilus
monitor_interface: eth0
public_network: 192.168.102.0/24
cluster_network: 192.168.60.0/24
journal_size: 32768

osd_objectstore: bluestore
lvm_volumes:
 - data: /dev/sda
   wal: /dev/sdf1

 - data: /dev/sdb
   wal: /dev/sdf2

 - data: /dev/sdc
   wal: /dev/sdf3

 - data: /dev/sdd
   wal: /dev/sdf4

configure_firewall: False
```
Does /dev/sdf need to have the partition already prepared or something ? A couple of month ago I did exactly the same deployment and worked like a charm, just can't figure out what is hapenning now..
Any suggestions ?
Thank you,

Leo

**Comment by dsavineau** [comment]
ceph-volume won't create the partition on /dev/sdf in this configuration. The partition needs to exist prior the ceph-ansible execution and match the size requirement (something like 5G)

If you're using only raw devices (not LV/VG setup) then you can switch to the ceph-volume lvm batch configuration.

```yaml
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
bluestore_wal_devices:
  - /dev/sdf
```
