### ISSUE TITLE
ceph-rgw: Pool creation fails with Ansible 2.9 on stable-5.0

### ISSUE THREAD

**Issue by BenoitKnecht** [ceph/ceph-ansible#5348]
**Bug Report**

What happened:

Applying the `ceph-rgw` role (on branch `stable-5.0`) with

```yaml
rgw_create_pools:
  .rgw.root:
    size: 3
  "{{ rgw_zone }}.rgw.control":
    size: 3
  "{{ rgw_zone }}.rgw.meta":
    size: 3
  "{{ rgw_zone }}.rgw.log":
    size: 3
  "{{ rgw_zone }}.rgw.buckets.index":
    size: 3
  "{{ rgw_zone }}.rgw.buckets.data":
    size: 3
```

fails with

```
  ansible_loop_var: item
  attempts: 60
  cmd:
  - ceph
  - --connect-timeout
  - '20'
  - --cluster
  - ceph
  - osd
  - pool
  - create
  - '{{'
  - rgw_zone
  - '}}.rgw.control'
  - '8'
  - replicated
  delta: '0:00:00.197946'
  end: '2020-05-08 13:39:43.871201'
  item:
    key: '{{ rgw_zone }}.rgw.control'
    value:
      size: 3
```

What you expected to happen:

The pools are created without error.

How to reproduce it (minimal and precise):

Since I'm using `stable-5.0`, I'm also using Ansible 2.9. The same configuration worked fine on `stable-4.0` with Ansible 2.8, so I suspected something changed with the way the template variables are expanded.

To validate that hypothesis, I created this very simple `site.yml` playbook:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - debug:
      msg: "{{ item.key }}"
    with_dict: "{{ rgw_create_pools }}"
```

and `host_vars/localhost.yml` file:

```yaml
rgw_zone: default
  
rgw_create_pools:
  .rgw.root:
    size: 3
  "{{ rgw_zone }}.rgw.control":
    size: 3
  "{{ rgw_zone }}.rgw.meta":
    size: 3
  "{{ rgw_zone }}.rgw.log":
    size: 3
  "{{ rgw_zone }}.rgw.buckets.index":
    size: 3
  "{{ rgw_zone }}.rgw.buckets.data":
    size: 3
```

With Ansible 2.8.11, I get:

```console
$ ansible-playbook site.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'


PLAY [localhost] ******************************************************************************************************

TASK [debug] **********************************************************************************************************
ok: [localhost] => (item={'key': '.rgw.root', 'value': {'size': 3}}) => {
    "msg": ".rgw.root"
}
ok: [localhost] => (item={'key': 'default.rgw.control', 'value': {'size': 3}}) => {
    "msg": "default.rgw.control"
}
ok: [localhost] => (item={'key': 'default.rgw.meta', 'value': {'size': 3}}) => {
    "msg": "default.rgw.meta"
}
ok: [localhost] => (item={'key': 'default.rgw.log', 'value': {'size': 3}}) => {
    "msg": "default.rgw.log"
}
ok: [localhost] => (item={'key': 'default.rgw.buckets.index', 'value': {'size': 3}}) => {
    "msg": "default.rgw.buckets.index"
}
ok: [localhost] => (item={'key': 'default.rgw.buckets.data', 'value': {'size': 3}}) => {
    "msg": "default.rgw.buckets.data"
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

But with Ansible 2.9.7, I get:

```console
$ ansible-playbook site.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [localhost] ******************************************************************************************************

TASK [debug] **********************************************************************************************************
ok: [localhost] => (item={'key': '.rgw.root', 'value': {'size': 3}}) => {
    "msg": ".rgw.root"
}
ok: [localhost] => (item={'key': '{{ rgw_zone }}.rgw.control', 'value': {'size': 3}}) => {
    "msg": "{{ rgw_zone }}.rgw.control"
}
ok: [localhost] => (item={'key': '{{ rgw_zone }}.rgw.meta', 'value': {'size': 3}}) => {
    "msg": "{{ rgw_zone }}.rgw.meta"
}
ok: [localhost] => (item={'key': '{{ rgw_zone }}.rgw.log', 'value': {'size': 3}}) => {
    "msg": "{{ rgw_zone }}.rgw.log"
}
ok: [localhost] => (item={'key': '{{ rgw_zone }}.rgw.buckets.index', 'value': {'size': 3}}) => {
    "msg": "{{ rgw_zone }}.rgw.buckets.index"
}
ok: [localhost] => (item={'key': '{{ rgw_zone }}.rgw.buckets.data', 'value': {'size': 3}}) => {
    "msg": "{{ rgw_zone }}.rgw.buckets.data"
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
