### ISSUE TITLE
Enabeling `mon_host_v1` on already deployed cluster  

### ISSUE THREAD

**Issue by mafonso** [ceph/ceph-ansible#5419]
**Bug Report**

What happened:

Deployed a single node cluster with the v1 endpoint disabled on `group_vars/all.yml` 

```
mon_host_v1:
  enabled: False
  suffix: ':6789'
mon_host_v2:
  suffix: ':3300'
```
The cluster deployed successfully with only port 3300 on the mon as expected. 

Then I realised I needed the v1 endpoint as well. So updated `group_vars/all.yml` to have
```
mon_host_v1:
  enabled: True
  suffix: ':6789'
mon_host_v2:
  suffix: ':3300'
```
The ansible run terminated successfully, and the ceph.conf config was updated. 
However mon did not bind on port 6789 as well.  

What you expected to happen:

How to reproduce it (minimal and precise):

Deploy a fresh cluster with minimal group_vars containing
```
mon_host_v1:
  enabled: False
  suffix: ':6789'
mon_host_v2:
  suffix: ':3300'
```
Update group_vars to set
```
mon_host_v1:
  enabled: True
```
Verify that the ceph.conf is updated but mon does not bind to the v1 port.
Sha your group_vars files, inventory and **full** ceph-ansibe log

**Update:** 

Deploying a fresh cluster with 
```
mon_host_v1:
  enabled: True
```
from the start, works just fine with both endpoints available. 

**Environment**:
* OS (e.g. from /etc/os-release): 18.04.4 LTS (Bionic Beaver)
* Kernel (e.g. `uname -a`): Linux ceph 4.15.0-101-generic #102-Ubuntu SMP
* Docker version if applicable (e.g. `docker version`): n/a
* Ansible version (e.g. `ansible-playbook --version`): ansible-playbook 2.9.9
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-5.0
* Ceph version (e.g. `ceph -v`): ceph version 15.2.3 (d289bbdec69ed7c1f516e0a093594580a76b78d0) octopus (stable)
