### ISSUE TITLE
Grafana and Dashboard listening on wrong IP 

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-ansible#5488]
I'm running a ceph 14.2.4 cluster and i want to upgrade to 14.2.10 via rolling_upgrade infrastructure playbook. The Cluster was originally bootstrapped via ceph-ansible stable-4.0 playbook (4.0.4). I updated the playbook to 4.0.25 and adjusted my variables.

The playbook runs without any error, but several (all docker containers) and for example mgr service (dashboard) are listening on the wrong IP:

```
tcp        0      0 172.17.0.1:3000         0.0.0.0:*               LISTEN      472        147814     19813/grafana-serve 
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      0          20348      1435/master         
tcp        0      0 172.17.0.1:8443         0.0.0.0:*               LISTEN      167        151438     14481/ceph-mgr      
tcp        0      0 192.168.26.241:3300     0.0.0.0:*               LISTEN      167        114785     13481/ceph-mon      
tcp        0      0 172.17.0.1:9092         0.0.0.0:*               LISTEN      65534      29428      2064/prometheus     
tcp        0      0 192.168.26.241:6789     0.0.0.0:*               LISTEN      167        114786     13481/ceph-mon      
tcp        0      0 172.17.0.1:9093         0.0.0.0:*               LISTEN      65534      29416      2061/alertmanager   
tcp        0      0 172.17.0.1:9094         0.0.0.0:*               LISTEN      65534      29413      2061/alertmanager   
tcp        0      0 192.168.26.241:6800     0.0.0.0:*               LISTEN      167        151428     14481/ceph-mgr      
tcp        0      0 192.168.26.241:8080     0.0.0.0:*               LISTEN      0          134215     16962/radosgw       
tcp        0      0 192.168.26.241:6801     0.0.0.0:*               LISTEN      167        151430     14481/ceph-mgr  
```

-> 192.168.26.xx is correct
-> 172.17.0.xx is wrong (docker IP)

Because of this, non of the services which are listening on the 172.17.0.xx IP is reachable.

**IP Setup**
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:91:dc:8f brd ff:ff:ff:ff:ff:ff
    inet 192.168.26.241/24 brd 192.168.26.255 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe91:dc8f/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d1:a0:4f:0b brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

**Inventory File**
```
[ceph-mgmt-nodes-dev]
ceph-mon01-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.241
ceph-mon02-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.242 
ceph-mon03-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.243 

[mons:children]
ceph-mgmt-nodes-dev

[mgrs:children]
ceph-mgmt-nodes-dev

[rgws:children]
ceph-mgmt-nodes-dev

[grafana-server]
ceph-mon01-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.241

#[iscsigws]
#ceph-osd01-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.244
#ceph-osd02-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.245 
#ceph-osd03-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.246

[osds:children]
osds-dev-2019-10

[osds-dev-2019-10]
ceph-osd01-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.244 
ceph-osd02-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.245 
ceph-osd03-dev.intern.customer-virt.eu ansible_ssh_host=192.168.26.246 
```

**all.yml**
```
grep -v -e \# -e ^$ group_vars/all.yml
---
dummy:
configure_firewall: False 
ntp_daemon_type: ntpd
upgrade_ceph_packages: False 
ceph_origin: repository
ceph_repository: community 
ceph_mirror: http://download.ceph.com
ceph_stable_key: https://download.ceph.com/keys/release.asc
ceph_stable_release: nautilus 
ceph_stable_repo: "{{ ceph_mirror }}/debian-{{ ceph_stable_release }}"
monitor_interface: ens192 
osd_objectstore: bluestore
radosgw_interface: ens192 
ceph_conf_overrides: 
  osd:
    osd_client_watch_timeout: 15
    osd_heartbeat_grace: 20
    osd_heartbeat_interval: 5
ceph_tcmalloc_max_total_thread_cache: 134217728 
dashboard_admin_password: admin 
grafana_admin_password: admin
grafana_container_memory: 1 
prometheus_container_memory: 1
alertmanager_container_memory: 1 
``` 

As i initially deployed the cluster all services were running on 192.168.xx IPs.

- CentOS 7
- Ansible 2.8.5
- ceph-ansible stable4.0 (4.0.25)

Ansible Run Logfile: https://owncloud.ringerl.de/s/tC9GsDSeYdpdsi5
