### ISSUE TITLE
playbook stuck at ceph-facts : is ceph running already?

### ISSUE THREAD

**Issue by a1git** [ceph/ceph-ansible#5633]
What happened:
ceph-ansible deployment fails. 

What you expected to happen:
the deployment to be successful. 

How to reproduce it (minimal and precise):
I have 3 mons and 3 osd hosts

-----------
HOSTS
-----------
```yaml
[mons]
n1
n2
n3

[osds]
c1
c2
c3

[mgrs]
n1

[grafana-server]
n1
```

----------
OSDS
----------
```yaml
---
dummy:
devices:
  - /dev/vdb
  - /dev/vdc
  - /dev/vdd
```

------
ALL
-----
```yaml
---
dummy:
ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus
cephx: true
monitor_interface: br-storage
ip_version: ipv4
journal_size: 5120 # OSD journal size in MB
cluster_network: 172.29.244.0/22
dashboard_enabled: True
dashboard_admin_user: admin0
dashboard_admin_password: admin0
grafana_admin_user: admin0
grafana_admin_password: admin0
```

----------
MONS
----------
```yaml
---
dummy:
```

the ceph.conf  is present in all the mons ( n1 n2 n3) with the following content. 
--------------------------
[global]
cluster network = 172.29.244.0/22
fsid = 480d75d5-8307-40f5-9f23-c37f721d3055
mon host = [v2:172.29.244.41:3300,v1:172.29.244.41:6789],[v2:172.29.244.42:3300,v1:172.29.244.42:6789]
,[v2:172.29.244.43:3300,v1:172.29.244.43:6789]
mon initial members = n1,n2,n3
osd pool default crush rule = -1
public network = 0.0.0.0/0

--------------------------

ceph-mon is listening to those ports  on n1 n2 and n3 

mon log file in all 3 servers (n1 n2 n3 ) have something like this in their logs

2020-08-05T12:03:12.668+0000 7fd10cd56700  0 -- [v2:10.11.12.43:3300/0,v1:10.11.12.43:6789/0] send_to message mon_probe(probe 480d75d5-8307-40f5-9f23-c37f721d3055 name n3 new mon_release octopus) v7 with empty dest 

The controllers only have this file with the content

cat /etc/ceph/rbdmap 
# RbdDevice		Parameters
#poolname/imagename	id=client,keyring=/etc/ceph/ceph.client.keyring

There is no *ceph* processes or services running in the osd hosts  c1 c2 c3 

------------
OS
------------
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

------------
KERNEL
------------
Linux 4.15.0-112-generic

---------------------------------
ANSIBLE PLAYBOOK
---------------------------------
ansible-playbook 2.9.11

-------------
BRANCH
-------------
stable-5.0

-----------------------
CEPH VERSION
-----------------------
ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
