### ISSUE TITLE
Users Specified `device` Variable Not Works as Expected when Scaling Down OSD

### ISSUE THREAD

**Issue by digglife** [ceph/ceph-ansible#5723]
**Bug Report**

What happened:

1. I deployed a ceph cluster, one of the nodes has 5 OSDs.

    ```yaml
    dedicated_devices:
    - /dev/sdb
    devices:
    - /dev/sdc
    - /dev/sdd
    - /dev/sde
    - /dev/sdf
    - /dev/sdg
    ```

2. I scaled the OSDs on this node down to 3. Delete 2 OSDs with `ceph osd rm`, then changed the relevant `host_var` to the following one.

    ```yaml
    dedicated_devices:
    - /dev/sdb
    devices:
    - /dev/sdc
    - /dev/sdd
    - /dev/sde
    ```
3. Redeployed the cluster. `systemd` services were still created for the OSDs of `sdf` and `sdg` thus the containers were still initialized.

What you expected to happen:

Only 3 OSDs created.

How to reproduce it (minimal and precise):

Just like above mentioned steps.

Share your group_vars files, inventory and **full** ceph-ansibe log

I can't share the full log. But I think I've found the root cause of this issue.

`ceph osd rm` just deletes the OSDs, not the lvm associated with them,
so the OSD ids collected by [`start_osds.yml`](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/start_osds.yml) will not changed at all, all the OSDs created before will be started.

```yaml
- name: systemd start osd
  systemd:
    name: ceph-osd@{{ item }}
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  with_items: "{{ ((ceph_osd_ids.stdout | default('{}') | from_json).keys() | list) + osd_ids_non_container.stdout_lines | default([]) }}"
```

**Environment**:
* OS (e.g. from /etc/os-release): `RHEL 8.1`
* Kernel (e.g. `uname -a`): `4.18.0-147.24.2.el8_1.x86_64`
* Docker version if applicable (e.g. `docker version`): `podman version 1.6.4`
* Ansible version (e.g. `ansible-playbook --version`): `2.8.12`
* ceph-ansible version (e.g. `git head or tag or stable branch`): `4.0.25.2`
* Ceph version (e.g. `ceph -v`): `14.2.4-125.el8cp`
