### ISSUE TITLE
Deploy 15.2.5, health_err: 10 mgr module failed 

### ISSUE THREAD

**Issue by ydw1118** [ceph/ceph-ansible#5811]
**Bug Report**

What happened: 
health_err: 10 mgr module failed

What you expected to happen:

How to reproduce it (minimal and precise):
Deploy version 15.2.5

Share your group_vars files, inventory and **full** ceph-ansibe log

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 8.2.2004 (Core)
* Kernel (e.g. `uname -a`): 4.18.0-193.14.2.el8_2.x86_64
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`): 
ansible 2.9.13
  config file = /root/ceph-ansible/ansible.cfg
  configured module search path = ['/root/ceph-ansible/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-5.0
* Ceph version (e.g. `ceph -v`):  15.2.5

**How to deal with it:**
Downgrade to 15.2.4 is no problem, health ok

**Comment by dsavineau** [comment]
> Share your group_vars files, inventory and **full** ceph-ansibe log

**Comment by dsavineau** [comment]
BTW you're testing 15.2.5 on stable-5.0 brnch in the CI without issue

**Comment by ydw1118** [comment]
> > Share your group_vars files, inventory and **full** ceph-ansibe log

**all.yml**
```yml
---
dummy:
cluster: ceph
configure_firewall: False
centos_package_dependencies:
  - epel-release
  - "{{ 'python3-libselinux' if ansible_distribution_major_version | int >= 8 else 'libselinux-python' }}"
ceph_repository_type: dummy
ceph_origin: repository
ceph_repository: community
ceph_mirror: http://mirrors.aliyun.com/ceph
ceph_stable_key: http://mirrors.aliyun.com/ceph/keys/release.asc
ceph_stable_release: octopus
ceph_stable_repo: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}"
generate_fsid: true
cephx: true
rbd_cache: "true"
rbd_cache_writethrough_until_flush: "true"
rbd_concurrent_management_ops: 20
rbd_client_directories: true # this will create rbd_client_log_path and rbd_client_admin_socket_path directories with proper permissions
ip_version: ipv4
osd_memory_target: 4294967296
block_db_size: -1 # block db size in bytes for the ceph-volume lvm batch. -1 means use the default of 'as big as possible'.
public_network: x.x.1.0/24
cluster_network: x.x.2.0/24
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: bluestore
filestore_xattr_use_omap: null
handler_health_mon_check_retries: 10
handler_health_mon_check_delay: 20
handler_health_osd_check_retries: 40
handler_health_osd_check_delay: 30
handler_health_osd_check: true
handler_health_mgr_check_retries: 5
handler_health_mgr_check_delay: 10
health_mon_check_retries: 20
health_mon_check_delay: 10
health_osd_check_retries: 20
health_osd_check_delay: 10
ceph_conf_overrides:
  global:
    osd_pool_default_min_size: 1
    osd_pool_default_size: 2
  mon:
    mon_allow_pool_delete: true
  mds:
    mds_cache_memory_limit: 6G
  osd:
    osd_max_write_size: 512
    osd_client_message_size_cap: 2147483648
    osd_deep_scrub_stride: 131072
    osd_op_threads: 16
    osd_disk_threads: 4
    osd_map_cache_size: 1024
    osd_map_cache_bl_size: 256
    osd_recovery_op_priority: 4
    osd_recovery_max_active: 16
    osd_max_backfills: 4
    osd_min_pg_log_entries: 30000
    osd_max_pg_log_entries: 100000
    osd_mon_heartbeat_interval: 40
    objecter_inflight_ops: 819200
    osd_op_log_threshold: 50
    osd_scrub_begin_hour: 1
    osd_scrub_end_hour: 5
    osd_op_num_threads_per_shard: 1
    osd_op_num_shards: 16
    osd_pg_object_context_cache_count: 50
    osd_client_message_cap: 5000
    osd_snap_trim_sleep: 1
    osd_pg_max_concurrent_snap_trims: 1
disable_transparent_hugepage: "{{ false if osd_objectstore == 'bluestore' else true }}"
os_tuning_params:
  - { name: fs.file-max, value: 26234859 }
  - { name: vm.zone_reclaim_mode, value: 0 }
  - { name: vm.swappiness, value: 10 }
  - { name: vm.min_free_kbytes, value: "{{ vm_min_free_kbytes }}" }
dashboard_enabled: False
```
---

**inventory**
```hosts
[mons]
h101 monitor_address=x.x.1.101
h102 monitor_address=x.x.1.102
h103 monitor_address=x.x.1.103

[mgrs]
h101
h102
h103


[osds]
h-1 devices="['/dev/sda','/dev/sdb']"
h-2 devices="['/dev/sda','/dev/sdb']"
```

--- 

**full log**
The full deploy log is not saved and can no longer be seen.
