### ISSUE TITLE
ceph-rgw: Pool get the wrong crush rule when rule_name isn't specified

### ISSUE THREAD

**Issue by BenoitKnecht** [ceph/ceph-ansible#5910]
**Bug Report**

What happened:

With `group_vars/rgws.yml` set to

```yaml
rgw_create_pools:
  "{{ rgw_zone }}.rgw.buckets.data":
    type: replicated
    pg_num: 2048
```

and `group_vars/osds.yml` set to

```yaml
crush_rule_config: true

crush_rules:
- name: replicated-default-hdd
  root: default
  type: host
  class: hdd
  default: true
```

`ceph-rgw` changed the crush rule on `default.rgw.buckets.data` from `replicated-default-hdd` to `replicated_rule`, leading the cluster to try and move a lot of objects, and several OSDs to crash in the process.

What you expected to happen:

`ceph-rgw` shouldn't have tried to change the crush rule, or it should have set it to the correct default rule, which is `replicated-default-hdd` in this case.

How to reproduce it (minimal and precise):

Run `ansible-playbook site.yml.sample` with the configuration above.

**Environment**:

* OS (e.g. from /etc/os-release): CentOS 7
* Ansible version (e.g. `ansible-playbook --version`): 2.9.13
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.11

The issue comes from the fact that this task:

https://github.com/ceph/ceph-ansible/blob/765db7ceecf1b75b18c113495673c45c3ae2375e/roles/ceph-rgw/tasks/rgw_create_pools.yml#L63-L74

sets the crush rule to `ceph_osd_pool_default_crush_rule_name` if `rule_name` is unspecified, but that fact is only being set in

https://github.com/ceph/ceph-ansible/blob/765db7ceecf1b75b18c113495673c45c3ae2375e/roles/ceph-facts/tasks/get_def_crush_rule_name.yml#L2-L14

which is not called on the `rgws` hosts. So instead, the default value

https://github.com/ceph/ceph-ansible/blob/765db7ceecf1b75b18c113495673c45c3ae2375e/roles/ceph-defaults/vars/main.yml#L6

ends up being used.

So making sure that `ceph-facts/tasks/get_def_crush_rule_name.yml` gets executed on the `rgws` hosts would fix this issue, but I think it would be much safer to not even try setting the crush rule on the pool unless it's explicitly defined in `crush_rules` as `rule_name`. To me, it would be quite unexpected if Ceph-Ansible tried to change the crush rule on an existing pool just because the default changed, given the huge impact it would have on the cluster.

I would suggest fixing this issue by turning `customize replicated pool crush_rule` into

```yaml
- name: customize replicated pool crush_rule
  command: "{{ container_exec_cmd }} ceph --connect-timeout 10 --cluster {{ cluster }} osd pool set {{ item.key }} crush_rule {{ item.value.rule_name }}"
  register: result
  retries: 60
  delay: 3
  until: result is succeeded
  loop: "{{ rgw_create_pools | dict2items }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  changed_when: false
  when:
    - item.value.type is not defined or item.value.type == 'replicated'
    - item.value.rule_name is defined
```
