### ISSUE TITLE
ceph-facts: Fact osd_pool_default_crush_rule is not set correctly

### ISSUE THREAD

**Issue by BenoitKnecht** [ceph/ceph-ansible#5912]
**Bug Report**

What happened:

After deploying a cluster with `group_vars/osds.yml` set to

```yaml
crush_rule_config: true

crush_rules:
- name: replicated-default-hdd
  root: default
  type: host
  class: hdd
  default: true
```

using `ansible-playbook site.yml.sample`, I noticed that `/etc/ceph/ceph.conf` contained

```ini
[global]
osd pool default crush rule = -1
```

What you expected to happen:

I expected to see

```ini
[global]
osd pool default crush rule = 1
```

since the ID of the `replicated-default-hdd` crush rule is `1`.

How to reproduce it (minimal and precise):

Run `ansible-playbook site.yml.sample` with the configuration above.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Ansible version (e.g. `ansible-playbook --version`): 2.9.13
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable-4.0
* Ceph version (e.g. `ceph -v`): 14.2.11

The issue comes from

https://github.com/ceph/ceph-ansible/blob/765db7ceecf1b75b18c113495673c45c3ae2375e/roles/ceph-facts/tasks/facts.yml#L293-L315

The `get default crush rule value from ceph configuration` task gets the correct value from `/etc/ceph/ceph.conf`, and sets `crush_rule_variable` accordingly. But then `get default crush rule value from running monitor ceph configuration` is skipped, but it still overwrites `crush_rule_variable` with

```yaml
crush_rule_variable:
  changed: false
  skip_reason: Conditional result was False
  skipped: true
```

After that, `set_fact osd_pool_default_crush_rule` sets `osd_pool_default_crush_rule` to `ceph_osd_pool_default_crush_rule` (which is equal to `-1`), since `crush_rule_variable.get('rc', 1)` returns `1`.

And finally, `ceph-config` generates `/etc/ceph/ceph.conf` with that value:

https://github.com/ceph/ceph-ansible/blob/765db7ceecf1b75b18c113495673c45c3ae2375e/roles/ceph-config/templates/ceph.conf.j2#L35
