### ISSUE TITLE
Failure to correctly set admin socket permissions.

### ISSUE THREAD

**Issue by AphidGit** [ceph/ceph-ansible#6058]
**Bug Report**

I intend to configure ceph-ansible to deploy ceph to several bare-metal remote hosts. Deployment, public, and cluster networks are seperate and all machines are reachable over all networks.  All machines are running an unmodified bare installation of ubuntu-server, installed via MAAS. I'm intending to later use this as a backend storage for openstack.

This is a minimal test configuration for ha-ceph, so it has 4 osd machines, 3 of which are to be monitors/managers/etc. as well.  

To install ceph to these machines, I run 

`ansible-playbook site.yml`

The operation stalls after about a minute of succeeding every operation with the following error: 

```
TASK [ceph-mon : waiting for the monitor(s) to form the quorum...] *************************************************************************************************
Wednesday 18 November 2020  15:26:46 +0100 (0:00:00.219)       0:01:52.787 ****
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (10 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (9 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (8 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (7 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (6 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (5 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (4 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (3 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (2 retries left).
FAILED - RETRYING: waiting for the monitor(s) to form the quorum... (1 retries left).
fatal: [st01.hostname.com]: FAILED! => changed=false
  attempts: 10
  cmd:
  - ceph
  - --cluster
  - ceph
  - daemon
  - mon.st01
  - mon_status
  - --format
  - json
  delta: '0:00:00.112282'
  end: '2020-11-18 15:30:09.914318'
  msg: non-zero return code
  rc: 22
  start: '2020-11-18 15:30:09.802036'
  stderr: 'admin_socket: exception getting command descriptions: [Errno 2] No such file or directory'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.mail.CallbackModule object at 0x7fe0b9f1ddc0>): 'in <string>'
requires string as left operand, not int

NO MORE HOSTS LEFT *************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************
st01.hostname.com       : ok=113  changed=11   unreachable=0    failed=1    skipped=201  rescued=0    ignored=0
st02.hostname.com       : ok=96   changed=8    unreachable=0    failed=0    skipped=186  rescued=0    ignored=0
st03.hostname.com       : ok=96   changed=8    unreachable=0    failed=0    skipped=186  rescued=0    ignored=0
st04.hostname.com       : ok=47   changed=3    unreachable=0    failed=0    skipped=112  rescued=0    ignored=0

INSTALLER STATUS 
Install Ceph Monitor           : In Progress (0:04:06)
        This phase can be restarted by running: roles/ceph-mon/tasks/main.yml

Wednesday 18 November 2020  15:30:09 +0100 (0:03:23.882)       0:05:16.670 ****
===============================================================================
ceph-mon : waiting for the monitor(s) to form the quorum... ----------------------------------------------------------------------------------------------- 203.88s
ceph-config : look up for ceph-volume rejected devices ----------------------------------------------------------------------------------------------------- 10.49s
ceph-infra : update cache for Debian based OSs -------------------------------------------------------------------------------------------------------------- 9.16s
gather and delegate facts ----------------------------------------------------------------------------------------------------------------------------------- 7.66s
ceph-validate : get devices information --------------------------------------------------------------------------------------------------------------------- 2.96s
ceph-config : run 'ceph-volume lvm batch --report' to see how many osds are to be created ------------------------------------------------------------------- 2.88s
ceph-validate : read information about the devices ---------------------------------------------------------------------------------------------------------- 2.55s
ceph-infra : enable chronyd --------------------------------------------------------------------------------------------------------------------------------- 2.40s
check for python -------------------------------------------------------------------------------------------------------------------------------------------- 2.34s
ceph-facts : resolve device link(s) ------------------------------------------------------------------------------------------------------------------------- 1.71s
ceph-validate : resolve devices in devices ------------------------------------------------------------------------------------------------------------------ 1.71s
ceph-facts : resolve device link(s) ------------------------------------------------------------------------------------------------------------------------- 1.66s
ceph-common : install ceph for debian ----------------------------------------------------------------------------------------------------------------------- 1.28s
ceph-infra : install chrony --------------------------------------------------------------------------------------------------------------------------------- 1.27s
ceph-facts : check for a ceph mon socket -------------------------------------------------------------------------------------------------------------------- 1.03s
ceph-mon : start the monitor service ------------------------------------------------------------------------------------------------------------------------ 1.02s
ceph-config : generate ceph.conf configuration file --------------------------------------------------------------------------------------------------------- 1.01s
ceph-common : update apt cache if cache_valid_time has expired ---------------------------------------------------------------------------------------------- 0.94s
ceph-common : install dependencies -------------------------------------------------------------------------------------------------------------------------- 0.94s
ceph-infra : disable time sync using timesyncd if we are not using it --------------------------------------------------------------------------------------- 0.92s
Playbook run took 0 days, 0 hours, 5 minutes, 16 seconds
```
### Diagnosis so far

In order to find out what the admin socket is, I run: 
`ceph-conf --name mon.st01 --show-config-value admin_socket`
which returns
`/var/run/ceph/ceph-mon.st01.asok`

The user **ceph** cannot access this file: By editing `/etc/passwd` and giving `ceph` access to `/usr/bin/bash`, I can execute `runuser -l ceph -c 'touch /var/run/ceph/ceph-mon.st01.asok'`. This prints: 

`touch: cannot touch '/var/run/ceph/ceph-mon.st01.asok': Permission denied`

Checking this: `ls -lha /var/run/ | grep ceph` prints 

`drwxr-xr-x  2 libvirt-qemu kvm       40 Nov 17 16:31 ceph`

And `groups ceph` prints 

`ceph : ceph`

So `ceph` does not have permission to write to this directory. This is likely the cause of the error message above: the program cannot create the admin socket file to connect to the other cluster members and halts, which aborts the testing step.

### Workaround

I login to every host separately and execute the following two commands: 

```
usermod -a -G kvm ceph
chmod g+w /var/run/ceph/
```

Theoretically this would completely solve the issue. I suggest adding the user `ceph` to the `kvm` group and modifying permissions on the folder containing the admin socket to allow the group to write.  In my configuration, since openstack will run on separate machines from the storage solution this is irrelevant: no hypervisors are run on the ceph hosts so I used the simple workaround above instead of configuring ACLs. 

Unfortunately, if you now re-run the `ansible-playbook site.yml` command, it will reset this write permission and fail with the same error. 

 As an alternative, You could install `acl` as a prerequisite package nd use ACLs to only give the `ceph` user permission to write to this folder (and still forbid it for members of `kvm` other than `libvirt-qemu`, although it is probably unlikely such a user exists.

### Configuration

Any configuration related to the admin socket is left to the default.  

List of changes made to the group vars (as compared via `diff` to the standard values): 

```
< # Set to the value reported by apt: 
< ceph_release_num: 15
< ceph_origin: distro
< radosgw_num_instances: 2
< openstack_config: true

< dashboard_protocol: https
< dashboard_port: 7481

< ceph_rbd_target_gw_docker_cpu_limit: 2
< ceph_rbd_target_api_docker_cpu_limit: 2
```

Finally, contents of the `hosts` file are: 
```
# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
#
#   - Comments begin with the '#' character
#   - Blank lines are ignored
#   - Groups of hosts are delimited by [header] elements
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups

all:
  hosts:
    # Separate hosts
    st01.hostname.com:
      ansible_ssh_user: deploy
      ansible_sudo_pass: secret
      ansible_ssh_private_key_file: /home/ansible/.ssh/id_st01
    st02.hostname.com:
      ansible_ssh_user: deploy
      ansible_sudo_pass: secret
      ansible_ssh_private_key_file: /home/ansible/.ssh/id_st02
    st03.hostname.com:
      ansible_ssh_user: deploy
      ansible_sudo_pass: secret
      ansible_ssh_private_key_file: /home/ansible/.ssh/id_st03
    st04.hostname.com:
      ansible_ssh_user: deploy
      ansible_sudo_pass: secret
      ansible_ssh_private_key_file: /home/ansible/.ssh/id_st04
  children:
# If you have a group of hosts using a pattern you can specify
# them like this:



#www[001:006].example.com

# Here's another example of host ranges, this time there are no
# leading 0s:

#db-[99:101]-node.example.com

# Ceph Monitor Hosts
# Currently set to the 'storage' network.

    mgrs:
      hosts:
        st01.hostname.com:
        st02.hostname.com:
        st03.hostname.com:
    mdss:
      hosts:
        st01.hostname.com:
        st02.hostname.com:
        st03.hostname.com:
    mons:
      hosts:
        st01.hostname.com:
          monitor_address: 10.1.32.1
        st02.hostname.com:
          monitor_address: 10.1.32.2
        st03.hostname.com:
          monitor_address: 10.1.32.3

# Ceph radosgw hosts
    rgws:
      hosts:
        st01.hostname.com:
          radosgw_address: 10.1.32.1
        st02.hostname.com:
          radosgw_address: 10.1.32.2
        st03.hostname.com:
          radosgw_address: 10.1.32.3
        st04.hostname.com:
          radosgw_address: 10.1.32.4

# Ceph data hosts
# nvme0n2 is a separate journal partition on an SSD drive
    osds:
      hosts:
        st01.hostname.com:
          devices: ['/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh']
          raw_journal_devices: ['/dev/disk/by-label/pjrn1', '/dev/disk/by-label/pjrn2', '/dev/disk/by-label/pjrn3', '/dev/disk/by-label/pjrn4', '/dev/disk/by-label/pjrn5', '/dev/disk/by-label/pjrn6', '/dev/disk/by-label/pjrn7']
          public_network: 10.1.32.1/22
          cluster_network: 10.0.47.1/24
        st02.hostname.com:
          devices: ['/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh']
          raw_journal_devices: ['/dev/disk/by-label/pjrn1', '/dev/disk/by-label/pjrn2', '/dev/disk/by-label/pjrn3', '/dev/disk/by-label/pjrn4', '/dev/disk/by-label/pjrn5', '/dev/disk/by-label/pjrn6', '/dev/disk/by-label/pjrn7']
          public_network: 10.1.32.2/22
          cluster_network: 10.0.47.2/24
        st03.hostname.com:
          devices: ['/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg']
          raw_journal_devices: ['/dev/disk/by-label/pjrn1', '/dev/disk/by-label/pjrn2', '/dev/disk/by-label/pjrn3', '/dev/disk/by-label/pjrn4', '/dev/disk/by-label/pjrn5', '/dev/disk/by-label/pjrn6']
          public_network: 10.1.32.3/22
          cluster_network: 10.0.47.3/24
        st04.hostname.com:
          devices: ['/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh']
          raw_journal_devices: ['/dev/disk/by-label/pjrn1', '/dev/disk/by-label/pjrn2', '/dev/disk/by-label/pjrn3', '/dev/disk/by-label/pjrn4', '/dev/disk/by-label/pjrn5', '/dev/disk/by-label/pjrn6', '/dev/disk/by-label/pjrn7']
          public_network: 10.1.32.4/22
          cluster_network: 10.0.47.4/24

# ISCSI gateways for CEPH Datastores
#    iscsigws:
#      hosts:
#        st01.hostname.com:
#        st02.hostname.com:
#        st03.hostname.com:
```

Note that here, the `by-label` accesses are partitions on a fast ssd disk. This disk is split into 7 equally sized partitions for use as journals, a fast cache for the larger and slower spinning drives making up the cluster. Each host has a `deploy` user. _Note: In all examples,  hostnames and passwords are excluded for security reasons._ 

There are some other changes related to `iscsigws`, but since `ceph-ansible` reports this isn't supported via ansible on ubuntu, these are not relevant (I've commented out the `[iscsigws]` section of the `hosts` file, so it should not run this playbook. 

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS
* Kernel (e.g. `uname -a`): 5.4.0-52
* Docker version if applicable (e.g. `docker version`): Not applicable
* Ansible version (e.g. `ansible-playbook --version`): 2.9.6 
* ceph-ansible version (e.g. `git head or tag or stable branch`): stable 5.0 (latest, for ansible 2.9).
* Ceph version (e.g. `ceph -v`): As installed by ceph-ansible, 15.2.3 (although the process does not fully complete: the installation is what fails. It may still need to update further).
