### ISSUE TITLE
Unable to add OSDs to an existing cluster

### ISSUE THREAD

**Issue by micmoyles** [ceph/ceph-ansible#6120]
Sorry for being a bit misleading here, I am trying to understand the intended vs observed behaviour of `ceph-ansible` and `ceph-volume` while I add OSDs to an existing cluster, so this may not strictly be a bug report. I appreciate `ceph-volume` is not part of the `ceph-ansible` project.

**Bug Report**

What happened:

I built my OSD nodes with a mix of SSD and HDD devices, I have now plugged in an additional HDD to each node, updated my group_vars to reflect this and re-ran ansible. The error received is 
```
fatal: [ixcephosd04]: FAILED! => {"changed": true, "cmd": ["ceph-volume", "--cluster", "ceph", "lvm", "batch", "--bluestore", "--yes", "/dev/sdc", "/dev/sdd", "/dev/sde", "/dev/sdf", "/dev/sdg", "/dev/sdh", "/dev/sdi", "/dev/sdj", "/dev/sdk", "/dev/sdl", "/dev/sdm", "/dev/sdn", "--report", "--format=json"], "msg": "non-zero return code", "rc": 1, "stderr": "--> Aborting because strategy changed from bluestore.MixedType to bluestore.SingleType after filtering", "stderr_lines": ["--> Aborting because strategy changed from bluestore.MixedType to bluestore.SingleType after filtering"], "stdout": "", 
```
I am aware this is produced by `ceph-volume`. From reading through some other issues (https://github.com/ceph/ceph-ansible/issues/4748, https://github.com/ceph/ceph-ansible/issues/4855) I believe the error is produced because the original setup generated OSDs on two device classes and now is attempting to create OSDs on a single device class (just HDD).

What you expected to happen:

I expected `ceph-ansible` to support adding a new OSD of either device class after a cluster is operational. Is this correct or not? And can you tell me if my understanding of the issue I am facing is correct?

If the intended behaviour of `ceph-ansible` is to exit at the error response of `ceph-volume` rather than detect a diff and create new OSDs, then this is fine for me and I can work something into my internal ansible roles to manage this. 

How to reproduce it (minimal and precise):

Create a cluster with mixed OSD devices, then try add a single new device.

Share your group_vars files, inventory and **full** ceph-ansibe log
OSD group vars. The new device is /dev/sdn and the LVM for block-db has been created on the machine.
```
bluestore_wal_device: /dev/md0
ceph_devices_bluestore_volume_group: block-db
lvm_volumes:
  - data: /dev/sdc
    db: "{{ ceph_devices_bluestore_volume_group }}-sdc"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdd
    db: "{{ ceph_devices_bluestore_volume_group }}-sdd"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sde
    db: "{{ ceph_devices_bluestore_volume_group }}-sde"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdf
    db: "{{ ceph_devices_bluestore_volume_group }}-sdf"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdg
    db: "{{ ceph_devices_bluestore_volume_group }}-sdg"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdh
    db: "{{ ceph_devices_bluestore_volume_group }}-sdh"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdi
    db: "{{ ceph_devices_bluestore_volume_group }}-sdi"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdj
    db: "{{ ceph_devices_bluestore_volume_group }}-sdj"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdk
    db: "{{ ceph_devices_bluestore_volume_group }}-sdk"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdl
    db: "{{ ceph_devices_bluestore_volume_group }}-sdl"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdm
    db: "{{ ceph_devices_bluestore_volume_group }}-sdm"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
  - data: /dev/sdn
    db: "{{ ceph_devices_bluestore_volume_group }}-sdn"
    db_vg: "{{ ceph_devices_bluestore_volume_group }}"
```
**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```
* Kernel (e.g. `uname -a`):
```
Linux ixcephosd02 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* Ansible version (e.g. `ansible-playbook --version`):
```
2.9.10
```
* ceph-ansible version (e.g. `git head or tag or stable branch`):
```
stable-5.0 (forked internally with a few patches required by my org)
```
* Ceph version (e.g. `ceph -v`):
```
ceph version 15.2.5 (2c93eff00150f0cc5f106a559557a58d3d7b6f1f) octopus (stable)
```
