### ISSUE TITLE
install failure on centos7

### ISSUE THREAD

**Issue by dpkshetty** [ceph/ceph-ansible#616]
I set ceph_origin to 'distro' and my ceph node is CentOS7, and install task fails as below ...

```
TASK: [ceph.ceph-common | install distro or red hat storage ceph mon] ********* 
failed: [ceph-node1] => (item=ceph,ceph-mon) => {"changed": false, "failed": true, "item": "ceph,ceph-mon", "rc": 0, "results": ["ceph-0.80.7-0.7.el7.x86_64 providing ceph is already installed"]}
msg: No Package matching 'ceph-mon' found available, installed or updated

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/site.retry

ceph-node1                 : ok=16   changed=2    unreachable=0    failed=1   
```

Digging further I see that it fails because it tries to install ceph-mon package, which isn't there in the CentOS and epel repos

Looking even further, it seems like we don't need to install ceph-mon, since the ceph package installed from epel repo has ceph-mon, ceph-osd binaries, but the failing task (as below) is trying to install ceph-mon ( and ceph-osd later on...) package ...

```
- name: install distro or red hat storage ceph mon
  yum:
    name: "{{ item }}"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  with_items:
    - ceph
    - ceph-mon
  when:
    (ceph_origin == "distro" or ceph_stable_rh_storage) and
    mon_group_name in group_names and
    ansible_pkg_mgr == "yum"
```

From my ceph-node1 ...

```
[root@ceph-node1 ~]# ls /usr/bin/cep*
/usr/bin/ceph           /usr/bin/ceph-client-debug  /usr/bin/ceph-coverage        /usr/bin/ceph-dencoder  /usr/bin/ceph-mon                  /usr/bin/ceph-post-file  /usr/bin/ceph-run
/usr/bin/ceph-authtool  /usr/bin/ceph-clsinfo       /usr/bin/ceph-crush-location  /usr/bin/cephfs         /usr/bin/ceph_mon_store_converter  /usr/bin/ceph-rbdnamer   /usr/bin/ceph-syn
/usr/bin/ceph-brag      /usr/bin/ceph-conf          /usr/bin/ceph-debugpack       /usr/bin/ceph-mds       /usr/bin/ceph-osd                  /usr/bin/ceph-rest-api

[root@ceph-node1 ~]# ls /etc/yum.repos.d/
CentOS-Base.repo  CentOS-CR.repo  CentOS-Debuginfo.repo  CentOS-fasttrack.repo  CentOS-Media.repo  CentOS-Sources.repo  CentOS-Vault.repo  epel.repo  epel-testing.repo

[root@ceph-node1 ~]# rpm -qf /usr/bin/ceph-mon 
ceph-0.80.7-0.7.el7.x86_64

[root@ceph-node1 ~]# rpm -qf /usr/bin/ceph-osd
ceph-0.80.7-0.7.el7.x86_64

[root@ceph-node1 ~]# 

```
