### ISSUE TITLE
Adding a node fails using --limit.

### ISSUE THREAD

**Issue by AphidGit** [ceph/ceph-ansible#6161]
**Bug Report**

What happened:

Ceph-ansible fails to add a node when run as suggested by the manual using the `--limit` option. Not using this option does not run into this problem. 

How to reproduce it (minimal and precise):

Try to add another node to an existing, running ceph cluster. 
To do so, the suggested procedure is to:
1. Edit the 'hosts' file to include this new node (as osd, mon, mgr, etc... the things you want to run on it).
2. Install the prerequisites on this host (ansible/deploy user with sudo access and an SSH key installed on the ansible host, bash, ssh, python2, python3).
3. Verify network connectivity.
4. Run the playbook using the "limit" option like so:

`ansible-playbook site.yml --limit newnode.mysite.com`

As instructed by https://docs.ceph.com/projects/ceph-ansible/en/latest/day-2/osds.html#:~:text=Adding%20new%20OSD(s)%20on,new%20osd%20nodes%20being%20added.

What you expected to happen:

This installs the chosen ceph components on the new host.

What actually happens: 

This fails with the message that `discovered_interpreter_python` cannot be found in `ansible.vars.hostvars.hostvarvars` for the step ` get current fsid if cluster is already running`. The problem file is the script `/ceph/ceph-ansible/roles/ceph-facts/tasks/facts.yml`, line 155. 

The code in question: 

```
- name: fsid related tasks
  when:
    - generate_fsid | bool
    - current_fsid.rc != 0
    - not rolling_update | bool
  block:
    - name: generate cluster fsid
      command: "{{ hostvars[groups[mon_group_name][0]]['discovered_interpreter_python'] }} -c 'import uuid; print(str(uuid.uuid4()))'"
      register: cluster_uuid
      delegate_to: "{{ groups[mon_group_name][0] }}"
      run_once: true
    - name: set_fact fsid
      set_fact:
        fsid: "{{ cluster_uuid.stdout }}"
```

Apparently ceph-ansible tries to access this variable even for hosts that are not the `--limit` ed host, failing to run the script when trying to expand the cluster. Not using the `--limit` option gets around this issue, but is inefficient. There are two reasons when you have a large cluster: 

- The sheer amount of time it takes to all the checks; disks may fail faster than this. 
- The fact that a large cluster may have failed disks/nodes all the time. Running the full `site.yml` from ceph-ansible will break and abort if even one disk or node cannot be reached. 

Either there is some bug that this no longer works or the manual is out of date. What's the proper way of adding a node? Note: the manual also suddenly assumes docker is there (it references `site-container.yml` instead of `site.yml`), so that might have something to do with it not working for the other one. But there's no command or syntax on how to do this simple task with the regular (non-dockerized) version. 

Version/config info: 

OS: Ubuntu 20.04 LTS
Version: Stable
Ceph version: From OS-repo, latest stable. 
Current configuration: Bug is independent of this (as long as there's a working ansible-configured ceph cluster, it will happen).
