### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by n27051538** [ceph/ceph-ansible#6182]
I tried to make Ceph installation on systems behind the proxy without direct access to internet and had problems on CentOS7.

**Describe the solution you'd like**
I have edited playbook a little for proxy support:

in inventory/group_vars/all.yml I have added two vars
```
http_proxy: http://proxy.example.com:3128
https_proxy: http://proxy.example.com:3128
```
and I edited downloaded playbook (I used branch stable-3.2 with luminous):

```
# cat roles/ceph.ceph-common/tasks/installs/redhat_community_repository.yml
---
- name: configure red hat ceph community repository stable key
  rpm_key:
    key: "{{ ceph_stable_key }}"
    state: present
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"

- name: configure red hat ceph stable community repository
  yum_repository:
    name: ceph_stable
    description: Ceph Stable repo
    gpgcheck: yes
    state: present
    gpgkey: "{{ ceph_stable_key }}"
    baseurl: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}/{{ ceph_stable_redhat_distro }}/$basearch"
    proxy: "{{ https_proxy | default('_none_') }}"
```

I added environment in the first task and proxy in the second task.
Please add support for systems behind the proxy, I believe that I am not unique person who needs this.
