### ISSUE TITLE
ceph-ansible(5.0) mix hdd and ssd

### ISSUE THREAD

**Issue by Auggie321** [ceph/ceph-ansible#6318]
Sir, 
 
I'm very sorry, I don't know if it's appropriate to mention this issue here, 
it's been bothering me for two or three days without a solution.
```
Test environment.
1. Three node bare metal server build ceph cluster, each server has 128G RAM, 48 cores
2. Each server has two 300G SAS HDD made raid1.
3. ssd 480G, and three 3T HDD, each HDD is a separate raid 0.

root@ceph1 ~/ceph-ansible/group_vars (origin/stable-5.0) $ lsblk
NAME                      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
*****************
sda                         8:0    0 278.9G  0 disk 
*****************
└─sda3                      8:3    0 277.9G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0   271G  0 lvm  /
sdb                         8:16   0 446.6G  0 disk 
sdc                         8:32   0   3.7T  0 disk 
sdd                         8:48   0   3.7T  0 disk 
sde                         8:64   0   3.7T  0 disk 

ceph-ansible(5.0)====>ceph version 15.2.8 octopus (stable)
````

Purpose
1. openstack data(vms. images, cinder, nova,xxx) <--------------> ceph ssd<-------------------->ceph hdd

2. How can I configure the configuration file of ceph-ansible to optimize the use of bare metal server memory and CPU resources without wasting them?

3. Checked, ceph-ansible issues https://github.com/ceph/ceph-ansible/issues/2435
But not sure how osds.yml would be better configured?

**Comment by Auggie321** [comment]
change title

**Comment by dsavineau** [comment]
This isn't clear to me what you try to achieve.

Do you need to have some pools on SSD and other on HDD ?

If the answer is yes then you need to create the OSD as following (in osds.yml)

```yaml
devices:
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
lvm_volumes:
  - data: /dev/sdb
```

The reason for not including the SSD (/dev/sdb) in the `devices` variable is related to ceph-volume lvm batch command that will automatically put the bluestore DB on the SSD devices and bluestore data on HDD in a mixed scenario.
Here you want the SSD devices as OSD.

With this configuration you will have two different device class created automatically (from the device type detection)
  - hdd
  - ssd

Then you can use those device class to create specific crush rules and applied them to pools (in osds.yml)

```yaml
crush_rule_config: true
crush_rule_hdd:
  name: HDD
  root: default
  type: host
  class: hdd
  default: true
crush_rule_ssd:
  name: SSD
  root: default
  type: host
  class: ssd
  default: false
crush_rules:
  - "{{ crush_rule_hdd }}"
  - "{{ crush_rule_ssd }}
```

Finally when you defined your pools via the `openstack_pools` variable you need to associated the right crush rule name (in all.yml)

```yaml
openstack_config: true
openstack_glance_pool:
  name: "images"
  application: "rbd"
  rule_nam: HDD
openstack_cinder_pool:
  name: "volumes"
  application: "rbd"
  rule_nam: SDD
openstack_nova_pool:
  name: "vms"
  application: "rbd"
  rule_nam: HDD
openstack_pools:
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_nova_pool }}"
```

This will configured the nova and glance pools on the HDD devices and the cinder pool on the SSD devices.

**Comment by Auggie321** [comment]
![openstack-ceph](https://user-images.githubusercontent.com/34760807/112287095-f5316380-8cc6-11eb-86fa-db73a946f0be.png)

**Comment by Auggie321** [comment]
openstack internal cinder-nova (volumes, vms, backups pool) for read and write frequency will be very high, 
the remaining glance (images pools) read and write requirements are relatively low; 
and images pool is not used frequently, 
all go ceph ssd pool cache and then to hdd pool, the impact should not be very large.
So consider openstack all the corresponding pools (volumes, vms, backups, images pool) into ssd pool cache first, 
and then into hdd pool;

default  ceph octopus osd pg_num autoscale is enable, for the pool settings consider manually create; use ceph-ansible can also, but need to disable ceph osd pg_num autoscale; otherwise the creation of the end will appear reblance problems.

**Comment by dsavineau** [comment]
So what you're looking for is a cache tiering setup which isn't supported by ceph-ansible.

I would recommand you to read [1] if it's not already done.

You can cover some part of this via ceph-ansible like
- crush rules creation
- pools creation

But the cache tiering command would need to be executed manually (to assigned the cache pool to the other pool on hdd)

This could be somehting like:

osds.yml
```yaml
lvm_volumes:
  - data: /dev/sdb
  - data: /dev/sdc
  - data: /dev/sdd
  - data: /dev/sde
crush_rule_config: true
crush_rule_hdd:
  name: HDD
  root: default
  type: host
  class: hdd
  default: true
crush_rule_ssd:
  name: SSD
  root: default
  type: host
  class: ssd
  default: false
crush_rules:
  - "{{ crush_rule_hdd }}"
  - "{{ crush_rule_ssd }}
```
all.yml
```yaml
openstack_config: true
openstack_glance_pool:
  name: "images"
  application: "rbd"
  rule_nam: HDD
openstack_cinder_pool:
  name: "volumes"
  application: "rbd"
  rule_nam: HDD
openstack_nova_pool:
  name: "vms"
  application: "rbd"
  rule_nam: HDD
openstack_cache_pool:
  name: "cache"
  application: "rbd"
  rule_nam: SSD
(...)
openstack_pools:
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_nova_pool }}"
  - "{{ openstack_cache_pool }}"
  - (...)
```

And after the ceph-ansible execution:
```console
$ ceph osd tier add cache vms
$ ceph osd tier add cache images
$ ceph osd tier add cache volumes
(...)
```


[1] https://docs.ceph.com/en/latest/rados/operations/cache-tiering/
