### ISSUE TITLE
How to use custom repository to install CEPH nautilus 

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-ansible#6358]
Can someone please guide to setup custom repository  to install cluster.

**Comment by dsavineau** [comment]
```yaml
ceph_origin: repository
ceph_repository: custom
ceph_custom_key: https://foo.io/ceph/key.asc
ceph_custom_repo: https://bar.io/ceph/nautilus/
```

https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L135
https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.yml.sample#L212-L221
