### ISSUE TITLE
Why remove infrastructure-playbooks/add-osd.yml

### ISSUE THREAD

**Issue by rongzhen-zhan** [ceph/ceph-ansible#6482]
In our host ,there are 8 nvme and 6 Spinning disk. Each 3 spinning disk occupy one nvme for db device，The remaining NVME is treated as an OSD (db and data).so I need to deploy it twice.
The first all.yml as below:
```yaml
osd_objectstore: bluestore
lvm_volumes:
  - data: ceph-hdd-lv-sda
    data_vg: ceph-hdd-vg-sda
    db: ceph-journal-sda
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdb
    data_vg: ceph-hdd-vg-sdb
    db: ceph-journal-sdb
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdc
    data_vg: ceph-hdd-vg-sdc
    db: ceph-journal-sdc
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdd
    data_vg: ceph-hdd-vg-sdd
    db: ceph-journal-sdd
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sde
    data_vg: ceph-hdd-vg-sde
    db: ceph-journal-sde
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdf
    data_vg: ceph-hdd-vg-sdf
    db: ceph-journal-sdf
    db_vg: ceph-nvme-vg-nvme1n1
```

The second all.yml al bebow:
```yaml
osd_objectstore: bluestore
lvm_volumes:
  - data: /dev/nvme2n1
  - data: /dev/nvme3n1
  - data: /dev/nvme4n1
  - data: /dev/nvme5n1
  - data: /dev/nvme6n1
  - data: /dev/nvme7n1
```

In this case, add-osd.yml is needed, isn't it?

**Comment by dsavineau** [comment]
> In this case, add-osd.yml is needed, isn't it?

I don't understand why you need to deploy the OSD in 2 steps. You can achieve this with a single configuration.

```yaml
osd_objectstore: bluestore
lvm_volumes:
  - data: ceph-hdd-lv-sda
    data_vg: ceph-hdd-vg-sda
    db: ceph-journal-sda
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdb
    data_vg: ceph-hdd-vg-sdb
    db: ceph-journal-sdb
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdc
    data_vg: ceph-hdd-vg-sdc
    db: ceph-journal-sdc
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdd
    data_vg: ceph-hdd-vg-sdd
    db: ceph-journal-sdd
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sde
    data_vg: ceph-hdd-vg-sde
    db: ceph-journal-sde
    db_vg: ceph-nvme-vg-nvme1n1
  - data: ceph-hdd-lv-sdf
    data_vg: ceph-hdd-vg-sdf
    db: ceph-journal-sdf
    db_vg: ceph-nvme-vg-nvme1n1
  - data: /dev/nvme2n1
  - data: /dev/nvme3n1
  - data: /dev/nvme4n1
  - data: /dev/nvme5n1
  - data: /dev/nvme6n1
  - data: /dev/nvme7n1
```

BTW you can also do the same (unless you're doing something specific on your own) by using the lvm batch setup for deploying the OSD on HDD/NVMe

```yaml
osd_objectstore: bluestore
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/nvme1n1
lvm_volumes:
  - data: /dev/nvme2n1
  - data: /dev/nvme3n1
  - data: /dev/nvme4n1
  - data: /dev/nvme5n1
  - data: /dev/nvme6n1
  - data: /dev/nvme7n1
```

This is the ceph-volume lvm batch implicit configuration (via `devices`) that will deploy the OSD data on HDD and the bluestore DB on the NVMe device. This will avoid to create the VG and LV manually prior the deployement.
You can also do the same with an explicit configuration.

```yaml
osd_objectstore: bluestore
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
dedicated_devices:
  - /dev/nvme1n1
lvm_volumes:
  - data: /dev/nvme2n1
  - data: /dev/nvme3n1
  - data: /dev/nvme4n1
  - data: /dev/nvme5n1
  - data: /dev/nvme6n1
  - data: /dev/nvme7n1
```

https://docs.ceph.com/projects/ceph-ansible/en/latest/osds/scenarios.html#lvm

About the add-osd.yml playbook removal, you can achieve the same with the main playbook and `--limit` ansible option.

https://docs.ceph.com/projects/ceph-ansible/en/latest/day-2/osds.html#adding-osd-s
