### ISSUE TITLE
How to use clients.yml for provision

### ISSUE THREAD

**Issue by poul1x** [ceph/ceph-ansible#6515]
I uncommented contents of [clients.yml](https://github.com/ceph/ceph-ansible/blob/master/group_vars/clients.yml.sample) and expected to see created pools after ceph deploy. But they weren't created.

How can I activate `clients.yml` to have pools ready for provision?

**Comment by dsavineau** [comment]
Could you share the clients.yml content ?

The important thing to not forget is to set `user_config: true` because the default value is false.
Otherwise even if you defined pools in this file then they won't be created.

**Comment by dsavineau** [comment]
As an example:

```yaml
user_config: true
pools:
  - name: foo
    application: rbd
  - name: bar
    application: cephfs
```

**Comment by poul1x** [comment]
Worked well, thanks!

**Comment by poul1x** [comment]
Consider better template for keys:

```yaml
keys:
  - name: client.agentfs
    key: "{{ lookup('file', 'client.agentfs.keyring') }}"
    mode: "{{ ceph_keyring_permissions }}"
    caps:
      mon: "allow r"
      mgr: "allow rw"
      mds: "allow rws"
      osd: "allow rw pool=fs-agent-data, allow rw pool=fs-agent-meta"
  - name: client.prometheus
    key: "{{ lookup('file', 'client.prometheus.keyring') }}"
    mode: "{{ ceph_keyring_permissions }}"
    caps:
      mon: "profile rbd"
      osd: "allow class-read object_prefix rbd_children, profile rbd pool=prometheus"
  - name: client.grafana
    key: "{{ lookup('file', 'client.grafana.keyring') }}"
    mode: "{{ ceph_keyring_permissions }}"
    caps:
      mon: "profile rbd"
      osd: "allow class-read object_prefix rbd_children, profile rbd pool=grafana"
```
VS
```yaml
#keys:
#  - { name: client.test, caps: { mon: "profile rbd", osd: "allow class-read object_prefix rbd_children, profile rbd pool=test" },  mode: "{{ ceph_keyring_permissions }}" }
#  - { name: client.test2, caps: { mon: "profile rbd", osd: "allow class-read object_prefix rbd_children, profile rbd pool=test2" },  mode: "{{ ceph_keyring_permissions }}" }
```

I think, mine is more readable
