### ISSUE TITLE
RGW `pg_autoscale_mode` is ignored during ceph deploy

### ISSUE THREAD

**Issue by poul1x** [ceph/ceph-ansible#6516]
**Bug Report**

What happened:

I set `pg_autoscale_mode: "off"` field in `rgws.yaml`.

```yaml
rgw_create_pools:
  ".rgw.root":
    type: replicated
    pg_autoscale_mode: "off"
    pg_num: 4
    pgp_num: 4
    size: 3
  "{{ rgw_zone }}.rgw.buckets.index":
    type: replicated
    pg_autoscale_mode: "off"
    pg_num: 4
    pgp_num: 4
    size: 3
  "{{ rgw_zone }}.rgw.meta":
    type: replicated
    pg_autoscale_mode: "off"
    pg_num: 4
    pgp_num: 4
    size: 3
  "{{ rgw_zone }}.rgw.log":
    type: replicated
    pg_autoscale_mode: "off"
    pg_num: 4
    pgp_num: 4
    size: 3
  "{{ rgw_zone }}.rgw.control":
    type: replicated
    pg_autoscale_mode: "off"
    pg_num: 4
    pgp_num: 4
    size: 3
  "{{ rgw_zone }}.rgw.buckets.data":
    type: replicated
    pg_autoscale_mode: "off"
    pg_num: 64
    pgp_num: 64
    size: 3 
```

But when ceph has been deployed `pg_autoscale_mode` was `on`.

What you expected to happen:

- `pg_autoscale_mode` is `off`.
- `pg_num`  and `pgp_num` have values that I set manually

**Bug found**:

Then, I inspected the sources and found two missprints:

https://github.com/ceph/ceph-ansible/blob/stable-6.0/roles/ceph-rgw/tasks/rgw_create_pools.yml#L63
https://github.com/ceph/ceph-ansible/blob/stable-6.0/roles/ceph-rgw/tasks/rgw_create_pools.yml#L40

After I set `pg_autoscale_mode: "{{ item.value.pg_autoscale_mode | default(omit) }}"` it worked well:

```
# ceph osd dump
...
pool 4 '.rgw.root' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 4 pgp_num 4 autoscale_mode off last_change 21 flags hashpspool stripe_width 0 application rgw
pool 5 'default.rgw.buckets.index' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 4 pgp_num 4 autoscale_mode off last_change 24 flags hashpspool stripe_width 0 application rgw
pool 6 'default.rgw.meta' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 4 pgp_num 4 autoscale_mode off last_change 27 flags hashpspool stripe_width 0 application rgw
pool 7 'default.rgw.log' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 4 pgp_num 4 autoscale_mode off last_change 30 flags hashpspool stripe_width 0 application rgw
pool 8 'default.rgw.control' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 4 pgp_num 4 autoscale_mode off last_change 32 flags hashpspool stripe_width 0 application rgw
pool 9 'default.rgw.buckets.data' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 64 pgp_num 64 autoscale_mode off last_change 35 flags hashpspool stripe_width 0 application rgw
max_osd 3
...
```

**Environment**:
* ceph-ansible version (e.g. `git head or tag or stable branch`):  stable-6.0
