### ISSUE TITLE
ceph-ansible stable-4.0 install fails with msg: '''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_hostname'''

### ISSUE THREAD

**Issue by AlbertBraden** [ceph/ceph-ansible#6579]
1. For issues or feature requests, please create an issue in this repository.
2. Did you already search the existing open issues for anything similar? -->

**Bug Report**

What happened:

Ansible playbook failed:
```
TASK [ceph-config : generate ceph.conf configuration file] **********************************************************************************************************************************************************************************
Thursday 10 June 2021  20:25:43 +0000 (0:00:00.286)       0:00:58.663 *********
[DEPRECATION WARNING]: set_available_variables is being deprecated. Use "@available_variables.setter" instead.. This feature will be removed in version 2.13. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
[DEPRECATION WARNING]: set_available_variables is being deprecated. Use "@available_variables.setter" instead.. This feature will be removed in version 2.13. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
[DEPRECATION WARNING]: set_available_variables is being deprecated. Use "@available_variables.setter" instead.. This feature will be removed in version 2.13. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
fatal: [192.168.0.31]: FAILED! =>
  msg: '''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_hostname'''
fatal: [192.168.0.32]: FAILED! =>
  msg: '''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_hostname'''
fatal: [192.168.0.33]: FAILED! =>
  msg: '''ansible.vars.hostvars.HostVarsVars object'' has no attribute ''ansible_hostname'''

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
192.168.0.21               : ok=33   changed=0    unreachable=0    failed=0    skipped=99   rescued=0    ignored=0
192.168.0.22               : ok=33   changed=0    unreachable=0    failed=0    skipped=99   rescued=0    ignored=0
192.168.0.23               : ok=33   changed=0    unreachable=0    failed=0    skipped=99   rescued=0    ignored=0
192.168.0.31               : ok=92   changed=0    unreachable=0    failed=1    skipped=219  rescued=0    ignored=0
192.168.0.32               : ok=78   changed=0    unreachable=0    failed=1    skipped=203  rescued=0    ignored=0
192.168.0.33               : ok=78   changed=0    unreachable=0    failed=1    skipped=203  rescued=0    ignored=0
```

What you expected to happen:

Playbook completes without error

How to reproduce it (minimal and precise):

Download and install:
```console
cd /opt/ceph
. bin/activate
git clone https://github.com/ceph/ceph-ansible.git
cd ceph-ansible
git checkout stable-4.0
pip install -r requirements.txt
```

Copy saved config that worked a few months ago:
```console
rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p2222" -a localhost:/root/save_area51/opt/ceph/ceph-ansible/group_vars/all.yml /opt/ceph/ceph-ansible/group_vars/all.yml
rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p2222" -a localhost:/root/save_area51/opt/ceph/ceph-ansible/group_vars/osds.yml /opt/ceph/ceph-ansible/group_vars/osds.yml
rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p2222" -a localhost:/root/save_area51/opt/ceph/inventory /opt/ceph/inventory
```

Run ansible:
```console
cd /opt/ceph/ceph-ansible/
ansible-playbook -i ../inventory site.yml
```

Share your group_vars files, inventory and **full** ceph-ansibe log

(ceph) [root@chnrc-area51-os-build ceph-ansible]# cat ../inventory
```ini
[mons]
192.168.0.[31:33]

[rgws]
192.168.0.[31:33]

[mgrs]
192.168.0.[31:33]

[osds]
192.168.0.[21:23]
```

(ceph) [root@chnrc-area51-os-build ceph-ansible]# cat group_vars/osds.yml|grep -v ^#|grep -v ^$
```yaml
---
dummy:
osd_scenario: lvm
osd_objectstore: bluestore
osds_per_device: 1
devices:
  - /dev/nvme0n1
  - /dev/nvme1n1
  - /dev/nvme2n1
  - /dev/nvme3n1
  - /dev/nvme4n1
  - /dev/nvme5n1
  - /dev/nvme6n1
  - /dev/nvme7n1
  - /dev/nvme8n1
  - /dev/nvme9n1
```

(ceph) [root@chnrc-area51-os-build ceph-ansible]# cat group_vars/all.yml|grep -v ^#|grep -v ^$
```yaml
---
dummy:
fetch_directory: fetch/
cluster: ceph
configure_firewall: no
ceph_conf_local: yes
ntp_service_enabled: no
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: nautilus
fsid: ae9b8b53-e015-461d-a413-6ca579e25602
generate_fsid: no
ceph_conf_key_directory: /etc/ceph
cephx: true
monitor_interface: bond0.102
monitor_address_block: 192.168.2.0/23
public_network: 192.168.2.0/23
cluster_network: 192.168.4.0/23
osd_objectstore: bluestore
radosgw_interface: bond0.102
ceph_conf_overrides_rgw: &rgw_config
  "rgw keystone api version": 3
  "rgw keystone url": "http://192.168.0.10:35357"
  "rgw keystone admin user": "admin"
  "rgw keystone admin password": "XUgJ1rC3mcAz7AOVTyztdUyR3umosyUYghplqSjd"
  "rgw keystone admin tenant": "admin"
  "rgw keystone admin domain": "Default"
  "rgw keystone accepted roles": "admin,swiftoperator"
  "rgw keystone token cache size": 10
  "rgw keystone revocation interval": 0
  "rgw keystone make new tenants": "true"
  "rgw keystone implicit tenants": "true"
  "rgw swift account in url": "true"
  "rgw user default quota max size": "1G"
  "rgw user default quota max objects": "1000"
ceph_conf_overrides:
  "client.rgw.{{ hostvars[groups.get(rgw_group_name)[0]]['ansible_hostname'] }}.rgw0": *rgw_config
  "client.rgw.{{ hostvars[groups.get(rgw_group_name)[1]]['ansible_hostname'] }}.rgw0": *rgw_config
  "client.rgw.{{ hostvars[groups.get(rgw_group_name)[2]]['ansible_hostname'] }}.rgw0": *rgw_config
openstack_config: yes
openstack_glance_pool:
  name: "images"
  pg_num: 128
  pgp_num: 128
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_cinder_pool:
  name: "volumes"
  pg_num: 1024
  pgp_num: 1024
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_nova_pool:
  name: "vms"
  pg_num: 256
  pgp_num: 256
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_cinder_backup_pool:
  name: "backups"
  pg_num: 256
  pgp_num: 256
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_gnocchi_pool:
  name: "metrics"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_cephfs_data_pool:
  name: "manila_data"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_cephfs_metadata_pool:
  name: "manila_metadata"
  pg_num: "{{ osd_pool_default_pg_num }}"
  pgp_num: "{{ osd_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "{{ osd_pool_default_size }}"
  min_size: "{{ osd_pool_default_min_size }}"
openstack_pools:
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_nova_pool }}"
  - "{{ openstack_cinder_backup_pool }}"
openstack_keys:
  - name: client.glance
    caps:
      mon: "profile rbd"
      osd: "profile rbd pool={{ openstack_cinder_pool.name }}, profile rbd pool={{ openstack_glance_pool.name }}"
    mode: "0600"
  - name: client.cinder
    caps:
      mon: "profile rbd"
      osd: "profile rbd pool={{ openstack_cinder_pool.name }}, profile rbd pool={{ openstack_nova_pool.name }}, profile rbd pool={{ openstack_glance_pool.name }}"
    mode: "0600"
  - name: client.cinder-backup
    caps:
      mon: "profile rbd"
      osd: "profile rbd pool={{ openstack_cinder_backup_pool.name }}"
    mode: "0600"
  - name: client.nova
    caps:
      mon: "profile rbd"
      osd: "profile rbd pool={{ openstack_nova_pool.name }}"
    mode: "0600"
dashboard_enabled: False
```

(ceph) [root@chnrc-area51-os-build ceph-ansible]# ansible-playbook -i ../inventory site.yml

Output was too long; see http://paste.openstack.org/show/806552/

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

* Kernel (e.g. `uname -a`):
Linux chnrc-area51-os-build.chtrse.com 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):
N/A
* Ansible version (e.g. `ansible-playbook --version`):
(ceph) [root@chnrc-area51-os-build ceph-ansible]# ansible-playbook --version
/opt/ceph/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ansible-playbook 2.9.20
  config file = /opt/ceph/ceph-ansible/ansible.cfg
  configured module search path = [u'/opt/ceph/ceph-ansible/library']
  ansible python module location = /opt/ceph/lib/python2.7/site-packages/ansible
  executable location = /opt/ceph/bin/ansible-playbook
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-4.0
* Ceph version (e.g. `ceph -v`):
nautilus
