### ISSUE TITLE
The ceph-dashboard can't create or add the host and osd devices,the 'create' and 'add ' button was not highlight.

### ISSUE THREAD

**Issue by xudehua** [ceph/ceph-ansible#7034]
**Bug Report**
I had deployed the ceph with ceph-ansible,but the ceph-dashboard can't create or add the host and osd devices,the 'create' and 'add ' button was not highlight.

What happened:

What you expected to happen:

How to reproduce it (minimal and precise):

 deploy the ceph(16.2.7) with ceph-ansible(6.0) on the redhat

Share your group_vars files, inventory and **full** ceph-ansibe log
hosts file
```
[mons]
ceph02
ceph03
ceph04

[mgrs]
ceph02
ceph03
ceph04

[osds]
ceph01
ceph02
ceph03
ceph04

[rgws]
ceph02
ceph03
ceph04

[mdss]
ceph01

[grafana-server]
ceph01

[clients]
ceph01
```

all.yml file
```
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
nfs_group_name: nfss
rbdmirror_group_name: rbdmirrors
client_group_name: clients
iscsi_gw_group_name: iscsigws
mgr_group_name: mgrs
rgwloadbalancer_group_name: rgwloadbalancers
monitoring_group_name: monitoring
configure_firewall: False
ntp_service_enabled: true
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_mirror: https://mirrors.ustc.edu.cn/ceph
ceph_stable_key: https://mirrors.ustc.edu.cn/ceph/keys/release.asc
ceph_stable_release: pacific
ceph_stable_repo: "{{ ceph_mirror }}/rpm-{{ ceph_stable_release }}"
cephx: true
monitor_interface: ens3
ip_version: ipv4
cephfs: cephfs # name of the ceph filesystem
cephfs_data_pool:
  name: "{{ cephfs_data if cephfs_data is defined else 'cephfs_data' }}"
cephfs_metadata_pool:
  name: "{{ cephfs_metadata if cephfs_metadata is defined else 'cephfs_metadata' }}"
cephfs_pools:
  - "{{ cephfs_data_pool }}"
  - "{{ cephfs_metadata_pool }}"
public_network: 172.16.1.0/24
cluster_network: 172.16.1.0/24
osd_objectstore: bluestore
radosgw_civetweb_port: 8080
radosgw_interface: ens3
dashboard_enabled: True
```

**Environment**:
* OS (e.g. from /etc/os-release): redhat 8
* Kernel (e.g. `uname -a`): 4.19.113-10
* Docker version if applicable (e.g. `docker version`): podman version 3.3.1
* Ansible version (e.g. `ansible-playbook --version`): 2.9.27
* ceph-ansible version (e.g. `git head or tag or stable branch`): 6.0
* Ceph version (e.g. `ceph -v`): 16.2.7
