### ISSUE TITLE
ceph-mon : check if monitor initial keyring already exists is hung

### ISSUE THREAD

**Issue by KienHT6** [ceph/ceph-ansible#7203]
**Bug Report**

What happened:
I am running the Ceph ansible script to install ceph version v6.0.27
When running the sample yml file that was supplied by the github repo it
runs fine up until the "ceph-mon : check if monitor initial keyring already
exists" step. There it will hang for 30-40 minutes before failing.

What you expected to happen:

How to reproduce it (minimal and precise):

Share your group_vars files, inventory and **full** ceph-ansibe log
```
root@ubuntu:~# grep -v "^#|^$" /opt/ceph/ceph-ansible/group_vars/all.yml
---

dummy:
cluster: ceph
ntp_service_enabled: true
ntp_daemon_type: chronyd

monitor_interface: ens160
#public_network: "172.29.236.0/22"
public_interface: ens192.236
radosgw_interface: ens192.236
#cluster_network: "172.29.244.0/22"
cluster_interface: ens192.244
ip_version: ipv4

containerized_deployment: true
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest-master
ceph_docker_registry: quay.io
ceph_docker_registry_auth: false
ceph_client_docker_image: "{{ ceph_docker_image }}"
ceph_client_docker_image_tag: "{{ ceph_docker_image_tag }}"
ceph_client_docker_registry: "{{ ceph_docker_registry }}"

ceph_conf_overrides:
  global:
    osd_pool_default_pg_num: 64
    osd_pool_default_pgp_num: 64
    osd_pool_default_size: 2
dashboard_enabled: True
dashboard_protocol: https
dashboard_port: 8443
dashboard_admin_user: admin
dashboard_admin_user_ro: false
dashboard_admin_password: p@ssw0rd
grafana_admin_user: admin
grafana_admin_password: admin
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.4
* Kernel (e.g. `uname -a`):   5.4.0-117-generic#132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Docker version if applicable (e.g. `docker version`): 20.10.17
* Ansible version (e.g. `ansible-playbook --version`): 2.11.6
* ceph-ansible version (e.g. `git head or tag or stable branch`): v6.0.27 (lastest-master) 
* Ceph version (e.g. `ceph -v`): ceph version 17.0.0-12443-gcd081981 (cd08198132e4385177b657dcfea32bfc9f0641c5) quincy (dev)
