### ISSUE TITLE
rgw_pool_create task does not consider pool type = 'ec'

### ISSUE THREAD

**Issue by vahide** [ceph/ceph-ansible#7360]
**Bug Report**

**What happened:**
rgw_pool_create task in ceph-rgw role does not apply pool type = 'ec' and creation of **ec pool** has been skipped.

**What you expected to happen:**
rgw_create_pool should consider 'ec' type. Because of "item.value.type is defined" condition check, it has been ignored and can be resolved by setting condition "item.value.type" without "is defined" like below:

```
 name: create ec profile
  ceph_ec_profile:
    name: "{{ item.value.ec_profile }}"
    cluster: "{{ cluster }}"
    k: "{{ item.value.ec_k }}"
    m: "{{ item.value.ec_m }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  loop: "{{ rgw_create_pools | dict2items }}"
  when:
    - item.value.type 
    - item.value.type == 'ec'
```

**How to reproduce it (minimal and precise):**
set type: 'ec'  for pool type variable in rgw_create_pools section like below:

```
rgw_create_pools:
  "{{ rgw_zone }}.rgw.buckets.data":
    pg_num: 512
    gpg_num: 512
    type: ec
```

****Environment**:**
* OS (e.g. from /etc/os-release):
ubuntu 20.04
* Kernel (e.g. `uname -a`):
Linux bastion 5.4.0-91-
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
2.9
2.10
* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable 5.0
stable 6.0
* Ceph version (e.g. `ceph -v`):
octopus
pacific
