### ISSUE TITLE
Unable to access ceph dashboard (Quincy CEPH)

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-ansible#7362]
I have install ceph Quincy 17.2.5 using ceph-ansible

```ondemand@ubuntucephmgt01:~$ sudo ceph --cluster quincy --version
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
```
=======================================================
Configuration files
all.yml
ondemand@ubuntucephadmin:~/ceph-ansible/group_vars$ cat all.yml |grep -v -E '^#|^$'
```yaml
---
dummy:
cluster: quincy
mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws
mds_group_name: mdss
mgr_group_name: mgrs
monitoring_group_name: monitoring
configure_firewall: True
ceph_mon_firewall_zone: public
ceph_mgr_firewall_zone: public
ceph_osd_firewall_zone: public
ceph_mds_firewall_zone: public
ceph_dashboard_firewall_zone: public
ntp_daemon_type: chronyd
ceph_origin: repository
ceph_repository: community
ceph_stable_release: quincy
generate_fsid: true
monitor_interface: ens160
ip_version: ipv4
dashboard_enabled: True
dashboard_protocol: https
dashboard_port: 8443
dashboard_network: "{{ public_network }}"
dashboard_admin_user: admin
dashboard_admin_password: Qu!Ncy
dashboard_crt: ''
dashboard_key: ''
node_exporter_container_image: "docker.io/prom/node-exporter:v0.17.0"
node_exporter_port: 9100
grafana_admin_user: admin
grafana_admin_password: Qu!Ncy
```

### Mon.yml ###
ondemand@ubuntucephadmin:~/ceph-ansible/group_vars$ cat mons.yml |grep -v -E '^#|^$'

```yaml
---
dummy:
mon_group_name: mons
monitor_secret: "{{ monitor_keyring.stdout }}"
admin_secret: 'admin_secret'
client_admin_ceph_authtool_cap:
  mon: allow *
  osd: allow *
  mds: allow *
  mgr: allow *
```
ondemand@ubuntucephadmin:~/ceph-ansible/group_vars$

### OSD.yml ###
ondemand@ubuntucephadmin:~/ceph-ansible/group_vars$ cat osds.yml |grep -v -E '^#|^$'
```yaml
---
dummy:
devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
osd_auto_discovery: false
dmcrypt: False
osd_objectstore: bluestore
```
ondemand@ubuntucephadmin:~/ceph-ansible/group_vars$
==================================

## Inventory file ###
ondemand@ubuntucephadmin:~/ceph-ansible$ cat quincy-host
```yaml
[hosts:vars]
ansible_ssh_user=ondemand
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

[hosts:children]
mgrs
mons
mdss
osds
monitoring

[hosts:vars]

[monitoring]
ubuntucephmgt01


[mons]
ubuntucephmgt01 monitor_address=10.177.152.202
ubuntucephmgt02 monitor_address=10.177.152.203
ubuntucephmgt03 monitor_address=10.177.152.204

[mgrs]
ubuntucephmgt01
ubuntucephmgt02
ubuntucephmgt03

[mdss]
ubuntucephmds01
ubuntucephmds02

[osds]
ubuntucephosd01
ubuntucephosd02
ubuntucephosd03
ubuntucephosd04
ubuntucephosd05
ubuntucephosd06
```
ondemand@ubuntucephadmin:~/ceph-ansible$
=========================================

```ondemand@ubuntucephmgt01:~$ sudo ceph --cluster quincy -s
  cluster:
    id:     fea02221-0c27-4b2e-b292-7077199da359
    health: HEALTH_WARN
            mons are allowing insecure global_id reclaim

  services:
    mon: 3 daemons, quorum ubuntucephmgt01,ubuntucephmgt02,ubuntucephmgt03 (age 41m)
    mgr: ubuntucephmgt03(active, since 36m), standbys: ubuntucephmgt02, ubuntucephmgt01
    mds: 1/1 daemons up, 1 standby
    osd: 18 osds: 18 up (since 39m), 18 in (since 39m)

  data:
    volumes: 1/1 healthy
    pools:   4 pools, 81 pgs
    objects: 25 objects, 453 KiB
    usage:   400 MiB used, 1.8 TiB / 1.8 TiB avail
    pgs:     81 active+clean
```

ondemand@ubuntucephmgt01:~$
=====================================
```ondemand@ubuntucephmgt01:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:8e:86:15 brd ff:ff:ff:ff:ff:ff
    inet 10.177.152.202/24 brd 10.177.152.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe8e:8615/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:73:4a:fd:9a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
ondemand@ubuntucephmgt01:~$
```

```ondemand@ubuntucephmgt01:~$ sudo docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS          PORTS     NAMES
14d9a5315369   prom/prometheus:v2.7.2       "/bin/prometheus --c…"   37 minutes ago   Up 37 minutes             prometheus
c87b3ad27a7e   prom/alertmanager:v0.16.2    "/bin/alertmanager -…"   37 minutes ago   Up 37 minutes             alertmanager
6d7c4d6cce2c   grafana/grafana:6.7.4        "/run.sh"                37 minutes ago   Up 37 minutes             grafana-server
2d554e9d8e85   prom/node-exporter:v0.17.0   "/bin/node_exporter …"   38 minutes ago   Up 38 minutes             node-exporter
ondemand@ubuntucephmgt01:~$
```

=========================

dashborad is enabled on ubuntucephmgt01. When I try to access dashboard using https://ubuntucephmgt01:8443 its redirecting to ip  172.17.0.1 and dashboard is not accessible... if you see "ip a " output 172.17.0.1 ip address is configured for docker0 interface..

Am I doing something wrong here? Please help me validate the config files and let me know if any corrections are required.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/52532360/209841615-21b1e1e0-290d-45e2-a432-0cc960f8edc0.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/52532360/209841701-c64d2a19-33f4-4f49-b4ae-3ee2f983b3a7.png">
