### ISSUE TITLE
Add Support to install this collection using ansible-galaxy

### ISSUE THREAD

**Issue by ashishsinghdev** [ceph/ceph-ansible#7471]
**Is your feature request related to a problem? Please describe.**
This collection can't be installed using ansible-galaxy because of missing galaxy.yml or MANIFEST.json.

**Describe the solution you'd like**
Add galaxy.yml which is required by ansible-galaxy compatible collections. https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#installing-a-collection-from-a-git-repository

After adding this, this collection can be installed using this configuration.
Create **requirements-galaxy.yml**, example:
```
collections:
- name: https://github.com/ceph/ceph-ansible.git
  type: git
  version: v6.0.28.7
```

Then run this command 
`ansible-galaxy install -r requirements-galaxy.yml`
