### ISSUE TITLE
Enable ceph-mon with service module

### ISSUE THREAD

**Issue by rnowling** [ceph/ceph-ansible#791]
Can the `ceph-mon` service be enabled with the `service` module instead of using `command` in `roles/ceph-mon/tasks/start_monitor.yml`?

I think `enabled=yes` could be added to the task following that:

```
- name: start the monitor service (for or after infernalis)
  service:
      name: ceph-mon
      state: started
      enabled: yes
  changed_when: false
  when:
    - use_systemd
    - is_after_hammer
```

If there is not a specific reason for this, I can submit a patch.
